//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by cinema.rc
//
#define IDSTOPPER                       3
#define IDCIBLES                        3
#define IDD_ABOUTBOX                    100
#define IDD_CINEMA_FORM                 101
#define IDD_CHANGER_PERIODE             102
#define IDB_SPLASH                      103
#define IDD_SELECTIONPRODUIT            104
#define IDD_ANALYSE_FILM                106
#define IDD_CRITERE                     107
#define IDD_GRAPHEFILM                  108
#define IDD_PERFORMANCESFILM            109
#define IDR_MAINFRAME                   128
#define IDR_CINEMATYPE                  129
#define IDR_FILMTYPE                    130
#define IDD_SELPRODBACCOMPLEXE          136
#define IDI_FLECHE                      144
#define IDI_FLECHE2                     145
#define IDD_SELECTION                   145
#define IDC_AJOUTSUPP                   146
#define IDC_BLOCCHANGE                  147
#define IDC_BLOCCOPIERCOLLER            148
#define IDC_BLOCDEPLACEMENT             149
#define IDC_BLOCEFFACE                  150
#define IDC_BLOCMOVE                    151
#define IDC_BLOCTEMPO                   152
#define IDC_DEPLACEMENTTRAIT            153
#define IDC_GLISSEMENT                  154
#define IDC_INTERDIT                    155
#define IDB_PATTERN1                    156
#define IDR_OUTILS                      157
#define IDB_PATTERN2                    158
#define IDD_CHOIXBINOME                 159
#define IDB_PATTERN3                    159
#define IDC_PASSAGE                     160
#define IDB_PATTERN4                    160
#define IDD_CIBLE                       161
#define IDB_PATTERN5                    161
#define IDR_CIBLE                       162
#define IDB_PATTERN6                    162
#define IDD_FONCTIONCIBLE               163
#define IDD_PERFORMANCES                164
#define IDD_OPTIONCALCUL                165
#define IDD_BUDGETNET                   166
#define IDD_BETA                        167
#define IDI_CIBLE                       167
#define IDD_DUREE                       168
#define IDD_GRAPHE                      169
#define IDB_TOM                         170
#define IDD_CHOIXTEMPO                  171
#define IDD_OPTIMISATION                173
#define IDD_ATTENTE                     175
#define IDD_PARAMPRINT                  178
#define IDR_TOOLBARNOTUSED              179
#define IDD_PERFORMANCES2               179
#define IDI_ICON1                       183
#define IDB_PATTERN7                    183
#define IDD_MAINTENANCE                 184
#define IDR_MAINFRAME1                  184
#define IDB_PATTERN8                    184
#define IDD_MULTICIBLE                  185
#define IDD_UNITEMONETAIRE              186
#define IDD_SELCOMPLEXE                 186
#define IDB_LOGOJFC                     198
#define IDD_FORMULAIRE_FILM             203
#define IDI_ICON2                       204
#define IDD_OPTIONCALCULFILM            205
#define IDD_OPTIONCALCULMEMO            206
#define IDD_PERFAGLO                    207
#define IDD_EXPORT_MEDIAVISION          211
#define IDD_TESTUGRID                   212
#define IDD_DIALOG1                     213
#define IDD_EXPORT_SCREENVISION         214
#define IDC_BUTTON1                     1000
#define IDC_BUTTON2                     1001
#define IDC_OK                          1001
#define IDC_BUTTON3                     1002
#define IDC_ANNULER                     1002
#define IDC_BUTTON4                     1003
#define IDC_MONTER                      1003
#define IDC_INVERSER                    1003
#define IDC_SELTOUT2                    1003
#define IDC_CALENDRIER                  1004
#define IDC_DESCENDRE                   1004
#define IDC_SELTOUT                     1004
#define IDC_INVERSER2                   1004
#define IDC_BINOME                      1005
#define IDC_SUPP                        1005
#define IDC_NBPASSAGES                  1006
#define IDC_AJOUTBAC                    1006
#define IDC_AJOUT                       1006
#define IDC_GRILLE                      1007
#define IDC_AJOUTPRODUIT                1007
#define IDC_HSCROLL                     1008
#define IDC_SCROLLBAR1                  1009
#define IDC_CADRE                       1010
#define IDC_CADRE1                      1011
#define IDC_CADRE7                      1011
#define IDC_HYPOTHESE4                  1012
#define IDC_CADRE4                      1012
#define IDC_HYPOTHESE5                  1013
#define IDC_CADRE5                      1013
#define IDC_LISTSELECT                  1013
#define IDC_LIST                        1013
#define IDC_HYPOTHESE2                  1014
#define IDC_CADRE6                      1014
#define IDC_LIST_GRP_BACS               1014
#define IDC_LIST_GRP_CMPLX              1014
#define IDC_HYPOTHESE1                  1015
#define IDC_CADRE8                      1015
#define IDC_HYPOTHESE3                  1016
#define IDC_CADRE9                      1016
#define IDC_CADRE2                      1017
#define IDC_CADRE12                     1017
#define IDC_DUREE1                      1018
#define IDC_DUREE2                      1019
#define IDC_DUREE3                      1020
#define IDC_DUREE4                      1021
#define IDC_DUREE5                      1022
#define IDC_CADRE3                      1023
#define IDC_EFFACER                     1024
#define IDC_RADIO1                      1025
#define IDC_BUTTONCHOIX                 1025
#define IDC_RADIO2                      1026
#define IDC_LIST1                       1026
#define IDC_LIST2                       1027
#define IDC_RADIODEMEMORISATION         1027
#define IDC_RADIO3                      1027
#define IDC_LIST3                       1028
#define IDC_RADIO4                      1028
#define IDC_EDIT1                       1029
#define IDC_RADIOSAISONNALITE           1029
#define IDC_EDIT2                       1030
#define IDC_RADIO6                      1030
#define IDC_EDIT3                       1031
#define IDC_RADIODUREE                  1031
#define IDC_EDIT_DUREE                  1032
#define IDC_EDIT4                       1032
#define IDC_RADIO7                      1032
#define IDC_EDIT5                       1033
#define IDC_RADIOCNCA                   1033
#define IDC_EDIT6                       1034
#define IDC_RADIOCNCP                   1034
#define IDC_EDIT7                       1035
#define IDC_RADIOBASEN                  1035
#define IDC_EDIT8                       1036
#define IDC_RADIOBASER                  1036
#define IDC_SPIN_DUREE                  1037
#define IDC_TITRESEGMENT                1037
#define IDC_EDITCOUVERTURE              1037
#define IDC_RADIO5                      1037
#define IDC_PANORAMA                    1038
#define IDC_EDITCOUVERTUREMEMO          1038
#define IDC_RADIO8                      1038
#define IDC_GRAPHE                      1039
#define IDC_PERF                        1040
#define IDC_OPTIMISATION                1041
#define IDC_MAJFILM                     1041
#define IDC_PERFAGGLO                   1041
#define IDC_OB                          1042
#define IDC_RADIOBASEDECALCUL           1043
#define IDC_OB2                         1043
#define IDC_GRILLE2                     1044
#define IDC_GRILLE1                     1045
#define IDC_GRILLE3                     1046
#define IDC_GRILLE4                     1047
#define IDC_COMBO1                      1048
#define IDC_LISTTEMPO                   1049
#define IDC_SPINNBVAGUEMIN              1050
#define IDC_CIBLE3                      1050
#define IDC_NBVAGUEMIN                  1051
#define IDC_CIBLE4                      1051
#define IDC_NBVAGUEMAX                  1052
#define IDC_CIBLE5                      1052
#define IDC_NBTEMPOMIN                  1053
#define IDC_INTERVAGUEMIN               1054
#define IDC_SPINNBVAGUEMAX              1055
#define IDC_SPINNBTEMPOMIN              1056
#define IDC_DATE_DEBUT                  1057
#define IDC_SPININTERVAGUEMIN           1057
#define IDC_SPINECONOMIE                1058
#define IDC_SPINCOUVERTURE              1059
#define IDC_SPINCEOUVERTUREMEMORISE     1060
#define IDC_EDITECONOMIE                1061
#define IDC_EDITBUDGET                  1062
#define IDC_TOLERANCE                   1063
#define IDC_SPINTOLERANCE               1064
#define IDC_COMBOOPTIMISATION           1065
#define IDC_CHECKNOYAU                  1066
#define IDC_FLAGUSEALL                  1067
#define IDC_NBPLAN1                     1068
#define IDC_NBPLAN2                     1069
#define IDC_DECHARGER                   1069
#define IDC_GRID                        1070
#define IDC_COMBOANNEE                  1071
#define IDC_RADIOFRANC_EURO             1072
#define IDC_RADIOFRANC_EURO2            1073
#define IDC_PROGRESS1                   1073
#define IDC_COULHYPVALIDE               1074
#define IDC_COULHYPACTIVE               1075
#define IDC_COULHYPVALIDE1              1075
#define IDC_COULHYPACTIVE1              1076
#define IDC_COULHYPVALIDE2              1077
#define IDC_COULHYPACTIVE2              1078
#define IDC_CIBLE1                      1079
#define IDC_CIBLE2                      1080
#define IDC_NOMCAMPAGNE                 1081
#define LABEL_CAMPAGNE                  1082
#define LABEL_ANNONCEUR                 1083
#define LABEL_CENTRAL                   1084
#define LABEL_PRODUIT                   1085
#define IDC_NOMANNONCEUR                1086
#define IDC_NOMCENTRALE                 1087
#define IDC_NOMPRODUIT                  1088
#define IDC_CADRELIBELLE                1090
#define IDC_SELECTION                   1091
#define IDC_AJOUTCOMPLX                 1093
#define IDC_PERFORMANCES                1094
#define IDC_AJOUTER                     1094
#define IDC_NOMCOMPLEXE                 1095
#define IDC_OPTION                      1099
#define IDC_TYPE                        1100
#define IDC_LIBELLE                     1101
#define IDC_COMBOREGIE                  1101
#define IDC_REGIE                       1102
#define IDC_COMBOREGIE2                 1102
#define IDC_BARRE                       1103
#define IDC_REGIE2                      1103
#define IDC_DATETIMEPICKER1             1104
#define IDC_DATETIME                    1104
#define IDC_BARRE3                      1105
#define IDC_CADRE10                     1105
#define IDC_CADRE11                     1106
#define IDC_PERIODE                     1111
#define IDC_CIBLEBASE                   1112
#define IDC_GRID_FILM                   1113
#define IDC_CADRE0                      1115
#define IDC_CAMPAGNEFILM                1116
#define IDC_PREC_FILM                   1118
#define IDC_SUIV_FILM                   1119
#define IDC_COMBO_RESEAUDISTR           1120
#define IDC_EDIT_TITRE                  1121
#define IDC_EDIT_TARIF                  1122
#define IDC_EDIT_ENTREECNC              1125
#define IDC_GRID_COEFFUSURE             1126
#define IDC_GRID_COEFFMODA              1127
#define IDC_CRITEREBASE                 1127
#define IDC_LISTCRITERE                 1128
#define IDC_EDIT_NBSEM                  1129
#define IDC_SPIN_NBSEM                  1130
#define IDC_SUPPFILM                    1131
#define IDC_NOFILM                      1132
#define IDC_COMBO_CRITERE               1133
#define IDC_GRILLEF1                    1147
#define IDC_GRILLEF2                    1148
#define IDC_GRILLEF3                    1149
#define IDC_GRILLEF4                    1150
#define IDC_FILMRADIOBASEN              1152
#define IDC_FILMRADIOBASER              1153
#define IDC_RADIOAGGLO                  1155
#define LABEL_TITRE                     1156
#define IDC_NOMTITRE                    1157
#define LABEL_SSTITRE                   1158
#define IDC_NOMSSTITRE                  1159
#define LABEL_DATEDEBUT                 1160
#define IDC_DATEDEBUT                   1161
#define LABEL_DATEDEBUT2                1162
#define IDC_DATEFIN                     1163
#define IDC_LISTCIBLES                  1164
#define IDC_LISTSELCIBLES               1165
#define IDC_UGRID                       1165
#define IDC_CIBLES                      1166
#define IDC_CIBLE_PERF_SEM              1167
#define ID_PARAMTRES_EXERCICE           32771
#define ID_PARAMTRES_DURE               32772
#define ID_PARAMTRES_CIBLE1             32773
#define ID_PARAMTRES_CIBLE2             32774
#define ID_PARAMTRES_BTA                32775
#define ID_PARAMTRES_BUDGETNET          32776
#define ID_CAMPAGNE_EXPORTER            32777
#define ID_PARAMTRES_BINME              32778
#define ID_OUTILS_AJOUTERSUPPRIMER      32786
#define ID_OUTILS_GLISSER               32787
#define ID_OUTILS_TEMPO                 32788
#define ID_OUTILS_GOMMER                32789
#define ID_OUTILS_DURE                  32790
#define ID_OUTILS_COUPER                32791
#define ID_OUTILS_COPIERCOLLER          32792
#define ID_CIBLE_NOUVELLE               32794
#define ID_CIBLE_CHARGER                32795
#define ID_CIBLE_MMORISER               32796
#define ID_CIBLE_RENOMER                32798
#define ID_CIBLE_SUPPRIMER              32799
#define ID_CIBLE_FERMER                 32800
#define ID_AFFICHAGE_RPERTOIREDECIBLES  32801
#define ID_MAINTENANCE_TARIFS           32802
#define ID_MAINTENANCE_SAISONALITS      32803
#define ID_MAINTENANCE_DURES            32804
#define IDC_ACTION_COPIER               32805
#define ID_AFFICHAGE_BARREDOUTILSSOURIS 32808
#define ID_ACTION_COLLER                32809
#define ID_ACTION_RECOPIERDANSLHYPOTHESEACTIVE_LHYPOTHSE1 32810
#define ID_ACTION_RECOPIERDANSLHYPOTHESEACTIVE_LHYPOTHSE2 32811
#define ID_ACTION_RECOPIERDANSLHYPOTHESEACTIVE_LHYPOTHSE3 32812
#define ID_ACTION_RECOPIERDANSLHYPOTHESEACTIVE_LHYPOTHSE4 32813
#define ID_ACTION_RECOPIERDANSLHYPOTHESEACTIVE_LHYPOTHSE5 32814
#define IDC_ACTION_VALIDER              32815
#define ID_PARAMTRES_OPTIONDECALCUL     32818
#define ID_AFFICHAGE_TEST               32819
#define ID_FILE_PRINT2                  32821
#define ID_MAINTENANCE_VISUALISATION    32831
#define ID_MAINTENANCE_INTEGRATION      32832
#define ID_PARAMTRES_UNITEMONTAIRE      32835
#define ID_PARAMTRES_FORMAT             32837
#define ID_CIBLE_MEMOSOUS               32838
#define ID_SELECT                       32839
#define ID_PARAMTRES_OPTIONDECALCULMEMO 32844
#define ID_EXPORT_MEDIAVISION           32845
#define ID_EXPORT_SCREENVISION          32846
#define ID_PIEDPAGE1_POPNAT             59394
#define ID_PIEDPAGE1_BAC_COUVERTS       59395
#define ID_PIEDPAGE2                    59396
#define ID_PIEDPAGE3                    59397
#define ID_PIEDPAGE_PRINTFILM           59398

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        215
#define _APS_NEXT_COMMAND_VALUE         32847
#define _APS_NEXT_CONTROL_VALUE         1168
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
