//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RepSupports.rc
//
#define IDM_RS_ABOUTBOX                 16
#define IDS_RS_TRFDTOD                  17
#define IDD_RS_DLGDATAEXO               18
#define IDD_RS_ABOUTBOX                 3000
#define IDD_RS_DLGAPPARENTE             3001
#define IDD_RS_DLGAPPARIE               3002
#define IDD_RS_DLGCOUPLAGE              3003
#define IDD_RS_DLGFAMILLE               3004
#define IDD_RS_DLGLOT                   3005
#define IDD_RS_DLGRENAME                3006
#define IDD_RS_DLGTARIF                 3007
#define IDD_RS_REPSUPPORTS_DIALOG       3008
#define IDI_RS_LEDOFF                   3009
#define IDI_RS_LEDON                    3010
#define IDI_RS_MAINFRAME                3011
#define IDM_RS_CTXLST2_RENAME           3013
#define IDM_RS_CTXLST2_SUPPR            3014
#define IDM_RS_CTXLST_RENAME            3015
#define IDM_RS_CTXLST_SUPPR             3016
#define IDM_RS_PALETTE_1                3017
#define IDM_RS_PALETTE_2                3018
#define IDM_RS_PALETTE_3                3019
#define IDM_RS_PALETTE_4                3020
#define IDM_RS_PALETTE_5                3021
#define IDM_RS_PALETTE_6                3022
#define IDM_RS_PALETTE_7                3023
#define IDM_RS_PALETTE_8                3024
#define IDM_RS_PALETTE_9                3025
#define IDM_RS_PALETTE_10               3026
#define IDR_RS_MENU                     3027
#define IDR_RS_MENUCTXTREE              3028
#define IDS_RS_ABOUTBOX                 3029
#define IDS_RS_MWOUTBOUNDS              3030
#define IDB_RS_MULTISEL                 3031
#define IDS_RS_TRFD                     3032
#define IDS_RS_TARIFS                   3033
#define IDS_RS_NEW_FAMILLE              3034
#define IDM_RS_PALETTE_11               3035
#define IDM_RS_PALETTE_12               3036
#define IDM_RS_PALETTE_13               3037
#define IDM_RS_PALETTE_14               3038
#define IDM_RS_PALETTE_15               3039
#define IDC_RS_BKREN                    3500
#define IDC_RS_BTNEFFCONTAINER          3501
#define IDC_RS_BTNEFFSAS                3502
#define IDC_RS_BTNGENESE                3503
#define IDC_RS_STATICDATA               3504
#define IDC_RS_BTNSEARCH                3505
#define IDC_RS_STATICBTN                3505
#define IDC_RS_BTNSELCENTRE             3506
#define IDC_RS_BTNSELFAMILLE            3507
#define IDC_RS_BTNSELPER                3508
#define IDC_RS_BTNVALID                 3509
#define IDC_RS_BTNVALIDFSPE             3510
#define IDC_RS_BUTTONSELPER             3511
#define IDC_RS_CHECKNA                  3512
#define IDC_RS_COMBOSOURCE              3513
#define IDC_RS_COMBOTERRAIN             3514
#define IDC_RS_DLGSTATIC                3515
#define IDC_RS_EDITCOUPLAGE             3516
#define IDC_RS_EDITDATED                3517
#define IDC_RS_EDITDATEF                3518
#define IDC_RS_EDITFORMAT               3519
#define IDC_RS_EDITFORMATSPE            3520
#define IDC_RS_EDITLOT                  3521
#define IDC_RS_EDITMW                   3522
#define IDC_RS_EDITNOM                  3523
#define IDC_RS_EDITSEARCH               3524
#define IDC_RS_EDITTARIF                3525
#define IDC_RS_EDITTITREAPPARENTE       3526
#define IDC_RS_EDITTITREAPPARIE         3527
#define IDC_RS_EDITTITREHS              3528
#define IDC_RS_LIBELLE                  3529
#define IDC_RS_LISTABATTEMENT           3530
#define IDC_RS_LISTAPPARENTE            3531
#define IDC_RS_LISTAPPARIE              3532
#define IDC_RS_LISTCENTRE               3533
#define IDC_RS_STATICCENTRE             3534
#define IDC_RS_STATICTTLDATA            3535
#define IDC_RS_LISTCENTRE2              3535
#define IDC_RS_LISTCOUPLAGE             3536
#define IDC_RS_STATICTTLBTN             3536
#define IDC_RS_LISTFAMILLE              3537
#define IDC_RS_LISTFORMAT               3538
#define IDC_RS_LISTFAMILLE2             3538
#define IDC_RS_LISTFORMATSPE            3539
#define IDC_RS_LISTFORMATSTD            3540
#define IDC_RS_LISTHS                   3541
#define IDC_RS_LISTLOT                  3542
#define IDC_RS_LISTNBINSERT             3543
#define IDC_RS_LISTPER                  3544
#define IDC_RS_LISTTARIF                3545
#define IDC_RS_LISTPER2                 3545
#define IDC_RS_LISTTITRE                3546
#define IDC_RS_LISTTITRECOUPLAGE        3547
#define IDC_RS_LISTTITRE2               3547
#define IDC_RS_LISTTITREHORS            3548
#define IDC_RS_LISTTITRELOT             3549
#define IDC_RS_RADIO_APP                3550
#define IDC_RS_RADIO_CPL                3551
#define IDC_RS_RADIO_FAM                3552
#define IDC_RS_RADIO_HS                 3553
#define IDC_RS_RADIO_LOT                3554
#define IDC_RS_RADIO_TAR                3555
#define IDC_RS_RADIO_EXO                3556
#define IDC_RS_STATICCOMBOS             3559
#define IDC_RS_STATICCOUPLAGE           3560
#define IDC_RS_STATICCUSTOM             3562
#define IDC_RS_STATICFAM                3564
#define IDC_RS_STATICFAMILLE            3565
#define IDC_RS_STATICFORMAT             3566
#define IDC_RS_STATICGRID               3567
#define IDC_RS_STATICLOT                3568
#define IDC_RS_STATICNBTITRE            3569
#define IDC_RS_STATICPER                3570
#define IDC_RS_STATICRESTE              3571
#define IDC_RS_STATICTITRE              3572
#define IDC_RS_STATICTITREHORS          3573
#define IDC_RS_STATICTITRELOT           3574
#define IDC_RS_STATICTREE               3575
#define IDC_RS_STATICTTLCENTRE          3576
#define IDC_RS_STATICTTLCOUPLAGE        3579
#define IDC_RS_STATICTTLCUSTOM          3580
#define IDC_RS_STATICTTLDATED           3581
#define IDC_RS_STATICTTLDATEF           3582
#define IDC_RS_STATICTTLFAM             3583
#define IDC_RS_STATICTTLFAMILLE         3584
#define IDC_RS_STATICTTLFORMAT          3585
#define IDC_RS_STATICTTLFORMATSPE       3586
#define IDC_RS_STATICTTLFORMATSTD       3587
#define IDC_RS_STATICTTLLOT             3588
#define IDC_RS_STATICTTLNB              3589
#define IDC_RS_STATICTTLNBINSERT        3590
#define IDC_RS_STATICTTLPER             3591
#define IDC_RS_STATICTTLSOURCE          3592
#define IDC_RS_STATICTTLTAPP            3593
#define IDC_RS_STATICTTLTAPPARENTE      3594
#define IDC_RS_STATICTTLTAPPARIE        3595
#define IDC_RS_STATICTTLTARIF           3596
#define IDC_RS_STATICTTLTCOUPL          3597
#define IDC_RS_STATICTTLTCOUPLAGE       3598
#define IDC_RS_STATICTTLTERRAIN         3599
#define IDC_RS_STATICTTLTFORMATSPE      3600
#define IDC_RS_STATICTTLTITRE           3601
#define IDC_RS_STATICTTLTITREHORS       3602
#define IDC_RS_STATICTTLTITRELOT        3603
#define IDC_RS_STATICTTLTTEMOIN         3604
#define IDC_RS_STATICTTLTTUTEUR         3605
#define IDC_RS_STATICTXT                3606
#define IDC_RS_STATICTXTFORMAT          3607
#define IDC_RS_STATICTXTMW              3608
#define IDC_RS_STATICTXTNB              3609
#define IDC_RS_STATICTXTNBMW            3610
#define IDC_RS_STATICTXTNBTITRE         3611
#define IDC_RS_STATICTXTNBTITRECPL      3612
#define IDC_RS_STATICTXTNBTITRELOT      3613
#define IDC_RS_STATICTXTNOM             3614
#define IDC_RS_STATICTXTTITRE           3615
#define IDC_RS_STATICTXTTITRE2          3616
#define IDC_RS_STATICTXTTITRETUTEUR     3617
#define IDC_RS_TREEFAM                  3618
#define IDC_RS_TTLREN                   3619
#define IDC_RS_STATICTTLLSTDATA         3621
#define IDC_RS_STATICLSTDATA            3622
#define IDC_RS_LISTDATA                 3623
#define IDC_RS_MAJFORM                  3624
#define IDC_RS_CREATEFORM               3624
#define IDC_RS_IMPORTFORM               3625
#define IDC_RS_EXPORTFORM               3626
#define IDC_RS_COMBO                    3627
#define IDC_RS_BKGBTN                   3629
#define IDC_ATP_BK                      6100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        2
#define _APS_NEXT_COMMAND_VALUE         32817
#define _APS_NEXT_CONTROL_VALUE         3630
#define _APS_NEXT_SYMED_VALUE           3720
#endif
#endif
