//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.296
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Ce code source a été automatiquement généré par xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Config {
    
    private string arField;
    
    private string inField;
    
    private string outField;
    
    /// <remarks/>
    public string Ar {
        get {
            return this.arField;
        }
        set {
            this.arField = value;
        }
    }
    
    /// <remarks/>
    public string In {
        get {
            return this.inField;
        }
        set {
            this.inField = value;
        }
    }
    
    /// <remarks/>
    public string Out {
        get {
            return this.outField;
        }
        set {
            this.outField = value;
        }
    }
}
