//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Ce code source a été automatiquement généré par xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Study {
    
    private StudyRoot_Cartouche root_CartoucheField;
    
    private StudyRoot_Plans root_PlansField;
    
    private decimal fileVersionField;
    
    /// <remarks/>
    public StudyRoot_Cartouche Root_Cartouche {
        get {
            return this.root_CartoucheField;
        }
        set {
            this.root_CartoucheField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_Plans Root_Plans {
        get {
            return this.root_PlansField;
        }
        set {
            this.root_PlansField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal FileVersion {
        get {
            return this.fileVersionField;
        }
        set {
            this.fileVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_Cartouche {
    
    private StudyRoot_CartoucheInformation informationField;
    
    private StudyRoot_CartoucheDate dateField;
    
    private StudyRoot_CartouchePeriode periodeField;
    
    private StudyRoot_CartoucheEchange echangeField;
    
    private StudyRoot_CartoucheDivers diversField;
    
    private StudyRoot_CartoucheBlocCoches blocCochesField;
    
    private StudyRoot_CartoucheBlocVagues blocVaguesField;
    
    private StudyRoot_CartoucheBlocStations blocStationsField;
    
    private object blocListeStaPasHeureField;
    
    private object blocListeStaPasEcranField;
    
    private object blocListeCorGrpField;
    
    private StudyRoot_CartoucheBlocFormats blocFormatsField;
    
    private object blocFormatsSpecifsField;
    
    private StudyRoot_CartoucheBlocStrates blocStratesField;
    
    private StudyRoot_CartoucheBlocEtudeOption blocEtudeOptionField;
    
    private StudyRoot_CartoucheBlocCampagne blocCampagneField;
    
    private StudyRoot_CartoucheBlocTarification blocTarificationField;
    
    private StudyRoot_CartoucheBlocTitrePerso blocTitrePersoField;
    
    private StudyRoot_CartoucheBlocSpecifYacast blocSpecifYacastField;
    
    /// <remarks/>
    public StudyRoot_CartoucheInformation Information {
        get {
            return this.informationField;
        }
        set {
            this.informationField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheDate Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartouchePeriode Periode {
        get {
            return this.periodeField;
        }
        set {
            this.periodeField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheEchange Echange {
        get {
            return this.echangeField;
        }
        set {
            this.echangeField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheDivers Divers {
        get {
            return this.diversField;
        }
        set {
            this.diversField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocCoches blocCoches {
        get {
            return this.blocCochesField;
        }
        set {
            this.blocCochesField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocVagues blocVagues {
        get {
            return this.blocVaguesField;
        }
        set {
            this.blocVaguesField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocStations blocStations {
        get {
            return this.blocStationsField;
        }
        set {
            this.blocStationsField = value;
        }
    }
    
    /// <remarks/>
    public object blocListeStaPasHeure {
        get {
            return this.blocListeStaPasHeureField;
        }
        set {
            this.blocListeStaPasHeureField = value;
        }
    }
    
    /// <remarks/>
    public object blocListeStaPasEcran {
        get {
            return this.blocListeStaPasEcranField;
        }
        set {
            this.blocListeStaPasEcranField = value;
        }
    }
    
    /// <remarks/>
    public object blocListeCorGrp {
        get {
            return this.blocListeCorGrpField;
        }
        set {
            this.blocListeCorGrpField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocFormats blocFormats {
        get {
            return this.blocFormatsField;
        }
        set {
            this.blocFormatsField = value;
        }
    }
    
    /// <remarks/>
    public object blocFormatsSpecifs {
        get {
            return this.blocFormatsSpecifsField;
        }
        set {
            this.blocFormatsSpecifsField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocStrates blocStrates {
        get {
            return this.blocStratesField;
        }
        set {
            this.blocStratesField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocEtudeOption blocEtudeOption {
        get {
            return this.blocEtudeOptionField;
        }
        set {
            this.blocEtudeOptionField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocCampagne blocCampagne {
        get {
            return this.blocCampagneField;
        }
        set {
            this.blocCampagneField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocTarification blocTarification {
        get {
            return this.blocTarificationField;
        }
        set {
            this.blocTarificationField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocTitrePerso blocTitrePerso {
        get {
            return this.blocTitrePersoField;
        }
        set {
            this.blocTitrePersoField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocSpecifYacast blocSpecifYacast {
        get {
            return this.blocSpecifYacastField;
        }
        set {
            this.blocSpecifYacastField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheInformation {
    
    private string nomField;
    
    private long numeroEtuField;
    
    private short etapeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nom {
        get {
            return this.nomField;
        }
        set {
            this.nomField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long NumeroEtu {
        get {
            return this.numeroEtuField;
        }
        set {
            this.numeroEtuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Etape {
        get {
            return this.etapeField;
        }
        set {
            this.etapeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheDate {
    
    private short dateDebutField;
    
    private short dateFinField;
    
    private short dateDebut010180Field;
    
    private short dateFin010180Field;
    
    private int dateEtudeValideField;
    
    private short dateHeureExtraitConsolideField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short DateDebut {
        get {
            return this.dateDebutField;
        }
        set {
            this.dateDebutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short DateFin {
        get {
            return this.dateFinField;
        }
        set {
            this.dateFinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short DateDebut010180 {
        get {
            return this.dateDebut010180Field;
        }
        set {
            this.dateDebut010180Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short DateFin010180 {
        get {
            return this.dateFin010180Field;
        }
        set {
            this.dateFin010180Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int DateEtudeValide {
        get {
            return this.dateEtudeValideField;
        }
        set {
            this.dateEtudeValideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short DateHeureExtraitConsolide {
        get {
            return this.dateHeureExtraitConsolideField;
        }
        set {
            this.dateHeureExtraitConsolideField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartouchePeriode {
    
    private int dateDebutPeriodeAField;
    
    private ushort nbSemainePeriodeAField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int DateDebutPeriodeA {
        get {
            return this.dateDebutPeriodeAField;
        }
        set {
            this.dateDebutPeriodeAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort NbSemainePeriodeA {
        get {
            return this.nbSemainePeriodeAField;
        }
        set {
            this.nbSemainePeriodeAField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheEchange {
    
    private string tauxEchangeField;
    
    private short deviseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TauxEchange {
        get {
            return this.tauxEchangeField;
        }
        set {
            this.tauxEchangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Devise {
        get {
            return this.deviseField;
        }
        set {
            this.deviseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheDivers {
    
    private short nrMaillageField;
    
    private string agrJoursField;
    
    private string plageHoraireField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NrMaillage {
        get {
            return this.nrMaillageField;
        }
        set {
            this.nrMaillageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AgrJours {
        get {
            return this.agrJoursField;
        }
        set {
            this.agrJoursField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PlageHoraire {
        get {
            return this.plageHoraireField;
        }
        set {
            this.plageHoraireField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocCoches {
    
    private string etatSelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string EtatSel {
        get {
            return this.etatSelField;
        }
        set {
            this.etatSelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocVagues {
    
    private object vagueUtilField;
    
    private StudyRoot_CartoucheBlocVaguesVagueRefSource vagueRefSourceField;
    
    /// <remarks/>
    public object VagueUtil {
        get {
            return this.vagueUtilField;
        }
        set {
            this.vagueUtilField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocVaguesVagueRefSource VagueRefSource {
        get {
            return this.vagueRefSourceField;
        }
        set {
            this.vagueRefSourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocVaguesVagueRefSource {
    
    private StudyRoot_CartoucheBlocVaguesVagueRefSourceVague vagueField;
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocVaguesVagueRefSourceVague Vague {
        get {
            return this.vagueField;
        }
        set {
            this.vagueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocVaguesVagueRefSourceVague {
    
    private short codeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocStations {
    
    private StudyRoot_CartoucheBlocStationsGroupeStation groupeStationField;
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocStationsGroupeStation GroupeStation {
        get {
            return this.groupeStationField;
        }
        set {
            this.groupeStationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocStationsGroupeStation {
    
    private StudyRoot_CartoucheBlocStationsGroupeStationStations[] stationsField;
    
    private StudyRoot_CartoucheBlocStationsGroupeStationLienTarifs[] lienTarifsField;
    
    private string nomField;
    
    private short numeroMaillageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Stations")]
    public StudyRoot_CartoucheBlocStationsGroupeStationStations[] Stations {
        get {
            return this.stationsField;
        }
        set {
            this.stationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LienTarifs")]
    public StudyRoot_CartoucheBlocStationsGroupeStationLienTarifs[] LienTarifs {
        get {
            return this.lienTarifsField;
        }
        set {
            this.lienTarifsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nom {
        get {
            return this.nomField;
        }
        set {
            this.nomField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NumeroMaillage {
        get {
            return this.numeroMaillageField;
        }
        set {
            this.numeroMaillageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocStationsGroupeStationStations {
    
    private StudyRoot_CartoucheBlocStationsGroupeStationStationsStation[] stationField;
    
    private short codeRegField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Station")]
    public StudyRoot_CartoucheBlocStationsGroupeStationStationsStation[] Station {
        get {
            return this.stationField;
        }
        set {
            this.stationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short CodeReg {
        get {
            return this.codeRegField;
        }
        set {
            this.codeRegField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocStationsGroupeStationStationsStation {
    
    private short codeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocStationsGroupeStationLienTarifs {
    
    private StudyRoot_CartoucheBlocStationsGroupeStationLienTarifsRegStaTarif[] regStaTarifField;
    
    private short codeRegField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RegStaTarif")]
    public StudyRoot_CartoucheBlocStationsGroupeStationLienTarifsRegStaTarif[] RegStaTarif {
        get {
            return this.regStaTarifField;
        }
        set {
            this.regStaTarifField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short CodeReg {
        get {
            return this.codeRegField;
        }
        set {
            this.codeRegField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocStationsGroupeStationLienTarifsRegStaTarif {
    
    private short typeEvolutifField;
    
    private short dateField;
    
    private short numeroTarifField;
    
    private string codeTarifField;
    
    private short txMGarantiField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short TypeEvolutif {
        get {
            return this.typeEvolutifField;
        }
        set {
            this.typeEvolutifField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NumeroTarif {
        get {
            return this.numeroTarifField;
        }
        set {
            this.numeroTarifField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CodeTarif {
        get {
            return this.codeTarifField;
        }
        set {
            this.codeTarifField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short TxMGaranti {
        get {
            return this.txMGarantiField;
        }
        set {
            this.txMGarantiField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocFormats {
    
    private StudyRoot_CartoucheBlocFormatsFormat[] formatField;
    
    private short baseFormatField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Format")]
    public StudyRoot_CartoucheBlocFormatsFormat[] Format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short BaseFormat {
        get {
            return this.baseFormatField;
        }
        set {
            this.baseFormatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocFormatsFormat {
    
    private short indexField;
    
    private short dureeField;
    
    private short nbFoisField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Duree {
        get {
            return this.dureeField;
        }
        set {
            this.dureeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NbFois {
        get {
            return this.nbFoisField;
        }
        set {
            this.nbFoisField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocStrates {
    
    private StudyRoot_CartoucheBlocStratesStrate strateField;
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocStratesStrate Strate {
        get {
            return this.strateField;
        }
        set {
            this.strateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocStratesStrate {
    
    private short indexField;
    
    private short numeroField;
    
    private short nbFoisField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Numero {
        get {
            return this.numeroField;
        }
        set {
            this.numeroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NbFois {
        get {
            return this.nbFoisField;
        }
        set {
            this.nbFoisField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocEtudeOption {
    
    private StudyRoot_CartoucheBlocEtudeOptionOptionClassement optionClassementField;
    
    private StudyRoot_CartoucheBlocEtudeOptionOptionPoids optionPoidsField;
    
    private StudyRoot_CartoucheBlocEtudeOptionOptionAffinite optionAffiniteField;
    
    private StudyRoot_CartoucheBlocEtudeOptionOptionTarif optionTarifField;
    
    private StudyRoot_CartoucheBlocEtudeOptionOptionCalcul optionCalculField;
    
    private StudyRoot_CartoucheBlocEtudeOptionOptionEdition optionEditionField;
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocEtudeOptionOptionClassement OptionClassement {
        get {
            return this.optionClassementField;
        }
        set {
            this.optionClassementField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocEtudeOptionOptionPoids OptionPoids {
        get {
            return this.optionPoidsField;
        }
        set {
            this.optionPoidsField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocEtudeOptionOptionAffinite OptionAffinite {
        get {
            return this.optionAffiniteField;
        }
        set {
            this.optionAffiniteField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocEtudeOptionOptionTarif OptionTarif {
        get {
            return this.optionTarifField;
        }
        set {
            this.optionTarifField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocEtudeOptionOptionCalcul OptionCalcul {
        get {
            return this.optionCalculField;
        }
        set {
            this.optionCalculField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocEtudeOptionOptionEdition OptionEdition {
        get {
            return this.optionEditionField;
        }
        set {
            this.optionEditionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocEtudeOptionOptionClassement {
    
    private short fClasMixteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short fClasMixte {
        get {
            return this.fClasMixteField;
        }
        set {
            this.fClasMixteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocEtudeOptionOptionPoids {
    
    private short poidsPuiField;
    
    private short poidsEcoField;
    
    private short poidsAffField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short PoidsPui {
        get {
            return this.poidsPuiField;
        }
        set {
            this.poidsPuiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short PoidsEco {
        get {
            return this.poidsEcoField;
        }
        set {
            this.poidsEcoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short PoidsAff {
        get {
            return this.poidsAffField;
        }
        set {
            this.poidsAffField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocEtudeOptionOptionAffinite {
    
    private short nrCibleBaseAffField;
    
    private short fAffIndiceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NrCibleBaseAff {
        get {
            return this.nrCibleBaseAffField;
        }
        set {
            this.nrCibleBaseAffField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short fAffIndice {
        get {
            return this.fAffIndiceField;
        }
        set {
            this.fAffIndiceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocEtudeOptionOptionTarif {
    
    private short pTarifFacialField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short PTarifFacial {
        get {
            return this.pTarifFacialField;
        }
        set {
            this.pTarifFacialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocEtudeOptionOptionCalcul {
    
    private short fMoyenneGRPField;
    
    private short fPenetrationField;
    
    private short valueMoyenneGRPField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short fMoyenneGRP {
        get {
            return this.fMoyenneGRPField;
        }
        set {
            this.fMoyenneGRPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short fPenetration {
        get {
            return this.fPenetrationField;
        }
        set {
            this.fPenetrationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short ValueMoyenneGRP {
        get {
            return this.valueMoyenneGRPField;
        }
        set {
            this.valueMoyenneGRPField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocEtudeOptionOptionEdition {
    
    private short fLigneGriseeField;
    
    private short fPleinEcranField;
    
    private short fCoeffMemoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short fLigneGrisee {
        get {
            return this.fLigneGriseeField;
        }
        set {
            this.fLigneGriseeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short fPleinEcran {
        get {
            return this.fPleinEcranField;
        }
        set {
            this.fPleinEcranField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short fCoeffMemo {
        get {
            return this.fCoeffMemoField;
        }
        set {
            this.fCoeffMemoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocCampagne {
    
    private StudyRoot_CartoucheBlocCampagneRefCampagne refCampagneField;
    
    private StudyRoot_CartoucheBlocCampagneRefOrgCampagne refOrgCampagneField;
    
    private object infoCampagneField;
    
    private object blocCampagneCentraleField;
    
    private object blocCampagneRegieField;
    
    private object blocCampagneStationField;
    
    private object blocOffreProduitField;
    
    private StudyRoot_CartoucheBlocCampagneFrontiere frontiereField;
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocCampagneRefCampagne RefCampagne {
        get {
            return this.refCampagneField;
        }
        set {
            this.refCampagneField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocCampagneRefOrgCampagne RefOrgCampagne {
        get {
            return this.refOrgCampagneField;
        }
        set {
            this.refOrgCampagneField = value;
        }
    }
    
    /// <remarks/>
    public object InfoCampagne {
        get {
            return this.infoCampagneField;
        }
        set {
            this.infoCampagneField = value;
        }
    }
    
    /// <remarks/>
    public object BlocCampagneCentrale {
        get {
            return this.blocCampagneCentraleField;
        }
        set {
            this.blocCampagneCentraleField = value;
        }
    }
    
    /// <remarks/>
    public object BlocCampagneRegie {
        get {
            return this.blocCampagneRegieField;
        }
        set {
            this.blocCampagneRegieField = value;
        }
    }
    
    /// <remarks/>
    public object BlocCampagneStation {
        get {
            return this.blocCampagneStationField;
        }
        set {
            this.blocCampagneStationField = value;
        }
    }
    
    /// <remarks/>
    public object BlocOffreProduit {
        get {
            return this.blocOffreProduitField;
        }
        set {
            this.blocOffreProduitField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_CartoucheBlocCampagneFrontiere Frontiere {
        get {
            return this.frontiereField;
        }
        set {
            this.frontiereField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocCampagneRefCampagne {
    
    private string libelleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Libelle {
        get {
            return this.libelleField;
        }
        set {
            this.libelleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocCampagneRefOrgCampagne {
    
    private string libelleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Libelle {
        get {
            return this.libelleField;
        }
        set {
            this.libelleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocCampagneFrontiere {
    
    private short frontiereDebutField;
    
    private short frontiereFinField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short FrontiereDebut {
        get {
            return this.frontiereDebutField;
        }
        set {
            this.frontiereDebutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short FrontiereFin {
        get {
            return this.frontiereFinField;
        }
        set {
            this.frontiereFinField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocTarification {
    
    private object blocPrixBiemField;
    
    private short baseFormatField;
    
    /// <remarks/>
    public object blocPrixBiem {
        get {
            return this.blocPrixBiemField;
        }
        set {
            this.blocPrixBiemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short BaseFormat {
        get {
            return this.baseFormatField;
        }
        set {
            this.baseFormatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocTitrePerso {
    
    private short lgTitPersonaliseField;
    
    private string titPersonaliseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short LgTitPersonalise {
        get {
            return this.lgTitPersonaliseField;
        }
        set {
            this.lgTitPersonaliseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TitPersonalise {
        get {
            return this.titPersonaliseField;
        }
        set {
            this.titPersonaliseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_CartoucheBlocSpecifYacast {
    
    private short nivNomenTarField;
    
    private short idNomenTarField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NivNomenTar {
        get {
            return this.nivNomenTarField;
        }
        set {
            this.nivNomenTarField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short IdNomenTar {
        get {
            return this.idNomenTarField;
        }
        set {
            this.idNomenTarField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_Plans {
    
    private StudyRoot_PlansPlan planField;
    
    /// <remarks/>
    public StudyRoot_PlansPlan Plan {
        get {
            return this.planField;
        }
        set {
            this.planField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlan {
    
    private StudyRoot_PlansPlanFenetre fenetreField;
    
    private StudyRoot_PlansPlanData dataField;
    
    private object selectionsField;
    
    private object parametresField;
    
    private long nrEtudeField;
    
    private short nrPlanField;
    
    private short versionField;
    
    private string nomField;
    
    private short refPlanField;
    
    private short occupeField;
    
    private short noSasField;
    
    private ushort dateDebutField;
    
    private ushort dateFinField;
    
    private short numCibleField;
    
    private string nomCibleField;
    
    private short numVagueField;
    
    private string nomVagueField;
    
    private uint dateHeureMemoField;
    
    private short nbSemainePAField;
    
    private ushort dateFinPAField;
    
    private ushort dateDebutPAField;
    
    /// <remarks/>
    public StudyRoot_PlansPlanFenetre Fenetre {
        get {
            return this.fenetreField;
        }
        set {
            this.fenetreField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_PlansPlanData Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    public object Selections {
        get {
            return this.selectionsField;
        }
        set {
            this.selectionsField = value;
        }
    }
    
    /// <remarks/>
    public object Parametres {
        get {
            return this.parametresField;
        }
        set {
            this.parametresField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long NrEtude {
        get {
            return this.nrEtudeField;
        }
        set {
            this.nrEtudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NrPlan {
        get {
            return this.nrPlanField;
        }
        set {
            this.nrPlanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nom {
        get {
            return this.nomField;
        }
        set {
            this.nomField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short RefPlan {
        get {
            return this.refPlanField;
        }
        set {
            this.refPlanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Occupe {
        get {
            return this.occupeField;
        }
        set {
            this.occupeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NoSas {
        get {
            return this.noSasField;
        }
        set {
            this.noSasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort DateDebut {
        get {
            return this.dateDebutField;
        }
        set {
            this.dateDebutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort DateFin {
        get {
            return this.dateFinField;
        }
        set {
            this.dateFinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NumCible {
        get {
            return this.numCibleField;
        }
        set {
            this.numCibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NomCible {
        get {
            return this.nomCibleField;
        }
        set {
            this.nomCibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NumVague {
        get {
            return this.numVagueField;
        }
        set {
            this.numVagueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NomVague {
        get {
            return this.nomVagueField;
        }
        set {
            this.nomVagueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint DateHeureMemo {
        get {
            return this.dateHeureMemoField;
        }
        set {
            this.dateHeureMemoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NbSemainePA {
        get {
            return this.nbSemainePAField;
        }
        set {
            this.nbSemainePAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort DateFinPA {
        get {
            return this.dateFinPAField;
        }
        set {
            this.dateFinPAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort DateDebutPA {
        get {
            return this.dateDebutPAField;
        }
        set {
            this.dateDebutPAField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanFenetre {
    
    private StudyRoot_PlansPlanFenetreBlocFenetres blocFenetresField;
    
    /// <remarks/>
    public StudyRoot_PlansPlanFenetreBlocFenetres blocFenetres {
        get {
            return this.blocFenetresField;
        }
        set {
            this.blocFenetresField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanFenetreBlocFenetres {
    
    private StudyRoot_PlansPlanFenetreBlocFenetresFenPlan fenPlanField;
    
    private short iconicField;
    
    private ushort leftField;
    
    private ushort rightField;
    
    private ushort topField;
    
    private ushort bottomField;
    
    /// <remarks/>
    public StudyRoot_PlansPlanFenetreBlocFenetresFenPlan FenPlan {
        get {
            return this.fenPlanField;
        }
        set {
            this.fenPlanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Iconic {
        get {
            return this.iconicField;
        }
        set {
            this.iconicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Left {
        get {
            return this.leftField;
        }
        set {
            this.leftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Right {
        get {
            return this.rightField;
        }
        set {
            this.rightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Top {
        get {
            return this.topField;
        }
        set {
            this.topField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Bottom {
        get {
            return this.bottomField;
        }
        set {
            this.bottomField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanFenetreBlocFenetresFenPlan {
    
    private StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocStrates blocStratesField;
    
    private StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocFormats blocFormatsField;
    
    private StudyRoot_PlansPlanFenetreBlocFenetresFenPlanPlgHor[] blocPlgHorairesField;
    
    private StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocRegions blocRegionsField;
    
    private StudyRoot_PlansPlanFenetreBlocFenetresFenPlanSemAct[] blocSemActivesField;
    
    private short iconicField;
    
    private ushort leftField;
    
    private ushort rightField;
    
    private ushort topField;
    
    private ushort bottomField;
    
    private short noGrilleField;
    
    private short dateDebutField;
    
    private short dateFinField;
    
    private short numCibleField;
    
    private string nomCibleField;
    
    private short nrVagueField;
    
    /// <remarks/>
    public StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocStrates blocStrates {
        get {
            return this.blocStratesField;
        }
        set {
            this.blocStratesField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocFormats blocFormats {
        get {
            return this.blocFormatsField;
        }
        set {
            this.blocFormatsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("PlgHor", IsNullable=false)]
    public StudyRoot_PlansPlanFenetreBlocFenetresFenPlanPlgHor[] blocPlgHoraires {
        get {
            return this.blocPlgHorairesField;
        }
        set {
            this.blocPlgHorairesField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocRegions blocRegions {
        get {
            return this.blocRegionsField;
        }
        set {
            this.blocRegionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SemAct", IsNullable=false)]
    public StudyRoot_PlansPlanFenetreBlocFenetresFenPlanSemAct[] blocSemActives {
        get {
            return this.blocSemActivesField;
        }
        set {
            this.blocSemActivesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Iconic {
        get {
            return this.iconicField;
        }
        set {
            this.iconicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Left {
        get {
            return this.leftField;
        }
        set {
            this.leftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Right {
        get {
            return this.rightField;
        }
        set {
            this.rightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Top {
        get {
            return this.topField;
        }
        set {
            this.topField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Bottom {
        get {
            return this.bottomField;
        }
        set {
            this.bottomField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NoGrille {
        get {
            return this.noGrilleField;
        }
        set {
            this.noGrilleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short DateDebut {
        get {
            return this.dateDebutField;
        }
        set {
            this.dateDebutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short DateFin {
        get {
            return this.dateFinField;
        }
        set {
            this.dateFinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NumCible {
        get {
            return this.numCibleField;
        }
        set {
            this.numCibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NomCible {
        get {
            return this.nomCibleField;
        }
        set {
            this.nomCibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NrVague {
        get {
            return this.nrVagueField;
        }
        set {
            this.nrVagueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocStrates {
    
    private StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocStratesStrate strateField;
    
    /// <remarks/>
    public StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocStratesStrate Strate {
        get {
            return this.strateField;
        }
        set {
            this.strateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocStratesStrate {
    
    private short nrStrateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NrStrate {
        get {
            return this.nrStrateField;
        }
        set {
            this.nrStrateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocFormats {
    
    private StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocFormatsFormat formatField;
    
    /// <remarks/>
    public StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocFormatsFormat Format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocFormatsFormat {
    
    private short nrFormatField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NrFormat {
        get {
            return this.nrFormatField;
        }
        set {
            this.nrFormatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanFenetreBlocFenetresFenPlanPlgHor {
    
    private short validField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Valid {
        get {
            return this.validField;
        }
        set {
            this.validField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocRegions {
    
    private StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocRegionsRegion regionField;
    
    /// <remarks/>
    public StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocRegionsRegion Region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocRegionsRegion {
    
    private StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocRegionsRegionStation[] stationField;
    
    private short noRegField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Station")]
    public StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocRegionsRegionStation[] Station {
        get {
            return this.stationField;
        }
        set {
            this.stationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NoReg {
        get {
            return this.noRegField;
        }
        set {
            this.noRegField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanFenetreBlocFenetresFenPlanBlocRegionsRegionStation {
    
    private short noStaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NoSta {
        get {
            return this.noStaField;
        }
        set {
            this.noStaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanFenetreBlocFenetresFenPlanSemAct {
    
    private short actifField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Actif {
        get {
            return this.actifField;
        }
        set {
            this.actifField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanData {
    
    private StudyRoot_PlansPlanDataBlocRegions blocRegionsField;
    
    private object blocTauxField;
    
    private StudyRoot_PlansPlanDataBlocStrates blocStratesField;
    
    private StudyRoot_PlansPlanDataBlocFormats blocFormatsField;
    
    private StudyRoot_PlansPlanDataBlocLegAttributs blocLegAttributsField;
    
    private StudyRoot_PlansPlanDataBlocSpots blocSpotsField;
    
    /// <remarks/>
    public StudyRoot_PlansPlanDataBlocRegions blocRegions {
        get {
            return this.blocRegionsField;
        }
        set {
            this.blocRegionsField = value;
        }
    }
    
    /// <remarks/>
    public object blocTaux {
        get {
            return this.blocTauxField;
        }
        set {
            this.blocTauxField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_PlansPlanDataBlocStrates blocStrates {
        get {
            return this.blocStratesField;
        }
        set {
            this.blocStratesField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_PlansPlanDataBlocFormats blocFormats {
        get {
            return this.blocFormatsField;
        }
        set {
            this.blocFormatsField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_PlansPlanDataBlocLegAttributs blocLegAttributs {
        get {
            return this.blocLegAttributsField;
        }
        set {
            this.blocLegAttributsField = value;
        }
    }
    
    /// <remarks/>
    public StudyRoot_PlansPlanDataBlocSpots blocSpots {
        get {
            return this.blocSpotsField;
        }
        set {
            this.blocSpotsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanDataBlocRegions {
    
    private StudyRoot_PlansPlanDataBlocRegionsRegion regionField;
    
    private short curRegionField;
    
    private short curStationField;
    
    private short curNiveauField;
    
    /// <remarks/>
    public StudyRoot_PlansPlanDataBlocRegionsRegion Region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short CurRegion {
        get {
            return this.curRegionField;
        }
        set {
            this.curRegionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short CurStation {
        get {
            return this.curStationField;
        }
        set {
            this.curStationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short CurNiveau {
        get {
            return this.curNiveauField;
        }
        set {
            this.curNiveauField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanDataBlocRegionsRegion {
    
    private StudyRoot_PlansPlanDataBlocRegionsRegionStation[] stationField;
    
    private short noField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Station")]
    public StudyRoot_PlansPlanDataBlocRegionsRegionStation[] Station {
        get {
            return this.stationField;
        }
        set {
            this.stationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short No {
        get {
            return this.noField;
        }
        set {
            this.noField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanDataBlocRegionsRegionStation {
    
    private short staField;
    
    private short lockField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Sta {
        get {
            return this.staField;
        }
        set {
            this.staField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Lock {
        get {
            return this.lockField;
        }
        set {
            this.lockField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanDataBlocStrates {
    
    private StudyRoot_PlansPlanDataBlocStratesStrate strateField;
    
    private short curStrateField;
    
    /// <remarks/>
    public StudyRoot_PlansPlanDataBlocStratesStrate Strate {
        get {
            return this.strateField;
        }
        set {
            this.strateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short CurStrate {
        get {
            return this.curStrateField;
        }
        set {
            this.curStrateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanDataBlocStratesStrate {
    
    private short noField;
    
    private short codeField;
    
    private short modeField;
    
    private string nomField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short No {
        get {
            return this.noField;
        }
        set {
            this.noField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nom {
        get {
            return this.nomField;
        }
        set {
            this.nomField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanDataBlocFormats {
    
    private StudyRoot_PlansPlanDataBlocFormatsFormat[] formatField;
    
    private short curFormatField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Format")]
    public StudyRoot_PlansPlanDataBlocFormatsFormat[] Format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short CurFormat {
        get {
            return this.curFormatField;
        }
        set {
            this.curFormatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanDataBlocFormatsFormat {
    
    private short noField;
    
    private short modeField;
    
    private short nomField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short No {
        get {
            return this.noField;
        }
        set {
            this.noField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Nom {
        get {
            return this.nomField;
        }
        set {
            this.nomField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanDataBlocLegAttributs {
    
    private StudyRoot_PlansPlanDataBlocLegAttributsLegAttrib legAttribField;
    
    /// <remarks/>
    public StudyRoot_PlansPlanDataBlocLegAttributsLegAttrib LegAttrib {
        get {
            return this.legAttribField;
        }
        set {
            this.legAttribField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanDataBlocLegAttributsLegAttrib {
    
    private short valSpField;
    
    private string legField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short ValSp {
        get {
            return this.valSpField;
        }
        set {
            this.valSpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Leg {
        get {
            return this.legField;
        }
        set {
            this.legField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanDataBlocSpots {
    
    private StudyRoot_PlansPlanDataBlocSpotsSP[] spotsPresentsField;
    
    private object spotsAbsentsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Sp", IsNullable=false)]
    public StudyRoot_PlansPlanDataBlocSpotsSP[] SpotsPresents {
        get {
            return this.spotsPresentsField;
        }
        set {
            this.spotsPresentsField = value;
        }
    }
    
    /// <remarks/>
    public object SpotsAbsents {
        get {
            return this.spotsAbsentsField;
        }
        set {
            this.spotsAbsentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class StudyRoot_PlansPlanDataBlocSpotsSP {
    
    private short regField;
    
    private short staField;
    
    private int numField;
    
    private ushort horField;
    
    private short jrField;
    
    private short noStrField;
    
    private short noForField;
    
    private short valAttField;
    
    private string attrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Reg {
        get {
            return this.regField;
        }
        set {
            this.regField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Sta {
        get {
            return this.staField;
        }
        set {
            this.staField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Num {
        get {
            return this.numField;
        }
        set {
            this.numField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Hor {
        get {
            return this.horField;
        }
        set {
            this.horField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short Jr {
        get {
            return this.jrField;
        }
        set {
            this.jrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NoStr {
        get {
            return this.noStrField;
        }
        set {
            this.noStrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short NoFor {
        get {
            return this.noForField;
        }
        set {
            this.noForField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short ValAtt {
        get {
            return this.valAttField;
        }
        set {
            this.valAttField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Attr {
        get {
            return this.attrField;
        }
        set {
            this.attrField = value;
        }
    }
}
