//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CreusetExt.rc
//
#define IDS_CR_CONTRIBN_C               1
#define IDS_CR_CONTRIBN_CTCOUV          2
#define IDS_CR_CONTRIBN_GRP             3
#define IDC_CR_TARIFBASE                4
#define IDS_CR_CONTRIBN_PGRP            5
#define IDS_CR_CONTRIBN_BUD             6
#define IDS_CR_CONTRIBN_PBUD            7
#define IDS_STRING7                     8
#define IDS_CR_MAX_TARIF                9
#define IDS_CR_CONTRIB                  10
#define IDS_CR_GRANDEUR                 11
#define IDB_CR_SPLASH                   1000
#define IDD_CR_ATPETUDE                 1001
#define IDD_CR_ATPLIBELLE               1002
#define IDD_CR_ATPPERIODE               1003
#define IDD_CR_ATPPERIODEACTION         1004
#define IDD_CR_ATPPRODUIT               1005
#define IDD_CR_ATPVERSION               1006
#define IDD_CR_ATPZOOMPLAN              1007
#define IDD_CR_DLG_CONTRIBUTION         1008
#define IDD_CR_DLG_FILTREAUDIENCE1      1009
#define IDD_CR_DLG_VERSIONPLANMAITRE    1010
#define IDI_CR_LEDOFF                   1011
#define IDI_CR_LEDON                    1012
#define IDI_CR_LEDSEL                   1013
#define IDM_CR_AFFINITE_IND             1014
#define IDM_CR_AFFINITE_PRC             1015
#define IDM_CR_BASETARIFNEGO            1016
#define IDM_CR_BASETARIFPLAQ            1017
#define IDM_CR_BUDGET_BRUT              1018
#define IDM_CR_BUDGET_NET               1019
#define IDM_CR_CHARGER_VERSION_PLANREF  1020
#define IDM_CR_CHROMIE                  1021
#define IDM_CR_COMPL                    1022
#define IDM_CR_CONTEXTLECTURE           1023
#define IDM_CR_CREER_VERSION_PLANREF    1024
#define IDM_CR_DEFVAGUETEMOIN           1025
#define IDM_CR_ETUDE_ARCHIVER           1026
#define IDM_CR_ETUDE_ENREGISTRER        1027
#define IDM_CR_ETUDE_ENREGISTRER_SOUS   1028
#define IDM_CR_ETUDE_FERMER             1029
#define IDM_CR_ETUDE_NOUVELLE           1030
#define IDM_CR_ETUDE_OUVRIR             1031
#define IDM_CR_ETUDE_RECUPERER          1032
#define IDM_CR_ETUDE_RENOMMER           1033
#define IDM_CR_ETUDE_SUPPRIMER          1034
#define IDM_CR_EXPORT_ETUDE             1035
#define IDM_CR_EXPORT_VAGUE             1036
#define IDM_CR_HYPOTH_CREATE            1037
#define IDM_CR_HYPOTH_VALID             1038
#define IDM_CR_HYPOTH_VERSION           1039
#define IDM_CR_IMPORT_ETUDE             1040
#define IDM_CR_IMPORTVAGUETEMOIN        1041
#define IDM_CR_INSERTSTATUT             1042
#define IDM_CR_LIGNE1                   1043
#define IDM_CR_MODEL                    1044
#define IDM_CR_MODELETAL                1045
#define IDM_CR_PROBABILIT               1046
#define IDM_CR_NAMEHYPOTH               1047
#define IDM_CR_NIVEXPOSITION            1048
#define IDM_CR_OFFRE_CIBLES             1049
#define IDM_CR_OFFRE_FORMATS            1050
#define IDM_CR_OFFRE_SOURCES            1051
#define IDM_CR_OFFRE_SUPPORTS           1052
#define IDM_CR_OPT_BASECALCGRPC_NAT     1053
#define IDM_CR_OPT_BASECALCGRPC_REG     1054
#define IDM_CR_OPT_CALCULXGRP           1055
#define IDM_CR_OPT_COURBE_MEMODEMEMO    1056
#define IDM_CR_OPT_ETALONNAGEPROBA      1057
#define IDM_CR_OPT_LDPQUOTIDIEN         1058
#define IDM_CR_OPT_LNMMAGAZINE          1059
#define IDM_CR_OPT_REPRISEENMAIN        1060
#define IDM_CR_PALETTE_1                1061
#define IDM_CR_PALETTE_2                1062
#define IDM_CR_PALETTE_3                1063
#define IDM_CR_PALETTE_4                1064
#define IDM_CR_PALETTE_5                1065
#define IDM_CR_PALETTE_6                1066
#define IDM_CR_PALETTE_7                1067
#define IDM_CR_PALETTE_8                1068
#define IDM_CR_PALETTE_9                1069
#define IDM_CR_PALETTE_10               1070
#define IDM_CR_PALETTE_11               1071
#define IDM_CR_PARAM_TRONCINSERTDEB     1072
#define IDM_CR_PARAM_TRONCINSERTFIN     1073
#define IDM_CR_PERIMETRE_PERIODE        1074
#define IDM_CR_PERIODE_ETUDE            1075
#define IDM_CR_SUPPINS_HYPACT           1076
#define IDM_CR_SUPPINS_TOUTESHYPS       1077
#define IDM_CR_TRANSFERT_PLANREF        1078
#define IDM_CR_TRANSFERT_VERSION        1079
#define IDR_CR_ATPCREUSET               1080
#define IDR_CR_ATPFRAME                 1081
#define IDS_CD_STR_VALIDHYPO            1082
#define IDS_CR_ARCHETUDE                1083
#define IDS_CR_AUCUN                    1084
#define IDS_CR_AUDIENCE                 1085
#define IDS_CR_BUDGET                   1086
#define IDS_CR_CONTACTS                 1087
#define IDS_CR_CONTACTSA                1088
#define IDS_CR_CONTACTSPLUS_ABR         1089
#define IDS_CR_COUVERTURE               1090
#define IDS_CR_COUVMEM                  1091
#define IDS_CR_CT1000C                  1092
#define IDS_CR_CT1000I                  1093
#define IDS_CR_CTGRP                    1094
#define IDS_CR_DISTRIB1                 1095
#define IDS_CR_DISTRIBCUMUL             1096
#define IDS_CR_DISTRIBN                 1097
#define IDS_CR_DISTRIBNETTE             1098
#define IDS_CR_DISTRIBNETTE1            1099
#define IDS_CR_DISTRIBNETTEN            1100
#define IDS_CR_DISTRIBNETTEP            1101
#define IDS_CR_DISTRIBNT                1102
#define IDS_CR_DISTRIBP                 1103
#define IDS_CR_ECHELLE                  1104
#define IDS_CR_GRP                      1105
#define IDS_CR_GRPACTIF                 1106
#define IDS_CR_GRPHCOUV                 1107
#define IDS_CR_GRPHGRP                  1108
#define IDS_CR_INDAFFINITE              1109
#define IDS_CR_LBLPLANMAITRE            1110
#define IDS_CR_LBLPLANMAITRE2           1111
#define IDS_CR_DISTRIBNETTEPABR         1112
#define IDS_CR_LBLRENHYPO               1113
#define IDS_CR_LDPLNM                   1114
#define IDS_CR_LOADETUDE                1115
#define IDS_CR_MEMODEMEMO               1116
#define IDS_CR_NBCTSDIS                 1117
#define IDS_CR_NBINDIVTOUCH             1118
#define IDS_CR_NBJOURSLECT              1119
#define IDS_CR_PATTLTEMOIN              1120
#define IDS_CR_PATTLTRAVAIL             1121
#define IDS_CR_PATTLVAGUE               1122
#define IDS_CR_PAWNDTEMOIN              1123
#define IDS_CR_PAWNDTRAVAIL             1124
#define IDS_CR_PAWNDVAGUE               1125
#define IDS_CR_PERF                     1126
#define IDS_CR_PERIOD                   1127
#define IDS_CR_PM                       1128
#define IDS_CR_PRCAFFINITE              1129
#define IDS_CR_RECUPETUDE               1130
#define IDS_CR_REPET                    1131
#define IDS_CR_REPRISES                 1132
#define IDS_CR_RESULTATS                1133
#define IDS_CR_RESULTG                  1134
#define IDS_CR_STR_CPL                  1135
#define IDS_CR_STR_ERR_CIBLE            1136
#define IDS_CR_STR_ERR_IAFF             1137
#define IDS_CR_STR_ERR_SUPPORT          1138
#define IDS_CR_STR_ERR_TERRA            1139
#define IDS_CR_STR_ERR_TERRC            1140
#define IDS_CR_STR_LOT                  1141
#define IDS_CR_STR_TITRE                1142
#define IDS_CR_STR_TRF1                 1143
#define IDS_CR_STR_TRF2                 1144
#define IDS_CR_STR_TRF3                 1145
#define IDS_CR_SUPPORTS                 1146
#define IDS_CR_SUPPRETUDE               1147
#define IDS_CR_TARIF                    1148
#define IDS_CR_TOUS                     1149
#define IDS_CR_TTLCREUSETHYPO           1150
#define IDS_CR_TTLCREUSETHYPOD          1151
#define IDS_CR_TTLDLGSAVETUDE           1152
#define IDS_CR_VENTIL                   1153
#define IDS_CR_TOTINS                   1154
#define IDS_CR_FILTER                   1155
#define IDS_CR_NONAME                   1156
#define IDD_CR_RESULTBAR                1157
#define IDS_CR_ERRSRC                   1158
#define IDD_CR_RESULTPLAN               1159
#define IDS_CR_ERRTER                   1160
#define IDD_CR_PANELBAS                 1161
#define IDS_CR_ERRITEM                  1162
#define IDS_CR_ERRAFFINITE              1163
#define IDI_CR_ECHELLE                  1164
#define IDS_CR_ERRSUPPORT               1165
#define IDI_CR_RESULT                   1166
#define IDS_CR_MAJTARIFS                1167
#define IDS_CR_PLATEAU                  1168
#define IDD_CR_DLGCTX                   1169
#define IDS_CR_PLAN                     1170
#define IDS_CR_EFFACER                  1171
#define IDB_CR_MOT3                     1172
#define IDS_CR_PLUS                     1173
#define IDB_CR_MOT1                     1174
#define IDS_CR_MOINS                    1175
#define IDB_CR_MOT2                     1176
#define IDS_CR_T                        1177
#define IDI_CR_FLECHE                   1178
#define IDS_CR_EFFHYPOACT               1179
#define IDI_CR_CRB                      1180
#define IDS_CR_EFFHYPOTT                1181
#define IDI_CR_HISTO                    1182
#define IDS_CR_TABLEUR                  1183
#define IDI_CR_FSUPP                    1184
#define IDS_CR_CALEND                   1185
#define IDI_CR_ZOOM                     1186
#define IDS_CR_PLAN_E                   1187
#define IDI_CR_FHAUT                    1188
#define IDS_CR_PLAN_T                   1189
#define IDI_CR_FBAS                     1190
#define IDS_CR_PLAN_M                   1191
#define IDB_CR_LEDVERT                  1192
#define IDS_CR_CONFIRMSAV               1193
#define IDB_CR_LEDNEUTRE                1194
#define IDS_CR_MOTABAQUE                1195
#define IDB_CR_LEDORANGE                1196
#define IDS_CR_MOTABAQUEETAL            1197
#define IDB_CR_LEDROUGE                 1198
#define IDS_CR_MOTPROBA                 1199
#define IDS_CR_APPREPET                 1200
#define IDD_CR_CRBREPONSE               1201
#define IDS_CR_APPCOUV                  1202
#define IDS_CR_APPCOUVM                 1203
#define IDD_CR_NVLCRB                   1204
#define IDS_CR_PARTBUDGET               1205
#define IDD_CR_PUPITRE                  1206
#define IDC_CR_A1                       1207
#define IDS_CR_APPORTGRP                1208
#define IDC_CR_A2                       1209
#define IDS_CR_PARTGRP                  1210
#define IDC_CR_A3                       1211
#define IDS_CR_DELTACOUV                1212
#define IDC_CR_BK                       1213
#define IDS_CR_DELTAGRP                 1214
#define IDD_CR_VENTIL                   1215
#define IDC_CR_BTN_FLORILEGES           1216
#define IDS_CR_DELTACTGRP               1217
#define IDI_CR_QUESTION                 1218
#define IDC_CR_BTN_LISTALL              1219
#define IDS_CR_CONTRIBBUDGET            1220
#define IDI_CR_THEME                    1221
#define IDC_CR_BTN_RAZSEARCH            1222
#define IDS_CR_CONTRIBGRP               1223
#define IDC_CR_A6                       1224
#define IDR_CR_MENUOFFRE                1225
#define IDC_CR_BTN_RECHERCHE            1226
#define IDS_CR_CONTRIBCOUV              1227
#define IDR_CR_TOOLBAR                  1228
#define IDC_CR_BTNR1_ITEMS              1229
#define IDS_CR_DELTAREPRISE             1230
#define IDC_CR_BTNR1_LOTS               1231
#define IDS_CR_PLMOINSINSER             1232
#define IDR_CR_GRILLE                   1233
#define IDC_CR_BTNR1_SOURCE             1234
#define IDS_CR_DATE                     1235
#define IDI_CR_LOCK                     1236
#define IDR_CR_ATPCREUSET1              1237
#define IDR_CR_ATPQUICKPLAN             1238
#define IDC_CR_BTNR1_UNIQUE             1239
#define IDS_CR_FORMAT                   1240
#define IDI_CR_STATE2                   1241
#define IDC_CR_BTNR2_MULTIPLE           1242
#define IDS_CR_FORMATS                  1243
#define IDI_CR_LEDNEUTRE                1244
#define IDC_CR_BTNR2_PALETTES           1245
#define IDS_CR_SUPPINSERT               1246
#define IDC_CR_BTNR2_SUPPORT            1247
#define IDS_CR_NUMERO                   1248
#define IDC_CR_BTNR2_TITRES             1249
#define IDS_CR_XGRPJOUR                 1250
#define IDC_CR_BTNR3_AFFINITE           1251
#define IDS_CR_GRPJOUR                  1252
#define IDC_CR_BTNR3_CIBLE              1253
#define IDS_CR_GRPCUMUL                 1254
#define IDC_CR_BTNR3_COUPLAGES          1255
#define IDS_CR_XGRPCUMUL                1256
#define IDC_CR_BTNT                     1257
#define IDS_CR_DISTRIBPABR              1258
#define IDC_CR_C3                       1259
#define IDS_CR_DISTRIBNABR              1260
#define IDC_CR_COMBO_ANNONCEUR          1261
#define IDS_CR_DISTRIB2                 1262
#define IDS_CR_DISTRIB1ABR              1263
#define IDC_CR_COMBO_GROUPE             1264
#define IDS_CR_EXT                      1265
#define IDC_CR_COMBO_PRODUIT            1266
#define IDS_CR_ETUDENONVALID            1267
#define IDC_CR_COMBO_SOURCE             1268
#define IDS_CR_ETUDENONINIT             1269
#define IDC_CR_COMBO_SOURCEA            1270
#define IDS_CR_AUDIENCE_ABR             1271
#define IDC_CR_COMBO_SOURCEC            1272
#define IDS_CR_CONTACTS_ABR             1273
#define IDC_CR_DATED                    1274
#define IDS_CR_CONTACTSPLUS             1275
#define IDC_CR_DATED2                   1276
#define IDS_CR_CT1000CONTACTS           1277
#define IDC_CR_DATEF                    1278
#define IDS_CR_CT1000INDIVIDUS          1279
#define IDC_CR_EDITSEARCH               1280
#define IDS_CR_DELTAGRPPLUS             1281
#define IDC_CR_FORMAT                   1282
#define IDS_CR_APPORTGRPPLUS            1283
#define IDC_CR_FR_ANNONCEUR             1284
#define IDS_CR_PARTGRPPLUS              1285
#define IDC_CR_HS                       1286
#define IDS_CR_CONTRIBGRPPLUS           1287
#define IDC_CR_LIBELLE                  1288
#define IDS_CR_APPORT                   1289
#define IDC_CR_LIST_BAS                 1290
#define IDS_CR_DEFICIT                  1291
#define IDC_CR_LIST_HAUT                1292
#define IDS_CR_COURBEBINOMIALE          1293
#define IDC_CR_LIST_PLAN                1294
#define IDS_CR_PASCOURBE                1295
#define IDC_CR_LIST_POIDS               1296
#define IDS_CR_CONFSUPPCRB              1297
#define IDC_CR_LIST_SEGMENT             1298
#define IDS_CR_MODIFCRB                 1299
#define IDC_CR_LIST_SEGMENTA            1300
#define IDS_CR_NEWCRB                   1301
#define IDC_CR_LIST_SEGMENTC            1302
#define IDS_CR_NOINSPM                  1303
#define IDC_CR_LIST_TERRAIN             1304
#define IDS_CR_ERR_INITETU              1305
#define IDC_CR_LIST_TERRAINA            1306
#define IDS_CR_SUPPR_SUPPORTECH         1307
#define IDC_CR_LIST_TERRAINC            1308
#define IDS_CR_COEFALPHA                1309
#define IDC_CR_LISTPLAN                 1310
#define IDS_CR_PERIODICITE              1311
#define IDC_CR_OFFRE                    1312
#define IDS_CR_DISTRIBNETTENABR         1313
#define IDC_CR_OK                       1314
#define IDS_CR_REFAFFINITE              1315
#define IDC_CR_OPT                      1316
#define IDS_CR_CTCOUV                   1317
#define IDC_CR_PERIODE                  1318
#define IDS_CR_CTCOUVERTURE             1319
#define IDC_CR_PRODUIT                  1320
#define IDS_CR_HYPOTHESE                1321
#define IDC_CR_PRODUIT2                 1322
#define IDS_CR_DISTRIBNTABR             1323
#define IDC_CR_SELECTION                1324
#define IDS_CR_REPETPLUS                1325
#define IDC_CR_SPINJ                    1326
#define IDS_CR_DELTAREPRISEPLUS         1327
#define IDC_CR_SPINS                    1328
#define IDS_CR_APPREPETPLUS             1329
#define IDC_CR_STATIC_BOX               1330
#define IDS_CR_BUDGETACTIF              1331
#define IDC_CR_STATIC_BTN               1332
#define IDS_CR_INDEXTHEM                1333
#define IDC_CR_STATIC_CIBLES            1334
#define IDS_CR_ITEMS                    1335
#define IDC_CR_STATIC_FILLE             1336
#define IDS_CR_PALETTES                 1337
#define IDC_CR_STATIC_FILTRE            1338
#define IDS_CR_INDGRP                   1339
#define IDC_CR_STATIC_FORMAT            1340
#define IDS_CR_INDGRPACTIF              1341
#define IDC_CR_STATIC_SOURCE            1342
#define IDS_CR_INDCOUV                  1343
#define IDC_CR_STATIC_TITRE             1344
#define IDS_CR_FILTER_ATP               1345
#define IDS_CR_FILTER_QP                1346
#define IDC_CR_STATIC_TTL               1347
#define IDS_CR_REPRISESPLUS             1348
#define IDR_MENU1                       1349
#define IDR_CR_MENUCONTRIB              1350
#define IDC_CR_STATIC_TTLCIBLES         1351
#define IDC_CR_STATIC_TTL2              1352
#define IDS_CR_EXT_QP                   1353
#define IDR_CR_VENTIL                   1354
#define IDC_CR_STATIC_TTLFILTRE         1355
#define IDC_CR_STATIC_TTL3              1356
#define IDD_CR_DLG_TARIFMANUEL          1357
#define IDS_CR_MAX_INS_EDIT             1358
#define IDC_CR_STATIC_TTLFORMAT         1359
#define IDR_CR_MENUGRAPH                1360
#define IDS_CR_GRAPH                    1361
#define IDC_CR_STATIC_TTLPOIDS          1362
#define IDS_CR_COUVCUM                  1363
#define IDC_CR_STATIC_TTLSEGMENT        1364
#define IDS_CR_APPCOUVJOUR              1365
#define IDC_CR_STATIC_TTLSEGMENTA       1366
#define IDS_CR_CALCUL_APPORT            1367
#define IDC_CR_STATIC_TTLSEGMENTC       1368
#define IDC_CR_STATIC_TTLSOURCE         1369
#define IDC_CR_STATIC_TTLSOURCEA        1370
#define IDC_CR_STATIC_TTLSOURCEC        1371
#define IDC_CR_STATIC_TTLTERRAIN        1372
#define IDC_CR_STATIC_TTLTERRAINA       1373
#define IDC_CR_STATIC_TTLTERRAINC       1374
#define IDC_CR_STATIC_TTLTITRE          1375
#define IDC_CR_TEXTJ                    1376
#define IDC_CR_TEXTS                    1377
#define IDC_CR_TITLEANNONCEUR           1378
#define IDC_CR_TITLEGROUPE              1379
#define IDC_CR_TITLEPRODUIT             1380
#define IDC_CR_TREE_BAS                 1381
#define IDC_CR_TTL                      1382
#define IDC_CR_TTL2                     1383
#define IDC_CR_TXT                      1384
#define IDC_CR_TTL3                     1385
#define IDC_CR_TXT2                     1386
#define IDC_CR_TTL4                     1387
#define IDC_CR_TXT3                     1388
#define IDC_CR_TXT4                     1389
#define IDC_CR_TXT5                     1390
#define IDC_CR_VS                       1391
#define IDC_CR_X                        1392
#define IDC_CR_B1RG                     1393
#define IDC_CR_B2DISTRIN                1394
#define IDC_CR_RESPLAN                  1395
#define IDC_CR_B3DISTRIC                1396
#define IDC_CR_B4VTL                    1397
#define IDC_CR_BTNGRPJ                  1398
#define IDC_CR_B5MEMDEMEMO              1399
#define IDC_CR_RES                      1400
#define IDC_CR_B6GRAPH                  1401
#define IDC_CR_GRPH                     1402
#define IDC_CR_ECHRES                   1403
#define IDC_CR_ECHELLE                  1404
#define IDC_CR_BTNZOOM                  1405
#define IDC_CR_IMPORT                   1406
#define IDC_CR_MIRE                     1407
#define IDC_CR_BTNCTX                   1408
#define IDC_CR_BTNSWITCH                1409
#define IDC_CR_CH1MOT                   1410
#define IDC_CR_BTNFSUPP                 1411
#define IDC_CR_CH2MOT                   1412
#define IDC_CR_BTNOPTMOT                1413
#define IDC_CR_CH3MOT                   1414
#define IDC_CR_RESULTATS                1415
#define IDC_CR_BTNREPRISE               1416
#define IDC_CR_LDP                      1417
#define IDC_CR_LNM                      1418
#define IDC_CR_BTNMOINS                 1419
#define IDC_CR_BTNPLUS                  1420
#define IDC_CR_BTNMOINS2                1421
#define IDC_CR_BTNAUTO                  1422
#define IDC_CR_COMBOCRB                 1423
#define IDC_CR_BTNCREER                 1424
#define IDC_CR_BTNMODIF                 1425
#define IDC_CR_BTNSUPPR                 1426
#define IDC_CR_BETA                     1427
#define IDC_CR_STATICGRID               1428
#define IDC_CR_LBL                      1429
#define IDC_CR_PROGRESS                 1430
#define IDC_CR_BTN1QUESTION             1431
#define IDC_CR_BTN2ITEM                 1432
#define IDC_CR_BTN3PALETTE              1433
#define IDC_CR_LIST                     1434
#define IDC_CR_TREE                     1435
#define IDC_CR_BTNEVAL                  1436
#define IDC_CR_LIST_TERRAINS            1437
#define IDC_CR_LIST_CIBLES              1438
#define IDC_CHECK1                      1439
#define IDC_CR_LIST_CIBLES2             1440
#define IDC_CR_LIST_REFAFF              1441
#define IDC_CHECK2                      1442
#define IDC_CHECK3                      1443
#define IDC_CHECK4                      1444
#define IDC_CHECK5                      1445
#define IDC_EDIT1                       1446
#define IDC_CR_EDIT_TARIF               1447
#define IDC_CR_CBX_FORMAT               1448
#define IDC_CR_SEPAR                    1449
#define IDC_CR_TXTSUPPORT               1450
#define IDM_CR_PALETTE_12               1451
#define IDC_LIST1                       1452
#define IDC_CR_TITRE_LIST1              1453
#define IDC_CR_BK_CIBLEPOND             1454
#define IDD_CR_DGL_CIBLEPOND            1455
#define IDC_CR_TITRE_COMPOS             1456
#define IDC_CR_MODIF_CIBLEPOND          1457
#define IDC_CR_CREER_CIBLEPOND          1458
#define IDC_CR_LST_ITEMS                1459
#define IDC_CR_LST_COMPOSANTS           1460
#define IDC_CR_GRID_PONDER              1461
#define IDC_CR_TITRE_CIBLEPOND          1462
#define IDC_CR_TITRE_PONDERATION        1463
#define IDC_CR_EDIT_CIBLEPOND           1464
#define IDC_CR_LST_CIBLEPOND            1465
#define IDC_CR_VALIDER                  1466
#define IDC_CR_TITRE_COMPLEMENT         1467
#define IDC_CR_PRCT_COMPL_REEL          1468
#define IDC_CR_PRCT_COMPL_POND          1469
#define IDC_CR_SUPPRIMER                1470
#define IDC_CR_FERMER                   1471
#define IDC_CR_LBL_SUPPORT              2218
#define IDC_CR_LBL_FORMAT               2219
#define IDC_CR_LBL_TARIF                2220
#define IDC_CR_BK_SAISIETARIF           2252
#define IDS_CR_APPORT_COUV              2253
#define IDM_CR_PALETTE_13               2254
#define IDM_CR_PALETTE_14               2255
#define IDM_CR_PALETTE_15               2256
#define IDM_CR_AFFOPTMOTEUR             32979
#define IDM_CR_REPRISES                 32982
#define IDM_CR_NOREPRISES               32983
#define IDM_CR_OPTIONS_LDPBIMESTR       32986
#define IDM_CR_SEUILSTAT                32988
#define IDM_CR_OFFRE_ITEMSDEVENTILATION 32989
#define IDM_CR_OFFRECREER               32997
#define IDM_CR_OFFREIMPORT              32998
#define IDM_CR_EXIT                     33003
#define IDM_CR_POPUPGRILLE_ITEM2        33010
#define IDM_CR_POPUPGRILLE_ITEM0        33012
#define IDM_CR_POPUPGRILLE_ITEM1        33013
#define IDM_CR_NBD_AUCUNEDECIMALE       33017
#define IDM_CR_NBD_1DECIMALE            33018
#define IDM_CR_NBD_2DECIMALE            33019
#define IDM_CR_CLIPBOARD_ECHELLE        33021
#define IDM_CR_CLIPBOARD_RESULTPLAN     33022
#define IDM_CR_CLIPBOARD_RESULTCALEND   33023
#define IDM_CR_CLIPBOARD_VENTIL         33024
#define IDM_CR_CLIPBOARD_TOUT           33025
#define IDM_CR_EXPORT_VENTIL            33029
#define IDM_CR_COMPUTEREALTIME          33033
#define IDM_CR_COMPUTEDIFF              33034
#define IDM_CR_PRINT_ECHELLE            33036
#define IDM_CR_PRINT_RESULTPLAN         33037
#define IDM_CR_PRINT_RESULTCALEND       33038
#define IDM_CR_PRINT_TOUT               33039
#define IDM_CR_EXPORT_ECHELLE           33040
#define IDM_CR_EXPORT_RESULTCALEND      33041
#define IDM_CR_EXPORT_RESULTPLAN        33042
#define IDM_CR_EXPORT_TOUT              33043
#define IDM_CR_COLTOTAL                 33045
#define IDM_CR_HYPO_COPIER              33050
#define IDM_CR_HYPO_COLLER              33051
#define IDM_CR_HYPO_ADD_1               33052
#define IDM_CR_HYPO_ADD_2               33053
#define ID_IMPRIMER_GRAPHE              33054
#define ID_GRAPHE_GRPJOUR               33055
#define IDM_CR_GRPHCLIPBOARD            33055
#define ID_GRAPHE_COUVJOUR              33056
#define ID_GRAPHE_GRPCUMUL              33057
#define ID_GRAPHE_APPORTC               33058
#define IDM_CR_CONTRIBCOUV              33061
#define IDM_CR_CONTRIBGRP               33062
#define IDM_CR_CONTRIBPGRP              33063
#define IDM_CR_CONTRIBBUDG              33064
#define IDM_CR_CONTRIBPBUDG             33065
#define ID_VENTIL_GRP                   33066
#define ID_VENTIL_COUV                  33068
#define ID_VENTIL_R                     33070
#define ID_VENTIL_ITEMSDEVENTILATION    33071
#define ID_VENTIL_INDCOUV               33072
#define ID_VENTIL_INDGRP                33073
#define IDM_CR_CONTRIBCTCOUV            33075
#define IDM_CR_AJOUT_1INS               33076
#define IDM_CR_AJOUT_2INS               33077
#define IDM_CR_OPT_FILTRE_AUDIENCE      33077
#define IDM_CR_AJOUT_3INS               33078
#define IDM_CR_AJOUT_4INS               33079
#define IDM_CR_OPT_COURBE_REPONSE       33079
#define IDM_CR_AJOUT_5INS               33080
#define ID_EXPORTERDANSUNFICHIER_GRAPHER 33080
#define IDM_CR_AJOUT_6INS               33081
#define ID_EXPORTERDANSUNFICHIER_TOUSLESGRAPHESR 33081
#define IDM_CR_AJOUT_7INS               33082
#define IDM_CR_AJOUT_8INS               33083
#define IDM_CR_AJOUT_9INS               33084
#define IDM_CR_AJOUT_10INS              33085
#define IDM_CR_AJOUT_11INS              33086
#define IDM_CR_GRAPH_GRPJOUR            33086
#define IDM_CR_AJOUT_12INS              33087
#define IDM_CR_GRAPH_GRPCUM             33087
#define IDM_CR_GRAPH_COUVCUM            33088
#define IDM_CR_GRAPH_APPORTCOUVCUM      33089
#define ID_TYPEDEGRAPHIQUE_TOTO         33090
#define IDM_CR_CREER_CIBLEPOND          33092
#define ID_Menu                         33096
#define IDM_CR_UTIL_CIBLEPOND           33098
#define ID_ETUDE_EXPORTERVERSEXCEL      33099
#define IDM_CR_EXCEL_ECHELLE            33100
#define IDM_CR_EXCEL_RESULTPLAN         33101
#define IDM_CR_EXCEL_RESULTCALEND       33102
#define IDM_CR_EXCEL_TOUT               33103
#define ID_OFFRE_NOUVELLEBOITE          33104
#define IDM_CR_OFFRE2CREER              33105
#define ID_ETUDE_IMPORTERUNPLATEAU      33106
#define ID_ETUDE_IMPORTERPLATEAU        33107
#define ID_CR_IMPORTERPLATEAU           33108
#define IDM_CR_IMPORT_PLATEAU           33109
#define ID_TOTO_CONTRIBUTIONSPARSUPPORTS 33110
#define ID_TOTO_CONTRIBUTIONSPARGRANDEURS 33111
#define IDM_CR_CONTRIB_MODE_SUPPORTS    33112
#define IDM_CR_CONTRIB_MODE_GRANDEURS   33113
#define ID_TOTO_CALCULER                33114
#define ID_VENTIL_NBCONTACTS            33115
#define ID_VENTIL_AUDIENCE000           33117

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        1270
#define _APS_NEXT_COMMAND_VALUE         33118
#define _APS_NEXT_CONTROL_VALUE         1371
#define _APS_NEXT_SYMED_VALUE           1393
#endif
#endif
