#include "StdAfx.h"
/// <summary>
/// Auto generated DlgItemsMessage class from C:\Work\AtelierPresse\Version 2.5.1\RepItemsExt\DlgItemsLocale.xls
/// </summary>

#include "DlgItemsMessage.h"

#if defined(BUILD_FOR_ATELIER_INTERNET)

const char* DlgItemsMessage::Languages[] = {
    "en", 
    "fr", 
    "it", 
    NULL
};

int DlgItemsMessage::CurrentLanguage = 0;
const char** DlgItemsMessage::MessageMap[] = {
    DlgItemsMessage::Message_en, 
    DlgItemsMessage::Message_fr, 
    DlgItemsMessage::Message_it, 
    NULL
};

const char* DlgItemsMessage::Message_en[] = {
    "Item set",
    "Respondents",
    "Overview and print the item definition",
    "Copy the item definition onto the clipboard",
    "Intersection between segments",
    "Union beween segments",
    "Select inter-segment operation",
    "Remove selected questions",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "And",
    "Or",
    "Nor",
    "Ex",
    "",
    "",
    "",
    "Everyone",
    "",
    "Current item definition",
    "",
    "Reach :",
    "In line",
    "In column",
    "In page",
    "Selected questions",
    "Or",
    "And",
    "Ex",
    "Nor",
    "Or",
    "Modality",
    "A",
    "",
    "And",
    "Or",
    "Or",
    "Or",
    "And",
    "Or",
    "Or",
    "And",
    "Ex",
    "Nor",
    "Or",
    "Questions",
    "",
    "",
    "",
    "A",
    "Validate",
    "Genesis",
    "Items",
    "Questions module",
    "Number of cases :",
    "Count :",
    "Elements",
    "Segm.",
    "0",
    "0.0 %",
    "0",
    "Wave",
    "All",
    "Dimension1",
    "Dimension2",
    "Dimension1xxx",
    "Individuals",
    "A",
    "Find",
    "All",
    "Theme index",
    "",
    "Clear",
    "Remove",
    "Lines",
    "Columns",
    "Pages",
    "@",
    "@",
    "A",
    "A",
    "@",
    "A",
    "Towards heading by defect",
    "",
    "Ingredients %s",
    "Dimension %d",
    "Filters",
    "%s %d headers",
    "In %s ?",
    "Items",
    "",
    "",
    "",
    "Items",
    "",
    "Item set",
    "",
    "Item",
    "Theme index",
    "",
    "",
    "",
    "&Export…",
    "Re&name…",
    "&Remove…",
    "&View…",
    "",
    "Re&place…",
    "",
    "",
    "",
    "Item set",
    "Filtered",
    "Dispatch",
    "Group",
    "Dimension",
    "Components",
    "Clear &item",
    "Clear active se&gment",
    "Clear &all",
    "&Add Heading",
    "&Remove Heading",
    "Re&name Heading",
    "Remove Heading and its &items",
    "&Classify...",
    "&Default Heading",
    "Target directory",
    "Segm.",
    "Items components",
    "Num Cases",
    "Count(000)",
    "Segment %d",
    "%s  Segment %d",
    "Item set headings",
    "Items headings",
    "Questions",
    "Modalities",
    "Questions and modalities",
    NULL
};

const char* DlgItemsMessage::Message_fr[] = {
    "Palettes",
    "Répondants",
    "Prévisualisation et impression de la définition de l'item",
    "Copier la définition de l'item dans presse-papier",
    "Effectuer l'intersection des segments entre eux",
    "Effectuer la réunion des segments entre eux",
    "Sélecteur d'opération entre les segments",
    "Suppression des questions sélectionnées",
    "Sélecteur opération entre les questions sélectionnées",
    "Effectuer l'intersection entre plusieurs modalités d'une même question",
    "Effectuer la réunion entre plusieurs modalités d'une même question",
    "Effectuer l'intersection entre les compléments de plusieurs modalités d'une même question",
    "Effectuer la réunion exclusive entre plusieurs modalités d'une même question",
    "Sélecteur opération entre composants",
    "Decalage élement vers le haut",
    "Decalage élement vers le bas",
    "Sélection de toutes les modalités ou effacement de la sélection en cours",
    "Effectuer l'intersection entre plusieurs éléments d'une même question",
    "Effectuer la réunion entre plusieurs éléments d'une même question",
    "Effectuer l'intersection entre les compléments de plusieurs éléments d'une même question",
    "Effectuer la réunion exclusive entre plusieurs éléments d'une même question",
    "Sélection de tous les éléments ou effacement de la sélection en cours",
    "Afficher soit l'effectif du segment actif, soit celui de tous les segments",
    "Permet de supprimer tout ou une partie de la sélection courante",
    "Accès au sélecteur des questions natives ou modifiées de l'enquête",
    "Et",
    "Ou",
    "Ni",
    "Ex",
    "Veuillez donner un libellé valide.",
    "Item construit à partir d'autres items, pas de genèse possible",
    "(Multi Seg.)",
    "Ensemble",
    "Composition palette",
    "Définition item en cours",
    "Actuellement vous êtes en mode Calcul Segment (effectif, nb cas).\nPour imprimer l'item en cours de construction, le programme reviendra automatiquement en mode Effectif Global, désirez-vous quand même continuer l'impression ?",
    "Pénétration :",
    "En ligne",
    "En colonne",
    "En page",
    "Questions sélectionnées",
    "Ou",
    "Et",
    "Ex",
    "Ni",
    "Ou",
    "Modalités",
    "T",
    "Tree1",
    "Et",
    "Ou",
    "Ou",
    "Ou",
    "Et",
    "Ou",
    "Ou",
    "Et",
    "Ex",
    "Ni",
    "Ou",
    "Questions",
    "List_1",
    "List_2",
    "Tab1",
    "T",
    "Valider",
    "Genèse",
    "Items",
    "Container des questions",
    "Nombre de cas :",
    "Effectif :",
    "Eléments",
    "Segm.",
    "0",
    "0.0 %",
    "0",
    "Terrain",
    "Tout",
    "Dimension1",
    "Dimension2",
    "Dimension1xxx",
    "Individus",
    "T",
    "Rechercher",
    "Tout",
    "Index  thématique",
    "Définition de l'item en construction",
    "Effacer",
    "Supprimer",
    "Lignes",
    "Colonnes",
    "Pages",
    "@",
    "@",
    "T",
    "T",
    "@",
    "T",
    "Vers rubrique par défaut",
    "Marquez les modalités à mettre en %s",
    "Ingrédients %s",
    "Dimension %d",
    "Filtres",
    "Entêtes de %s %d",
    "En %s ?",
    "Items",
    "Effectuer l'intersection entre les modalités ou les éléments de plusieurs questions",
    "Effectuer la réunion entre les modalités ou les éléments de plusieurs questions",
    "Valider la création d'un item construit",
    "Items",
    "Accès au sélecteur des items construits",
    "Palettes",
    "Accès au sélecteur des palettes",
    "Item",
    "Index thématique",
    "Il faut vérifier l'Item avant de le valider!",
    "Ce libellé appartient à un item déjà créé",
    "Items indépendants",
    "&Exporter...",
    "&Renommer...",
    "&Supprimer...",
    "&Visualiser",
    "Libellé item déjà existant",
    "Re&mplacer",
    "Créer une palette, dont les items sont le croisement (intersection) terme à terme des items de plusieurs palettes",
    "Créer une palette, qui soit une suite de plusieurs palettes mises bout à bout",
    "Valider la création d'une palette",
    "Palette",
    " Filtrés",
    "Ventiler",
    "Regrouper",
    "Dimension",
    "Composants",
    "Effacer &item",
    "Effacer se&gment actif",
    "Effacer &tout",
    "&Ajouter Rubrique",
    "&Supprimer Rubrique",
    "&Renommer Rubrique",
    "Supprimer Rubrique et ses &items ",
    "&Classer...",
    "Rubrique par &défaut",
    "Répertoire des cibles",
    "Segm.",
    "Items composants",
    "Nb Cas",
    "Eff(000)",
    "Segment %d",
    "%s  Segment %d",
    "Rubriques palettes",
    "Rubriques Items",
    "Questions",
    "Modalités",
    "Questions et modalités",
    NULL
};

const char* DlgItemsMessage::Message_it[] = {
    "Insieme d' items",
    "Dichiaranti",
    "",
    "",
    "Effettuare l' intersezione dei segmenti tra loro",
    "Effettuare la riunione dei segmenti tra loro",
    "Selezionatore delle operazione tra i segmenti",
    "Soppressione delle questioni scelte",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "And",
    "Or",
    "Nor",
    "Escl",
    "",
    "",
    "",
    "Insieme",
    "",
    "Definizione item in costruzione",
    "",
    "Penetrazione :",
    "In linea",
    "In colonna",
    "In pagina",
    "Domande selezionate",
    "Or",
    "And",
    "Escl",
    "Nor",
    "Or",
    "Modalita'",
    "T",
    "",
    "And",
    "Or",
    "Or",
    "Or",
    "And",
    "Or",
    "Or",
    "And",
    "Escl",
    "Nor",
    "Or",
    "Domande",
    "",
    "",
    "",
    "T",
    "Validare",
    "Genesi",
    "Items",
    "Modulo domande",
    "Numero di casi :",
    "Effettivo :",
    "Elementi",
    "Segm.",
    "0",
    "0.0 %",
    "0",
    "Periodo",
    "Tutti",
    "Dimensione1",
    "Dimensione2",
    "Dimensione1xxx",
    "Individui",
    "T",
    "Ricercare",
    "Tutti",
    "Indice tematico",
    "Definizione item in costruzione",
    "Cancellare",
    "Sopprimi",
    "Linee",
    "Colonne",
    "pagine",
    "@",
    "@",
    "T",
    "T",
    "@",
    "T",
    "Verso rubrica per difetto",
    "",
    "Ingredienti %s",
    "Dimensione %d",
    "Filtri",
    "Intestazioni di %s %d",
    "In %s ?",
    "Items",
    "",
    "",
    "",
    "Items",
    "",
    "Insieme d' items",
    "",
    "Item",
    "Indice tematico",
    "",
    "",
    "",
    "&Esportare…",
    "&Rieleggere…",
    "&Sopprimi…",
    "&Visualizzare…",
    "",
    "S&ostituire",
    "",
    "",
    "",
    "Insieme d' items",
    " Filtrate",
    "Ripartire",
    "Raccogliere",
    "Dimensione",
    "Componenti",
    "Cancellare &item",
    "Cancellare se&gmento attivo",
    "Cancellare &tutti",
    "&Aggiungere rubrica",
    "&Eliminare rubrica",
    "&Rieleggere rubrica",
    "Eliminare rubrica ed i suoi &items ",
    "&Classificare…",
    "Rubrica per &difetto",
    "Catalogo Target",
    "Segm.",
    "Items Componenti",
    "Numero di casi",
    "Effettivo(000)",
    "Segmento %d",
    "%s  Segmento %d",
    "Insieme d' items rubrica",
    "Item rubrica",
    "Domande",
    "Modalità",
    "Domande e modalità",
    NULL
};

#endif
