//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RepItemsExt.rc
//
#define IDB_RI_BITMAP1                  2000
#define IDB_RI_BITMAP2                  2001
#define IDB_RI_BITMAP3                  2002
#define IDB_RI_BITMAP4                  2003
#define IDB_RI_BITMAP5                  2004
#define IDB_RI_BITMAP6                  2005
#define IDB_RI_TREE_BMP                 2006
#define IDD_RI_ABOUTBOX                 2007
#define IDD_RI_DLG_ITEMS                2008
#define IDD_RI_DLG_LIBELLE              2009
#define IDD_RI_DLG_DIMENSION            2010
#define IDD_RI_DLG_PATRIMOINE           2011
#define IDD_RI_DLG_SEGMENT              2012
#define IDD_RI_DLG_SOURCE               2013
#define IDD_RI_DLG_VALUES               2014
#define IDI_RI_FILTRE                   2015
#define IDI_RI_TRANS                    2016
#define IDI_RI_ICON                     2017
#define IDM_RI_DECILE                   2018
#define IDM_RI_DELETE_ITEM              2019
#define IDM_RI_VISU_ITEM                2020
#define IDM_RI_GROUP_DIMENSION1         2021
#define IDM_RI_PALETTE_1                2022
#define IDM_RI_PALETTE_2                2023
#define IDM_RI_PALETTE_3                2024
#define IDM_RI_PALETTE_4                2025
#define IDM_RI_PALETTE_5                2026
#define IDM_RI_PALETTE_6                2027
#define IDM_RI_PAT_CONSULTER            2028
#define IDM_RI_QUARTILE                 2029
#define IDM_RI_QUINTILE                 2030
#define IDM_RI_RENAME_ITEM              2031
#define IDM_RI_RENAME_DIMENSION1        2032
#define IDM_RI_SEG_CHANGER              2033
#define IDM_RI_SP_CHOISIR               2034
#define IDM_RI_TERCILE                  2035
#define IDR_RI_MENU                     2036
#define IDR_RI_MENU_GENERAL             2037
#define IDR_RI_MENU_POPUPS              2038
#define IDS_RI_ABOUTBOX                 2039
#define IDS_RI_CLASSES                  2040
#define IDS_RI_DECILE                   2041
#define IDS_RI_DEGROUPER                2042
#define IDS_RI_MATRIX                   2043
#define IDS_RI_FMT_DECILE               2044
#define IDS_RI_FMT_GROS                 2045
#define IDS_RI_FMT_MOYEN                2046
#define IDS_RI_FMT_PETIT                2047
#define IDS_RI_FMT_QUANTILE             2048
#define IDS_RI_FMT_QUARTILE             2049
#define IDS_RI_FMT_QUINTILE             2050
#define IDS_RI_FMT_SANSVALEUR           2051
#define IDS_RI_GRANDTHEME               2052
#define IDS_RI_GROUPER                  2053
#define IDS_RI_INDEX_THEMATIQUE         2054
#define IDS_RI_ITEM_LABEL               2055
#define IDS_RI_ITEMS_CONST              2056
#define IDS_RI_LABEL_CLASS              2057
#define IDS_RI_LABEL_ITEM               2058
#define IDS_RI_LABEL_QUANTILE           2059
#define IDS_RI_PAGES                    2060
#define IDS_RI_MODIFIER                 2061
#define IDS_RI_PSEUDO                   2062
#define IDS_RI_QUANTILES                2063
#define IDS_RI_QUARTILE                 2064
#define IDS_RI_QUINTILE                 2065
#define IDS_RI_REGROUPE_CLASSES         2066
#define IDS_RI_RENOMMER                 2067
#define IDS_RI_SUPPORTS                 2068
#define IDS_RI_SUPPRIMER                2069
#define IDS_RI_TERCILE                  2070
#define IDS_RI_PALETTES                 2071
#define IDB_RI_DOWN                     2072
#define IDS_PU_AJOUT_LIGNES             2073
#define IDS_RI_LABEL_PALETTE            2074
#define IDB_RI_UP                       2075
#define IDS_PU_AJOUT_COLONNES           2076
#define IDS_RI_ITEMS                    2077
#define IDD_RI_DLG_POIDS                2078
#define IDS_PU_AJOUT_PAGES              2079
#define IDS_RI_EN_PALETTE               2080
#define IDS_RI_EN                       2081
#define IDS_RI_LINE_DIM                 2082
#define IDB_RI_BITMAP7                  2083
#define IDS_RI_COLUMN_DIM               2084
#define IDM_RI_PALETTE_7                2085
#define IDB_RI_BITMAP8                  2086
#define IDS_RI_PALETTE_DIM              2087
#define IDM_RI_PALETTE_8                2088
#define IDS_RI_CONSULTATION             2089
#define IDM_RI_PALETTE_9                2090
#define IDS_RI_EXPORTER                 2091
#define IDS_RI_NICHE                    2092
#define IDS_RI_LINE                     2093
#define IDS_RI_COLUMN                   2094
#define IDS_RI_REPONDANTS               2095
#define IDS_RI_USER_BLOC                2096
#define IDB_RI_CIRCLES_OU               2097
#define IDB_RI_CIRCLES_ET               2098
#define IDS_RI_OU                       2099
#define IDB_RI_CIRCLES_XOR              2100
#define IDS_RI_ET                       2101
#define IDB_RI_CIRCLES_NI               2102
#define IDS_RI_NI                       2103
#define IDS_RI_XOR                      2104
#define IDB_RI_SEGMENTS                 2105
#define IDB_RI_SEGMENT                  2106
#define IDS_RI_TT_QUESTION              2107
#define IDB_RI_CIRCLES_XOR1             2108
#define IDS_RI_TT_ITEMS                 2109
#define IDB_RI_CIRCLES_OU1              2110
#define IDS_RI_TT_PALETTE               2111
#define IDB_RI_CIRCLES_NI1              2112
#define IDS_RI_TT_TITRES                2113
#define IDB_RI_CIRCLES_ET1              2114
#define IDS_RI_TT_T_M                   2115
#define IDS_RI_TT_T_E                   2116
#define IDB_RI_TUBE                     2117
#define IDS_RI_TT_OU_M                  2118
#define IDS_RI_TT_OU_E                  2119
#define IDS_RI_TT_ET_M                  2120
#define IDB_RI_PALETTE                  2121
#define IDS_RI_TT_ET_E                  2122
#define IDS_RI_TT_XOR_M                 2123
#define IDS_RI_TT_XOR_E                 2124
#define IDD_RI_DLG_EXPORT               2125
#define IDS_RI_TT_NI_M                  2126
#define IDD_RI_BROWSER_DLG              2127
#define IDS_RI_TT_NI_E                  2128
#define IDS_RI_TT_OU_Q_ITEM             2129
#define IDR_MENU_HTMLBROWSER            2130
#define IDS_RI_TT_ET_Q_ITEM             2131
#define IDS_RI_TT_OU_S                  2132
#define IDS_RI_TT_ET_S                  2133
#define IDS_RI_TT_OU_Q_PALETTE          2134
#define IDS_RI_TT_ET_Q_PALETTE          2135
#define IDS_RI_TT_RAZ_TOUT              2136
#define IDS_RI_ONGLET_SELECTION         2137
#define IDS_RI_TT_RAZ_ITEM              2138
#define IDS_RI_TT_BUT_OPE_SELQU         2139
#define IDS_RI_TT_BUT_OPE_SEGMENT       2140
#define IDS_RI_TT_SEGMENT               2141
#define IDS_RI_TT_VALID_ITEM            2142
#define IDS_RI_TT_VALID_PALETTE         2143
#define IDS_RI_TT_VALID_CLASSE          2144
#define IDS_RI_TT_VALID_QUANTILE        2145
#define IDS_RI_TT_CLASSES               2146
#define IDS_RI_TT_QUANTILES             2147
#define IDS_RI_PREVIEW                  2148
#define IDS_RI_INDUITES                 2149
#define IDS_RI_LABEL_INDUITE            2150
#define IDS_RI_TT_VALID_INDUITE         2151
#define IDS_RI_QUE_INDUITES             2152
#define IDS_RI_QINDUITE_AUCUN           2153
#define IDS_RI_DIM_DIMENSION            2154
#define IDS_RI_PAGE_DIM                 2155
#define IDS_RI_ITEM_DIM                 2156
#define IDS_RI_ITEMNATIF                2157
#define IDS_RI_DIM_ERROR                2158
#define IDS_RI_DIM_SEL                  2159
#define IDD_RI_DLG_VISU                 2160
#define IDR_RI_MENU_QFILTER             2161
#define IDS_RI_LINEMODE_ERR             2162
#define IDS_RI_VERIFIER                 2163
#define IDR_RI_MENU_PFILTER             2164
#define IDS_RI_ITEMEXISTS               2165
#define IDS_RI_VALIDER_PALETTE          2166
#define IDS_RI_FILTRES                  2167
#define IDS_RI_VAL_ERROR                2168
#define IDS_RI_VAL_SEL                  2169
#define IDS_STRING2143                  2170
#define IDS_RI_DEFAULT_LABEL_ITEMS_CONSTRUITS 2171
#define IDS_RI_DEFAULT_LABEL_ITEMS_INDEPENDANTS 2172
#define IDS_RI_DEFAULT_LABEL_CROISEMENT_PALETTES 2173
#define IDS_RI_TITLE_PUPITRE            2174
#define IDS_RI_TT_GROUPER               2175
#define IDS_RI_COMPTER                  2176
#define IDS_RI_TT_COMPTER               2177
#define IDS_RI_GROUPER_ERROR            2178
#define IDS_RI_QUANTILE_ERROR           2179
#define IDD_RI_UPWARDS                  2180
#define IDS_RI_TT_INDUITES              2181
#define IDB_RI_LOGO_ITEM                2182
#define IDS_RI_INDUITE_ERROR            2183
#define IDB_RI_LOGO_PALETTE             2184
#define IDB_RI_LOGO_QUESTINDUITE        2185
#define IDS_RI_COMPOSANTS               2186
#define IDB_RI_LOGO_QUANTILE            2187
#define IDS_RI_TT_BUT_OPE_DIM1          2188
#define IDB_RI_LOGO_CLASSE              2189
#define IDS_RI_TT_BUT_OPE_SELQUESTION   2190
#define IDD_RI_DLG_REMPLACE             2191
#define IDS_RI_TT_BUT_OPE_SEGMENTS      2192
#define IDR_RI_MENU_SUPPRESSION         2193
#define IDS_RI_DIM_SEL_NEW              2194
#define IDS_RI_TT_SUPPRESSION           2195
#define IDR_RI_MENU_OPE_DIM2            2196
#define IDS_RI_LBL_ITEM_CONSTRUCTION    2197
#define IDS_RI_LBL_PALETTE_COMPO        2198
#define IDS_RI_SUITE_PALETTE            2199
#define IDS_RI_CROISE_PALETTE           2200
#define IDB_BITMAP1                     2201
#define IDB_RI_IMP                      2202
#define IDS_RI_DIM_DIMENSION_UNIQUE     2203
#define IDS_RI_ONGLET_VERIFIER          2204
#define IDR_RI_MENU_SUPP_SELPUPITRE     2205
#define IDS_RI_DIM_SEL_NEW_INGREDIENT   2206
#define IDB_RI_CROISE_PALETTE           2207
#define IDS_PU_SUPPRESSION              2208
#define IDB_RI_CIRCLES_ET2              2209
#define IDS_PU_TR_LIGNES                2210
#define IDB_RI_SUITE_PALETTE            2211
#define IDS_PU_TR_COLONNES              2212
#define IDS_PU_TR_PAGES                 2213
#define IDS_PU_CC_LIGNES                2214
#define IDS_PU_CC_COLONNES              2215
#define IDS_PU_CC_PAGES                 2216
#define IDB_BITMAP3                     2217
#define IDS_PU_SUPP_DOUBLON             2218
#define IDB_RI_MIN_LIST_SELPUPITRE      2219
#define IDS_RI_TT_RAZ_S                 2220
#define IDB_RI_MAX_LIST_SELPUPITRE      2221
#define IDS_RI_DIM_SEL_NEW_INGREDIENT_VENT 2222
#define IDS_PU_TRI_LIGNES               2223
#define IDR_RI_MENU_SUPP_PALETTE        2224
#define IDS_RI_ITEM_UP                  2225
#define IDS_RI_ITEM_DOWN                2226
#define IDR_RI_MENU_RUBRIQUES           2227
#define IDS_RI_DIM_SEL_NEW_INGREDIENT_NONVENT 2228
#define IDS_PU_TRI_COLONNES             2229
#define IDS_PU_TRI_PAGES                2230
#define IDD_RI_DLG_CLASSE_ITEMS         2231
#define IDS_RI_RUBRIQUE_ITEMS           2232
#define IDS_RI_DIVERS                   2233
#define IDS_RI_NEW_RUBRIQUE             2234
#define IDS_RI_SUPP_RUBRIQUE            2235
#define IDS_RI_RUBR_DEJA_EXISTANTE      2236
#define IDS_RI_MESS_RUBRIQUE1           2237
#define IDS_RI_IMP_ITEM                 2238
#define IDS_RI_EXPORT_ITEM              2239
#define IDB_RI_EXPORT_ITEM              2240
#define IDB_RI_EXPORT_ITEM2             2241
#define IDS_RI_RUBRIQUE_PALETTES        2242
#define IDS_RI_MESS_1                   2243
#define IDS_RI_MESS_2                   2244
#define IDS_RI_MULTISEG                 2245
#define IDS_RI_ENSEMBLE                 2246
#define IDS_STRING2195                  2247
#define IDS_RI_LABELITEM_EXIST          2248
#define IDS_RI_DIM_SEL_VENTILER         2249
#define IDS_RI_DIM_SEL_REGROUPER        2250
#define IDC_RI_BUT_ACCEPT               2251
#define IDR_RI_MENU_OPE_DIM1            2252
#define IDC_RI_BUT_DIM2_RAZ             2253
#define IDC_RI_BUT_QUESTION_TOUS        2254
#define IDC_RI_BUT_GENESE               2255
#define IDC_RI_BUT_ITEM_RAZ             2256
#define IDC_RI_BUT_ALL_LIGNES           2257
#define IDC_RI_BUT_DIM1_DOWN            2258
#define IDC_RI_BUT_DIM1_RAZ             2259
#define IDC_RI_BUT_DIM1_UP              2260
#define IDC_RI_BUT_COLONNES_UP          2261
#define IDC_RI_BUT_Q_RAZ                2262
#define IDC_RI_BUT_COLONNES_DOWN        2263
#define IDC_RI_BUT_RAZ_TOUT             2264
#define IDC_RI_BUT_PAGES_UP             2265
#define IDC_RI_BUT_RAZSEARCH            2266
#define IDC_RI_BUT_START                2267
#define IDC_RI_RAD_DIMENSION1           2268
#define IDC_RI_CHECK_CALC_SEGMENT       2269
#define IDC_RI_COMBO_SOURCE             2270
#define IDC_RI_RAD_DIMENSION2           2271
#define IDC_RI_EDIT_NAME                2272
#define IDC_RI_EDIT_SEARCH              2273
#define IDC_RI_LABEL                    2274
#define IDC_RI_EDIT_QFILTER             2275
#define IDC_RI_BUTTON                   2276
#define IDC_RI_LABEL_EFFECTIF           2277
#define IDC_RI_LABEL1                   2278
#define IDC_RI_LABEL_REMPLACEPAR        2279
#define IDC_RI_LABEL_DIMENSION2         2280
#define IDC_RI_LABEL_ITEMS              2281
#define IDC_RI_BUT_QFILTER              2282
#define IDC_RI_LABEL_LIBELLE            2283
#define IDC_RI_BUT_PAGES_DOWN           2284
#define IDC_RI_LABEL_DIMENSION1         2285
#define IDC_RI_LABEL_NBCAS              2286
#define IDC_RI_LABEL_QUESTIONS          2287
#define IDC_RI_LABEL_SAS                2288
#define IDC_RI_LABEL_SOURCE             2289
#define IDC_RI_LABEL_QUESTIONS2         2290
#define IDC_RI_LABEL_THEME              2291
#define IDC_RI_LABEL_TITLE              2292
#define IDC_RI_LIBELLE                  2293
#define IDC_RI_LABEL_TYPEPOIDS          2294
#define IDC_RI_LIST_DIMENSION2          2295
#define IDC_RI_LIST_IITEMS              2296
#define IDC_RI_LIST_DIMENSION1          2297
#define IDC_RI_LIST_QUESTIONS           2298
#define IDC_RI_LIST_SAS                 2299
#define IDC_RI_LIST_SEGMENT             2300
#define IDC_RI_BUT_QFILTERRAZ           2301
#define IDC_RI_LIST_TERRAIN             2302
#define IDC_RI_BUT_SUPPRESSION          2303
#define IDC_RI_LIST_VALUES              2304
#define IDC_RI_BUT_LIGNES_DOWN          2305
#define IDC_RI_RAD_DIM2_ET              2306
#define IDC_RI_RAD_DIM2_NI              2307
#define IDC_RI_RAD_DIM2_OU              2308
#define IDC_RI_RAD_DIM2_XOR             2309
#define IDC_RI_RAD_DIM1_ET              2310
#define IDC_RI_RAD_DIM1_NI              2311
#define IDC_RI_RAD_DIM1_OU              2312
#define IDC_RI_RAD_DIM1_XOR             2313
#define IDC_RI_RAD_Q_ET                 2314
#define IDC_RI_RAD_Q_OU                 2315
#define IDC_RI_RAD_S_ET                 2316
#define IDC_RI_RAD_S_OU                 2317
#define IDC_RI_STATIC_BOX               2318
#define IDC_RI_BUT_MENU_OPE_DIM1        2319
#define IDC_RI_STATIC_BOX1              2320
#define IDC_RI_BUT_MENU_OPE_DIM2        2321
#define IDC_RI_STATIC_BOX2              2322
#define IDC_RI_BUT_MENU_OPE_QUSEL       2323
#define IDC_RI_STATIC_EFF               2324
#define IDC_RI_STATIC_DIMENSION2        2325
#define IDC_RI_STATIC_ITEMS             2326
#define IDC_RI_BUT_MENU_OPE_SEGMENT     2327
#define IDC_RI_STATIC_DIMENSION1        2328
#define IDC_RI_STATIC_NBCAS             2329
#define IDC_RI_STATIC_PERCENT           2330
#define IDC_RI_STATIC_QUESTION          2331
#define IDC_RI_STATIC_SAS               2332
#define IDC_RI_STATIC_SEGMENT           2333
#define IDC_RI_STATIC_SOURCE            2334
#define IDC_RI_STATIC_ONGLET_PUPITRE    2335
#define IDC_RI_STATIC_SRCTERRAIN        2336
#define IDC_RI_STATIC_TERRAIN           2337
#define IDC_RI_BUT_LIGNES_UP            2338
#define IDC_RI_STATIC_THEME             2339
#define IDC_RI_STATIC_TITLE             2340
#define IDC_RI_TAB_SEGMENT              2341
#define IDC_RI_TREE                     2342
#define IDC_RI_BUT_ALL_PAGES            2343
#define IDC_RI_BUT_SAS_RAZ              2344
#define IDC_RI_TREE_THEME               2345
#define IDC_RI_RAD_QUESTIONS            2346
#define IDC_RI_RAD_LIST_1               2347
#define IDC_RI_RAD_LIST_2               2348
#define IDC_RI_RAD_VERIFIER             2349
#define IDC_RI_TREE_THEME2              2350
#define IDC_RI_TREE_RUBRIC_ITEMS        2351
#define IDC_RI_RAD_LIST_3               2352
#define IDC_RI_RAD_TITLE                2353
#define IDC_RI_RAD_MODE_LIGNES          2354
#define IDC_RI_RAD_MODE_COLONNES        2355
#define IDC_RI_RAD_MODE_PAGES           2356
#define IDC_RI_LIST_POIDS               2357
#define IDC_RI_TREE_RUBRIC_ITEMS2       2358
#define IDC_RI_TREE_RUBRIC_PALETTES     2359
#define IDC_RI_BTN_PROPERTY             2360
#define IDC_RI_LIST_ITEMS               2361
#define IDC_RI_EXPLORER                 2362
#define IDC_RI_LIST_LIGNES              2363
#define IDC_RI_BUT_EXIT                 2364
#define IDC_RI_LIST_COLONNES            2365
#define IDC_RI_LIST_PAGES               2366
#define IDC_RI_LIST_COMPO_PALETTE       2367
#define IDC_RI_BUT_VALUES_RAZ           2368
#define IDC_RI_LIST_LIGNES2             2368
#define IDC_RI_LIST_TRI                 2368
#define IDC_RI_PUSH_DIM1_OK             2369
#define IDC_RI_BUT_VALUES_SUP1          2369
#define IDC_RI_BUT_VALUES_QTLE          2370
#define IDC_UPWARDS                     2371
#define IDC_RI_LIST_UPWARDS             2372
#define IDC_RI_BTN_IMPITEM              2373
#define IDC_RI_LABEL_DEFITEM            2374
#define IDC_RI_PICT                     2375
#define IDC_RI_LABEL_LIGNES             2376
#define IDC_RI_LABEL_ITEM               2377
#define IDC_RI_LIBELLE_REMPLACE         2378
#define IDC_RI_LABEL_ITEM2              2378
#define IDC_RI_LABEL_NBCELLS            2378
#define IDC_RI_LABEL_COLONNES           2379
#define IDC_EDIT2                       2380
#define IDC_RI_LIBELLE_REMPLACEPAR      2381
#define IDC_RI_LABEL_PAGES              2382
#define IDC_RI_LABEL_REMPLACE           2383
#define IDC_RI_BTN_RESIZE_SELPUPITRE    2384
#define IDC_RI_BTN_EXPORT_ITEM          2385
#define IDC_RI_STATIC_BOX_REMPLACE      2386
#define IDC_RI_BTN_SUPP_ITEM            2387
#define IDC_RI_BTN_SITES_LIG            2388
#define IDC_RI_BUT_ALL_COLONNES         2389
#define IDC_RI_BTN_SITES_COL            2390
#define IDC_RI_STATIC_RESULT            2391
#define IDC_RI_STATIC_PUPITRE           2392
#define IDC_RI_BTN_SITES_PAGE           2393
#define IDC_RI_BUT_MENU_OPE_MODA2       2394
#define IDC_RI_BTN_UP                   2394
#define IDC_BUTTON1                     2395
#define IDC_RI_BTN_DOWN                 2395
#define IDC_RAZ                         2395
#define IDC_RI_LIST_RUBRIQUES           2396
#define IDC_RI_BUT_TRANSFERT_ITEMS      2397
#define IDC_RI_LIST_RUBR_DEST           2398
#define IDC_RI_LABEL_RUBR_SRC           2399
#define IDC_CUSTOM1                     2400
#define IDC_RI_LABEL_RUBR_DST           2401
#define IDC_RI_CADRE_RESULT             2402
#define IDC_RI_LABEL_POURCENT           2403
#define IDC_RI_CHK_RUBRIQUE_DEFAUT      2404
#define IDC_COMBO1                      2405
#define IDC_RI_COMBO_RUBRIQUES          2406
#define IDR_HTML_DLGCLASSEMENTITEMS     2407
#define IDB_RI_BITMAP9                  2408
#define IDB_RI_BITMAP10                 2409
#define IDB_RI_BITMAP11                 2410
#define IDB_RI_BITMAP12                 2411
#define IDC_RI_LABEL2                   2412
#define IDS_RI_SUPP_ITEM                2413
#define IDI_ICON1                       2414
#define IDI_RI_RAZ                      2415
#define IDC_RI_BUT_ITEM_MOY_LIG         2416
#define IDC_RI_BUT_ITEM_MOY_COL         2417
#define IDD_RI_DLG_ITEMS_MOYENNE        2418
#define IDS_RI_VALEURS_NUM              2419
#define IDC_RI_BUT_SEGMENT_RAZ          2420
#define IDS_RI_BUT_SUPPRIMER            2421
#define IDS_RI_BUT_SEGEMENT             2422
#define IDS_RI_COL_ITEMS_COMP           2423
#define IDS_RI_COL_NBCAS                2424
#define IDS_RI_COL_EFF                  2425
#define IDS_RI_LABEL_SEG                2426
#define IDS_RI_LABEL_OPSEG              2427
#define IDS_RI_TT_RAZ_SEG               2428
#define IDI_RI_ICON_ALL                 2429
#define IDC_RI_LIST_ITEMSMOY_AUTO       2430
#define IDC_RI_LIST_ITEMSMOY_UTIL       2431
#define IDC_RI_TREE_QUANTI              2432
#define IDC_RI_ALL_QUANTI_AUTO          2433
#define IDC_RI_ALL_QUANTI_UTIL          2434
#define IDB_RI_BITMAP13                 2435
#define IDB_RI_BITMAP14                 2436
#define IDB_RI_BITMAP15                 2437
#define IDC_RI_BUT_FILTRE               2438
#define IDS_RI_ITEM_FILTRE              2439
#define IDI_ICON2                       3010
#define IDI_ICON3                       3011
#define IDI_ICON4                       3012
#define IDB_BITMAP2                     3013
#define IDI_ICON5                       3016
#define IDI_ICON6                       3018
#define IDI_ICON7                       3019
#define IDI_ICON8                       3020
#define IDI_ICON9                       3021
#define IDI_ICON10                      3022
#define IDI_ICON11                      3023
#define IDI_ICON12                      3025
#define IDI_ICON13                      3028
#define IDD_RI_FILTRE_MODA              3029
#define IDI_ICON14                      3030
#define IDC_RI_LIST_FILTRE              5017
#define IDC_LIST1                       5018
#define IDI_ATP_ANALYSEUR               6007
#define IDI_RI_ICON_RUBRIQUE            6008
#define IDC_CS_SPLIT2_VERT              7124
#define IDM_RI_DELETE_DIMENSION1        33002
#define IDM_RI_ITEM                     33008
#define IDM_RI_PALETTE                  33009
#define IDM_RI_CLASSE                   33010
#define IDM_RI_QUANTILE                 33011
#define IDM_RI_PALETTE_11               33015
#define IDM_RI_PALETTE_10               33016
#define IDM_RI_ICONES                   33017
#define IDM_RI_EXPORT_ITEM              33029
#define IDM_RI_PREVIEW                  33030
#define IDM_RI_PREVIEW_ITEM             33032
#define IDM_RI_PREVIEW_DIMENSION1       33033
#define IDM_RI_INDUITE                  33036
#define IDM_RI_PAT_IMPORTER             33037
#define IDM_RI_PAT_EXPORTER             33038
#define IDM_RI_VISUALISEITEM            33040
#define IDM_RI_QFTOUS                   33045
#define IDM_RI_QFQUESTIONS              33046
#define IDM_RI_QFMODALITES              33047
#define IDM_RI_QFANNULER                33048
#define ID_Menu                         33049
#define IDM_RI_QFPALETTE                33050
#define IDM_RI_ABOUTBOX                 33051
#define IDM_RI_QUITTER                  33052
#define IDM_RI_VISUALISER_DIMENSION1    33053
#define IDM_RI_REMPLACER_DIMENSION1     33054
#define IDS_RI_VISUALISER               33055
#define IDS_RI_REMPLACER                33056
#define IDM_RI_EFFACER_TOUT             33057
#define IDM_RI_PALETTE_12               33058
#define IDM_RI_EFFACER_SEGMENT          33060
#define ID_TEST_OPTION1                 33061
#define ID_TEST_OPTION2                 33062
#define IDM_RI_OPE_DIM1_OU              33063
#define IDM_RI_OPE_DIM1_ET              33064
#define IDM_RI_OPE_DIM1_EX              33065
#define IDM_RI_OPE_DIM1_NI              33066
#define IDM_RI_OPE_DIM2_OU              33067
#define IDM_RI_OPE_DIM2_ET              33068
#define IDM_RI_OPE_DIM2_XOR             33069
#define IDM_RI_OPE_DIM2_NI              33071
#define IDM_RI_PALETTE_13               33072
#define IDM_RI_PALETTE_14               33073
#define IDM_RI_PALETTE_15               33074
#define IDR_RI_MENU_SUPP_LIGNES         33075
#define IDR_RI_MENU_SUPP_COLONNES       33076
#define IDR_RI_MENU_SUPP_PAGES          33077
#define IDR_RI_MENU_SUPP_TOUT           33079
#define IDM_PU_SUPPRESSION              33080
#define IDM_PU_TR_LIGNES                33081
#define IDM_PU_TR_COLONNES              33082
#define IDM_PU_TR_PAGES                 33083
#define ID_SUPPRIMERTOUTESLESLIGNES     33083
#define IDM_PU_CC_LIGNES                33084
#define ID_SUPPRIMERTOUTESLESCOLONNES   33084
#define IDM_PU_CC_COLONNES              33085
#define ID_SUPPRIMERTOUTESLESPAGES      33085
#define IDM_PU_CC_PAGES                 33086
#define IDM_PU_SUPP_DOUBLON             33087
#define IDM_RI_EFFACER_PALETTE          33088
#define IDM_RI_EFFACER_TOUT_PALETTE     33089
#define IDM_RI_EFFACER_ITEM             33090
#define IDM_PU_TRI_LIGNES               33091
#define IDM_PU_TRI_COLONNES             33092
#define IDR_RI_MENU_SUPP_ALL_LCP        33093
#define IDM_PU_TRI_PAGES                33094
#define IDM_PU_SUPP_ALL_LIGNES          33095
#define ICD_RI_MENU_RUBRIQUE            33096
#define IDM_PU_SUPP_ALL_COLONNES        33097
#define IDM_PU_SUPP_ALL_PAGES           33098
#define IDS_PU_SUPP_ALL_LIGNES          33099
#define IDS_PU_SUPP_ALL_COLONNES        33100
#define ID_RI_AJOUTER_RUBRIQUE          33101
#define IDS_PU_SUPP_ALL_PAGES           33102
#define ID_RI_SUPPRIMER_RUBRIQUE        33103
#define IDS_PU_SUPP_SEL_LIGNES          33104
#define ID_RI_RENOMMER_RUBRIQUE         33105
#define IDS_PU_SUPP_SEL_COLONNES        33106
#define ID_CTXMENUCLASSITEM_CLASSERITEMS 33107
#define IDS_PU_SUPP_SEL_PAGES           33108
#define ID_RI_CLASSER_ITEMS             33109
#define ID_RI_SUPPRIMER_RUBRIQUE_ET_ITEMS 33110
#define IDM_RI_SOURCE_CHANGER           33111
#define ID_RI_RUBRIQUE_PARDEFAUT        33112
#define IDM_PU_AJOUT_LIGNES             33113
#define IDM_PU_AJOUT_COLONNES           33114
#define IDM_PU_AJOUT_PAGES              33115

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3031
#define _APS_NEXT_COMMAND_VALUE         33116
#define _APS_NEXT_CONTROL_VALUE         5019
#define _APS_NEXT_SYMED_VALUE           6009
#endif
#endif
