//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Nomenclature.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_NOMENCLATURE_FORM           101
#define IDD_DIALOG_FORMULAIRE_NOM       102
#define IDD_DIALOG_FORMULAIRE_STANDARD  103
#define IDD_DIALOG_FORMULAIRE_PRODUIT   104
#define IDR_MAINFRAME                   128
#define IDR_NOMENCTYPE                  129
#define IDB_BITMAP_ITEM                 132
#define IDR_MENUPOPUP                   133
#define IDD_DIALOG_INFO                 134
#define IDD_DIALOG_FORMULAIRE_IMPRESSION 136
#define IDD_DIALOG_FORMULAIRE_GROUPE    137
#define IDD_DIALOG_NLLE_ANNEE           138
#define IDD_DIALOG_TAUXFO               142
#define IDD_DIALOG_UTILTAUX             144
#define IDD_DIALOG_EDI                  145
#define IDD_DIALOG_TIERSEDI             146
#define IDB_BITMAPJFC                   147
#define IDB_BITMAPJFCSMALL              150
#define IDC_TREE1                       1000
#define IDC_CADRE1                      1001
#define IDC_EDIT1_1                     1002
#define IDC_CADRE2                      1002
#define IDC_EDIT1_2                     1003
#define IDC_CADRE3                      1003
#define IDC_EDIT1_3                     1004
#define IDC_CADRE4                      1004
#define IDC_CADRE5                      1005
#define IDC_CADRE6                      1006
#define IDC_STATIC1                     1007
#define IDC_RADIO1                      1008
#define IDC_RADIO2                      1009
#define IDC_STATIC_NOMREP1              1010
#define IDC_CHECK1                      1010
#define IDC_STATIC_ALIAS1               1011
#define IDC_STATIC_REF                  1011
#define IDC_RADIO3                      1011
#define IDC_STATIC_CODE1                1012
#define IDC_STATIC_REF2                 1013
#define IDC_CADRE7                      1014
#define IDC_STATIC_ALIAS4               1015
#define IDC_STATIC_NOMREP4              1016
#define IDC_STATIC_CODE4                1017
#define IDC_EDIT3_2                     1018
#define IDC_EDIT4_2                     1018
#define IDC_STATIC_ALIAS3               1019
#define IDC_EDIT4_1                     1019
#define IDC_EDIT4_3                     1020
#define IDC_STATIC_DATE4                1021
#define IDC_EDIT4_4                     1022
#define IDC_STATIC_INFODATE4            1023
#define IDC_STATIC_REF4                 1024
#define IDC_FAMILLE2                    1025
#define IDC_SECTEUR2                    1026
#define IDC_STATIC_NOMREP2              1027
#define IDC_STATIC_ALIAS2               1028
#define IDC_LIST_ANNEE_POSSIBLE         1028
#define IDC_STATIC_CODE2                1029
#define IDC_STATIC_ANNEE                1029
#define IDC_EDIT2_1                     1030
#define IDC_CADRE8                      1030
#define IDC_EDIT2_2                     1031
#define IDC_STATIC_TRAIT                1031
#define IDC_EDIT2_3                     1032
#define IDC_STATIC_ANNEECOUR            1032
#define IDC_EDIT2_4                     1033
#define IDC_STATIC2_ANNEECOUR           1034
#define IDC_COMBOMARQUE2                1035
#define IDC_MARQUE2                     1036
#define IDC_COMBOFAMILLE2               1037
#define IDC_COMBOSECTEUR2               1038
#define IDC_TAUX1                       1039
#define IDC_TAUX2                       1040
#define IDC_TAUX3                       1041
#define IDC_TAUX4                       1042
#define IDC_TAUX5                       1043
#define IDC_TAUXCM                      1044
#define IDC_EXTAUX1                     1045
#define IDC_EXTAUX2                     1046
#define IDC_EXTAUX3                     1047
#define IDC_EXTAUX4                     1048
#define IDC_EXTAUX5                     1049
#define IDC_EXTAUXCM                    1050
#define IDC_SIMTAUX1                    1051
#define IDC_SELCHAINE                   1052
#define IDC_NVNOMDATE                   1053
#define IDC_EXNOMDATE2                  1054
#define IDC_LIST_STATIONS               1055
#define IDC_TAUXFO                      1056
#define IDC_EXTAUXFO                    1057
#define IDC_SIMTAUX2                    1058
#define IDC_SIMTAUX3                    1059
#define IDSuppTaux                      1060
#define IDC_CADRE9                      1061
#define IDC_SIMTAUX4                    1062
#define IDSauverTaux                    1063
#define IDC_SIMTAUX5                    1064
#define IDC_CADRE10                     1065
#define IDC_SIMTAUXCM                   1065
#define IDC_NOM_UTILTAUX                1066
#define IDC_SIMTAUXFO                   1066
#define IDC_MP_UTILTAUX                 1067
#define IDSuppTauxSimul                 1067
#define IDC_AJOUTUTILTAUX               1070
#define IDC_SUPPUTILTAUX                1071
#define IDC_SELRADIO                    1071
#define IDC_SELTV                       1072
#define IDC_INFOTFO                     1073
#define IDC_SEPTAUXSIMUL                1074
#define IDC_TAUXSIMUL                   1075
#define IDC_INFOEDI                     1076
#define IDC_EDIT_CODE                   1078
#define IDC_EDIT_TYPE                   1079
#define IDC_EDIT_TYPECODE               1080
#define IDC_EDIT_NOM                    1081
#define IDC_EDIT_ADR1                   1082
#define IDC_EDIT_ADR2                   1083
#define IDC_EDIT_CODEPOSTAL             1084
#define IDC_COMBO_PAYS                  1085
#define IDC_EDIT_VILLE                  1086
#define IDC_EDIT_NOMCONTACT             1087
#define IDC_EDIT_PRENOMCONTACT          1088
#define IDC_EDIT_ADRMAILCONTACT         1089
#define IDC_OBLIG1                      1090
#define IDC_OBLIG2                      1091
#define IDC_OBLIG3                      1092
#define IDC_OBLIG4                      1093
#define IDC_OBLIG5                      1094
#define IDC_EDIT_NOTEL                  1095
#define IDC_AJOUTER                     1095
#define IDC_EDIT_NOFAX                  1096
#define IDC_MODIFIER                    1096
#define IDC_SUPPRIMER                   1097
#define IDC_PREC_CONTACT                1097
#define IDC_SUIV_CONTACT                1098
#define IDC_LIST_TIERSEDI               1098
#define IDC_SUPP_CONTACT                1099
#define IDC_ADD_CONTACT                 1100
#define IDC_CADRECONTACT                1101
#define IDC_EDIT_CODE2                  1102
#define IDC_EDIT_CODE_GLN               1102
#define ID_MENUNOMENCL_AJOUTERNVLLEBRANCHE 32771
#define ID_MENUNOMENCL_RENOMMERBRANCHE  32772
#define ID_MENUNOMENCL_SUPPRIMERBRANCHE 32773
#define ID_MENUNOMENCL_COUPERBRANCHE    32774
#define ID_MENUNOMENCL_COLLERBRANCHE    32775
#define ID_MENUNOMENCL_INFOPRODUIT      32776
#define ID_INFOS_APROPOSDENOMENCLATURE  32781
#define ID_FILE_PRINTBIS                32782
#define ID_ANNE_NOUVELLE                32785
#define ID_ANNE_DUPLIQUER               32788
#define ID_MENUNOMENCL_AJOUTERANNONCEURSANSGROUPE 32789
#define ID_MENUNOMENCL_AJOUTERANNONCEURSANSGROUPESANSPRODUIT 32790
#define ID_MENUNOMENCL_TAUX             32791
#define ID_UTILTAUX                     32792
#define ID_REGIES                       32793
#define ID_CENTRALESDACHAT              32794
#define ID_MENU_DYN_FIRST               40000
#define ID_MENU_DYN_LAST                40099

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
