#pragma once

enum CALCULATE
{
	CALC_UNIVERSE		=	1,
	CALC_CIBLES			=	CALC_UNIVERSE<<1,
	CALC_ROWS			=	CALC_CIBLES<<1,
	CALC_ROWSIZE		=	CALC_ROWS<<1,
	CALC_COLS			=	CALC_ROWSIZE<<1,
	CALC_COLSIZE		=	CALC_COLS<<1,
	CALC_PAGES			=	CALC_COLSIZE<<1,
	CALC_PAGESIZE		=	CALC_PAGES<<1,
	CALC_CELLS			=	CALC_PAGESIZE<<1,
	CALC_SURLIGNAGE		=	CALC_CELLS<<1,
	CALC_SORT			=	CALC_SURLIGNAGE<<1,
	CALC_GRIDUPDATE		=	CALC_SORT<<1,
	CALC_TRANSPOSE		=	CALC_GRIDUPDATE<<1,
};

enum RESULTSTYLE
{
	/*
	RSTYLE_NOSTYLE				=	0,
	RSTYLE_RESULT				=	1,
	RSTYLE_HORZ_STRUCTURE		=	RSTYLE_RESULT<<1,

	// RSTYLE_HORIZONTAL			=	RSTYLE_HORZ_STRUCTURE

	RSTYLE_HORZ_CORRELATION		=   RSTYLE_HORZ_STRUCTURE<<1,
	RSTYLE_HORIZONTAL			=	RSTYLE_HORZ_STRUCTURE|RSTYLE_HORZ_CORRELATION,
	RSTYLE_VERT_STRUCTURE		=	RSTYLE_HORZ_CORRELATION<<1,

	// RSTYLE_VERT_STRUCTURE		=	RSTYLE_HORZ_STRUCTURE<<1,

	RSTYLE_VERTICAL				=	RSTYLE_VERT_STRUCTURE,
	RSTYLE_GBL_STRUCTURE		=	RSTYLE_VERT_STRUCTURE<<1,
	RSTYLE_GBL_CORRELATION		=	RSTYLE_GBL_STRUCTURE<<1,
	RSTYLE_GBL_PROXIMITY		=	RSTYLE_GBL_CORRELATION<<1,
	RSTYLE_GBL_ZSCORE			=	RSTYLE_GBL_PROXIMITY<<1,
	RSTYLE_GLOBAL				=	RSTYLE_GBL_STRUCTURE|RSTYLE_GBL_CORRELATION|RSTYLE_GBL_PROXIMITY|RSTYLE_GBL_ZSCORE,
	RSTYLE_CIBLES				=	RSTYLE_GBL_ZSCORE<<1,
	*/

	RSTYLE_NOSTYLE				=	0,
	RSTYLE_RESULT				=	1,
	RSTYLE_HORZ_STRUCTURE		=	RSTYLE_RESULT<<1,

	// RSTYLE_HORIZONTAL			=	RSTYLE_HORZ_STRUCTURE

	RSTYLE_HORZ_CORRELATION		=   RSTYLE_HORZ_STRUCTURE<<1,
	RSTYLE_HORIZONTAL			=	RSTYLE_HORZ_STRUCTURE|RSTYLE_HORZ_CORRELATION,
	RSTYLE_VERT_STRUCTURE		=	RSTYLE_HORZ_CORRELATION<<1,

	// RSTYLE_VERT_STRUCTURE		=	RSTYLE_HORZ_STRUCTURE<<1,

	RSTYLE_VERTICAL				=	RSTYLE_VERT_STRUCTURE,
	RSTYLE_GBL_STRUCTURE		=	RSTYLE_VERT_STRUCTURE<<1,
	RSTYLE_GBL_CORRELATION		=	RSTYLE_GBL_STRUCTURE<<1,
	RSTYLE_GBL_PROXIMITY		=	RSTYLE_GBL_CORRELATION<<1,
	RSTYLE_GBL_ZSCORE			=	RSTYLE_GBL_PROXIMITY<<1,
	RSTYLE_GLOBAL				=	RSTYLE_GBL_STRUCTURE|RSTYLE_GBL_CORRELATION|RSTYLE_GBL_PROXIMITY|RSTYLE_GBL_ZSCORE,
	RSTYLE_CIBLES				=	RSTYLE_GBL_ZSCORE<<1,
};

enum TABLESTYLE
{
	TSTYLE_UNIVERSEX			=	1,
	TSTYLE_NICHER				=	TSTYLE_UNIVERSEX<<1,
	TSTYLE_NICHEC				=	TSTYLE_NICHER<<1,
	TSTYLE_NICHEP				=	TSTYLE_NICHEC<<1,
	TSTYLE_NICHEX				=	TSTYLE_NICHER|TSTYLE_NICHEC|TSTYLE_NICHEP,
	TSTYLE_ITEMSR				=	TSTYLE_NICHEP<<1,
	TSTYLE_ITEMSC				=	TSTYLE_ITEMSR<<1,
	TSTYLE_ITEMSP				=	TSTYLE_ITEMSC<<1,
	TSTYLE_ITEMSX				=	TSTYLE_ITEMSR|TSTYLE_ITEMSC|TSTYLE_ITEMSP,
	TSTYLE_ITEMMOYENR			=	TSTYLE_ITEMSP<<1,
	TSTYLE_ITEMMOYENC			=	TSTYLE_ITEMMOYENR<<1,
	TSTYLE_ITEMMOYENP			=	TSTYLE_ITEMMOYENC<<1,
	TSTYLE_ITEMMOYENX			=	TSTYLE_ITEMMOYENR|TSTYLE_ITEMMOYENC|TSTYLE_ITEMMOYENP,
	TSTYLE_CONTRENICHER			=	TSTYLE_ITEMMOYENP<<1,
	TSTYLE_CONTRENICHEC			=	TSTYLE_CONTRENICHER<<1,
	TSTYLE_CONTRENICHEP			=	TSTYLE_CONTRENICHEC<<1,
	TSTYLE_CONTRENICHEX			=	TSTYLE_CONTRENICHER|TSTYLE_CONTRENICHEC|TSTYLE_CONTRENICHEP,
	TSTYLE_EXCLUSIVE			=	TSTYLE_CONTRENICHEP<<1,
	TSTYLE_DUPLIQUE				=	TSTYLE_EXCLUSIVE<<1,
	TSTYLE_TERRAINCOL			=	TSTYLE_DUPLIQUE<<1,
	TSTYLE_GRANDEURCOL			=	TSTYLE_TERRAINCOL<<1,
	TSTYLE_ORDONNERON			=	TSTYLE_GRANDEURCOL<<1,
	TSTYLE_ORDONNERPAGE			=	TSTYLE_ORDONNERON<<1,
	TSTYLE_ORDONNERFORTE		=	TSTYLE_ORDONNERPAGE<<1, // No longer used
	TSTYLE_ORDONNER				=	TSTYLE_ORDONNERON|TSTYLE_ORDONNERPAGE,
};

enum CLICKMODE
{
	CMODE_TRI				=	1,
	CMODE_ORDONNER			=	CMODE_TRI<<1,
	CMODE_BASE100			=	CMODE_ORDONNER<<1,
	CMODE_HASMODE			=	CMODE_TRI|CMODE_ORDONNER|CMODE_BASE100,
};

enum CELLTYPE
{
	CTYPE_HEADER1				=	0,	// IS A QUESTION HEADER
	CTYPE_HEADER2,						// IS AN ITYPE_ITEM HEADER
	CTYPE_HEADERCALC,					// IS A CALC HEADER
	CTYPE_HEADERTERRAIN,				// IS A TERRAIN HEADER
	CTYPE_ITEMCELL,						// IS AN ITYPE_ITEM CELL
	CTYPE_ERROR,
};

enum RESULTTYPE
{
	RTYPE_NOTYPE				=   0,
	RTYPE_EFFECTIVE_000			=	1,
	RTYPE_NBCAS					=	RTYPE_EFFECTIVE_000<<1,
	RTYPE_QUANTITY_000			=	RTYPE_NBCAS<<1,
	RTYPE_AVERAGEQUANTUM		=	RTYPE_QUANTITY_000<<1,
	RTYPE_PENETRATION			=	RTYPE_AVERAGEQUANTUM<<1,
	RTYPE_CENTRAGE				=	RTYPE_PENETRATION<<1,
	RTYPE_EFFECTIVE_CIBLE		=	RTYPE_CENTRAGE<<1,
	RTYPE_CONCOMITENCE			=	RTYPE_EFFECTIVE_CIBLE<<1,
	RTYPE_COEFFYULE				=	RTYPE_CONCOMITENCE<<1,
	RTYPE_EFFECTIVE_NONCIBLE	=	RTYPE_COEFFYULE<<1,
	RTYPE_AVERAGEQUANTUM_P00	=	RTYPE_EFFECTIVE_NONCIBLE<<1,
	RTYPE_ZSCORE				=   RTYPE_AVERAGEQUANTUM_P00<<1,
};

enum ITEMTYPE
{
	ITYPE_UNIVERSE		=	1,
	ITYPE_NICHE			=	ITYPE_UNIVERSE<<1,
	ITYPE_ITEM			=	ITYPE_NICHE<<1,
	ITYPE_CONTRENICHE	=	ITYPE_ITEM<<1,
	ITYPE_EXCLUSIVE		=	ITYPE_CONTRENICHE<<1,
	ITYPE_MOYEN			=	ITYPE_EXCLUSIVE<<1,
};

enum DATATYPE
{
	DTYPE_ITEMS				=	1,
	DTYPE_SITES				=	DTYPE_ITEMS<<1,
};

