//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AnalyseurExt.rc
//
#define IDC_AN_BUT_TERRAIN_DOWN         2305
#define IDC_AN_BUT_TERRAIN_UP           2306
#define IDM_AN_ABOUTBOX                 4000
#define IDM_AN_PALETTE_1                4001
#define IDM_AN_PALETTE_2                4002
#define IDM_AN_PALETTE_3                4003
#define IDM_AN_PALETTE_4                4004
#define IDM_AN_PALETTE_5                4005
#define IDM_AN_PALETTE_6                4006
#define IDR_AN_MENU                     4007
#define IDM_AN_PALETTE_7                4008
#define IDM_AN_PALETTE_8                4009
#define IDM_AN_PALETTE_9                4010
#define IDM_AN_PALETTE_10               4011
#define IDD_AN_ABOUTBOX                 4012
#define IDI_AN_ICON                     4013
#define IDD_AN_DLG_ANALYSEUR            4014
#define IDS_AN_NICHE                    4015
#define IDS_AN_REPONDANTS               4016
#define IDS_AN_GLISSE                   4018
#define IDS_AN_ABR_EFFECTIVE            4019
#define IDS_AN_ITEMDUPLIQUANT           4020
#define IDS_AN_CTRL_INDEXDROPDOWNLIST   4021
#define IDS_AN_LINE                     4022
#define IDS_AN_COLUMN                   4023
#define IDS_AN_ABR_NBCAS                4024
#define IDS_AN_AVERAGEQUANTUM           4025
#define IDS_AN_CENTRAGE                 4026
#define IDS_AN_EFFECTIVE                4027
#define IDS_AN_NBCAS                    4028
#define IDS_AN_PENETRATION              4029
#define IDS_AN_QUANTITY                 4030
#define IDS_AN_TITRE_CHOISIR_UNIVERS    4031
#define IDS_AN_CONTRENICHE              4032
#define IDS_AN_ITEMEXCLUSIVE            4033
#define IDS_AN_ITEMMOYEN                4034
#define IDM_AN_PALETTE_11               4035
#define IDS_AN_ABR_GLOBAL               4036
#define IDS_AN_ABR_QUANTITY             4037
#define IDD_AN_DLG_CIBLE                4038
#define IDS_AN_ABR_CORRELATION          4039
#define IDS_AN_ABR_AVERAGEQUANTUM       4040
#define IDD_AN_DLG_SRC_UNIQUE           4041
#define IDS_AN_ABR_PROXIMITY            4042
#define IDS_AN_ABR_PENETRATION          4043
#define IDS_AN_SITES                    4044
#define IDS_AN_ABR_CENTRAGE             4045
#define IDS_AN_ABR_EFFECTIVEBRUT        4046
#define IDS_AN_EFFECTIVEBRUT            4047
#define IDS_AN_CONCOMITENCE             4048
#define IDS_AN_COEFFYULE                4049
#define IDD_AN_DLG_PARAMS               4050
#define IDS_AN_APPNAME                  4051
#define IDS_AN_ABR_CONCOMITENCE         4052
#define IDS_AN_TITRE_CHOISIR_CIBLES     4053
#define IDS_AN_ABR_COEFFYULE            4054
#define IDS_AN_NONAME                   4055
#define IDS_AN_LABEL_UNIVERS            4056
#define IDS_AN_NICHECIBLE               4057
#define IDS_AN_MENU_CHOISIR_UNIVERS     4058
#define IDS_AN_MENU_CHOISIR_CIBLES      4059
#define IDI_AN_CHECKOFF                 4060
#define IDS_AN_ZSCORE                   4061
#define IDS_AN_CORRELATION              4062
#define IDI_AN_CHECKON                  4063
#define IDS_AN_ABR_ZSCORE               4064
#define IDS_AN_PROXIMITY                4065
#define IDI_AN_RADIOOFF                 4066
#define IDS_AN_INDAFFINITE              4067
#define IDS_AN_SAVETABLEAU              4068
#define IDI_AN_RADIOON                  4069
#define IDS_AN_ABR_INDAFFINITE          4070
#define IDI_AN_RADIOON1                 4071
#define IDS_AN_PAGE                     4072
#define IDI_AN_RADIOOFF1                4073
#define IDS_AN_RESULTAT                 4074
#define IDM_AN_RESULTATS                4075
#define IDS_AN_MESS_SELQULIGNE          4076
#define IDS_AN_LABEL_CIBLES             4077
#define IDS_AN_MESS_SELQUCOL            4078
#define IDS_AN_MESS_SELQUPAGE           4079
#define IDD_AN_DLG_SURLIGNAGE           4080
#define IDS_AN_LABEL_GRANDEUR           4081
#define IDR_AN_MENU_GLOBAL              4082
#define IDD_AN_DLG_SITE                 4083
#define IDS_AN_AVERAGEQUANTUM_P00       4084
#define IDS_AN_ABR_AVERAGEQUANTUM_P00   4085
#define IDS_AN_ABR_NOTHING              4086
#define IDB_AN_MULTISEL                 4087
#define IDS_AN_MESS_AUCUN_ITEM_IDENT    4088
#define IDB_AN_EXPORT_SURLIGN           4089
#define IDS_AN_LABEL_GLOBAL             4090
#define IDS_AN_LABEL_INDICE_PROXIMITE   4091
#define IDS_AN_LABEL_INDICE_CORRELATION 4092
#define IDS_AN_LABEL_INDICE_STRUCTURE   4093
#define IDS_AN_LABEL_H_CORRELATION      4094
#define IDS_AN_LABEL_H_STRUCTURE        4095
#define IDS_AN_ABR_HORIZ                4096
#define IDS_AN_ABR_VERT                 4097
#define IDS_AN_NON_DEFINI               4098
#define IDI_ICON1                       4099
#define IDC_AN_BASE100                  4100
#define IDC_AN_EXCL                     4101
#define IDC_AN_EXCL1                    4102
#define IDC_AN_DUP                      4103
#define IDB_AN_PUPITRE                  4104
#define IDC_AN_EFFACER_TOUS             4105
#define IDC_AN_EFFACER_LIGNES           4106
#define IDC_AN_EFFACER_COLONNES         4107
#define IDC_AN_TRI                      4108
#define IDI_AN_UNDO                     4108
#define IDD_AN_DLG_PARAMS_SURLIGN       4109
#define IDC_AN_EFFACER_PAGES            4110
#define IDC_AN_QUANTITY                 4111
#define IDC_AN_COMBO_SOURCE             4112
#define IDI_ICON2                       4112
#define IDI_AN_RAZ                      4112
#define IDC_AN_LIST_TERRAIN             4113
#define IDC_AN_STATIC_BOX               4114
#define IDC_AN_STATIC_SOURCE            4115
#define IDC_AN_BOX_CONFIG               4116
#define IDC_AN_GRID_TITLE               4117
#define IDC_AN_BOX_COLUMN               4118
#define IDC_AN_BOX_GRID                 4119
#define IDC_AN_BOX_PAGE                 4120
#define IDC_AN_LABEL_TERRAINS           4121
#define IDC_AN_LABEL_CIBLES             4122
#define IDC_AN_LABEL_GRANDEURS          4123
#define IDC_AN_LABEL_TABLEAU            4124
#define IDC_AN_LIST_TERRAINS            4125
#define IDC_AN_LIST_CIBLES              4126
#define IDC_AN_LIST_GRANDEURS           4127
#define IDC_AN_LABEL_MARQUAGE           4128
#define IDC_AN_BUT_VECTORIELLE          4129
#define IDC_AN_LABEL_TRI                4130
#define IDC_AN_BUT_COLUMN               4131
#define IDC_AN_LIST_TERRAINS2           4131
#define IDC_AN_LABEL_RESULT             4132
#define IDC_AN_BUT_ORDONNER             4134
#define IDC_AN_BUT_COLUMN_SITE          4135
#define IDC_AN_BUT_PAGE                 4136
#define IDC_AN_BUT_GRANDEUR             4137
#define IDC_AN_BUT_BASE100              4138
#define IDC_AN_BUT_PAGE2                4139
#define IDC_AN_BUT_BASE101              4140
#define IDC_AN_BUT_PARAMSURLIGNAGE      4141
#define IDC_AN_STATIC_V                 4142
#define IDC_AN_BUT_HORIZ                4143
#define IDC_AN_BUT_PAGE_SITE            4144
#define IDC_AN_STATIC_C                 4145
#define IDC_AN_BUT_VERT                 4146
#define IDC_AN_STATIC_I                 4147
#define IDC_AN_BUT_GLOBAL               4148
#define IDC_AN_LIST_COLUMN              4149
#define IDC_AN_BUT_EXCLU                4150
#define IDC_AN_LIST_PAGE                4151
#define IDC_AN_BUT_DUPLI                4152
#define IDC_AN_BUT_LINE                 4153
#define IDC_AN_BUT_GRANDEUR3            4154
#define IDC_AN_BOX_LINE                 4155
#define IDC_AN_BUT_HORIZ3               4156
#define IDC_AN_LIST_LINE                4157
#define IDC_AN_BUT_VERT3                4158
#define IDC_AN_BUT_SORTLINE             4159
#define IDC_AN_BUT_GLOBAL3              4160
#define IDC_AN_TABLE                    4161
#define IDC_AN_BUT_LINE2                4162
#define IDC_AN_BUT_SORTCOLUMN           4163
#define IDC_AN_BUT_GRANDEUR2            4164
#define IDC_AN_BUT_SORTPAGE             4165
#define IDC_AN_BUT_HORIZ2               4166
#define IDC_AN_LIST_SELCIBLE            4167
#define IDC_AN_BUT_LINE_SITE            4168
#define IDC_AN_BUT_VERT2                4169
#define IDC_AN_LIST_POIDS               4170
#define IDC_AN_BUT_GLOBAL2              4171
#define IDC_AN_LIST_SEGMENT             4172
#define IDC_AN_STATIC_TTLPOIDS          4173
#define IDC_AN_STATIC_TTLSEGMENT        4174
#define IDC_AN_STATIC_TTLSOURCE         4175
#define IDC_AN_STATIC_TTLTERRAIN        4176
#define IDC_AN_STATIC_BASE100           4177
#define IDC_AN_STATIC_TTLBASE100        4178
#define IDC_AN_BASE_UNIVERS             4179
#define IDC_AN_BASE_NICHE               4180
#define IDC_AN_STATIC_OPTIONS           4181
#define IDC_AN_STATIC_TTLOPTIONS        4182
#define IDC_AN_OPTION_NICHE             4183
#define IDC_AN_OPTION_CONTRENICHE       4184
#define IDC_AN_OPTION_ITEMMOYEN         4185
#define IDC_AN_OPTION_ITEMS             4186
#define IDC_AN_STATIC_TTLOPTIONS2       4187
#define IDC_AN_OPTION_NICHE2            4188
#define IDC_AN_OPTION_CONTRENICHE2      4189
#define IDC_AN_OPTION_ITEMMOYEN2        4190
#define IDC_AN_OPTION_ITEMS2            4191
#define IDC_AN_STATIC_TTLOPTIONS3       4192
#define IDC_AN_OPTION_NICHE3            4193
#define IDC_AN_OPTION_CONTRENICHE3      4194
#define IDC_AN_OPTION_ITEMMOYEN3        4195
#define IDC_AN_OPTION_ITEMS3            4196
#define IDC_AN_STATIC_TTLGRANDEURS      4197
#define IDC_AN_GRANDEUR_LIGNE           4198
#define IDC_AN_GRANDEUR_COLONNE         4199
#define IDC_AN_STATIC_TTLTERRAINS       4200
#define IDC_AN_TERRAIN_LIGNE            4201
#define IDC_AN_TERRAIN_COLONNE          4202
#define IDC_AN_STATIC_TTLSURLIGNAGE     4203
#define IDC_AN_SURLIGNAGE_PAGE          4204
#define IDC_AN_SURLIGNAGE_GLOBAL        4205
#define IDC_AN_STATIC_RESULTS           4206
#define IDC_AN_STATIC_TTLREPONDANTS     4207
#define IDC_AN_REP_TOUS                 4208
#define IDC_AN_REP_EXCLUSIFS            4209
#define IDC_AN_REP_DUPLIQ               4210
#define IDC_AN_REP_RIEN                 4211
#define IDC_AN_STATIC_TTLVERTICAL       4212
#define IDC_AN_VERT_STRUCTURE           4213
#define IDC_AN_VERT_RIEN                4214
#define IDC_AN_STATIC_TTLHORIZONTAL     4215
#define IDC_AN_HORZ_STRUCTURE           4216
#define IDC_AN_HORZ_RIEN                4217
#define IDC_AN_STATIC_TTLGLOBAL         4218
#define IDC_AN_STATIC_TTLCIBLE          4219
#define IDC_AN_GLOB_STRUCTURE           4220
#define IDC_AN_GLOB_CORRELATION         4221
#define IDC_AN_GLOB_PROXIMITY           4222
#define IDC_AN_GLOB_RIEN                4223
#define IDC_AN_STATIC_CIBLE             4224
#define IDC_AN_PROGRESS                 4225
#define IDC_AN_LABEL1                   4226
#define IDC_AN_LIST_ITEMS1              4227
#define IDC_AN_STATIC_BOX1              4228
#define IDC_AN_BUT_EXIT1                4229
#define IDC_AN_STATIC_SITE              4230
#define IDC_AN_STATIC_TTLSITE           4231
#define IDC_AN_LIST_SITES               4232
#define IDC_AN_EDIT_SEARCH              4233
#define IDC_AN_ALL_SITES                4234
#define IDC_AN_BUT_EXPORT               4235
#define IDC_COMBO_TRI_GRANDEURS         4236
#define IDC_AN_NO_SITE                  4237
#define IDC_COMBO_TRI_RESULTATS         4238
#define IDC_AN_NOSEL_SITE               4239
#define IDC_COMBO_TYPETRI               4240
#define IDM_AN_PALETTE_12               4241
#define IDC_COMBO_MODETRI               4242
#define IDM_AN_TRI_GRANDEUR             4243
#define IDM_AN_TRI_HORZ                 4244
#define IDM_AN_TRI_VERT                 4245
#define IDM_AN_TRI_IC                   4246
#define IDM_AN_TRI_CROISSANT            4247
#define IDM_AN_TRI_DECROISSANT          4248
#define IDM_AN_TRI_ANNULE               4249
#define IDM_AN_TRI_GLOBAL               4250
#define IDM_AN_TRI_BLOCQUESTION         4251
#define IDD_AN_DLG_PARAMS_TRI           4252
#define IDC_AN_STATIC_ORDRE_TRI         4253
#define IDC_AN_STATIC_GRANDEUR_TRI      4254
#define IDC_AN_STATIC_RESULT_TRI        4255
#define IDC_AN_STATIC_NATURE_TRI        4256
#define IDC_AN_STATIC_TTL_ORDRETRI      4257
#define IDC_AN_STATIC_TTL_GRANDEURTRI   4258
#define IDC_AN_STATIC_TTL_RESULTTRI     4259
#define IDC_AN_STATIC_TTL_NATURETRI     4260
#define IDC_AN_RAD_CROISSANT            4261
#define IDC_AN_RAD_DECROISSANT          4262
#define IDC_AN_RAD_AUCUNTRI             4263
#define IDC_AN_RAD_GLOBAL               4264
#define IDC_AN_RAD_PARBLOC              4265
#define IDC_AN_LIST_TRI_RESULTATS       4266
#define IDC_AN_LIST_TRI_GRANDEURS       4267
#define IDC_AN_STATIC_OBJETS_SURLIGN    4268
#define IDC_AN_STATIC_TTL_RES_SURLIGN   4269
#define IDC_AN_STATIC_TTL_GRD_SURLIGN   4270
#define IDC_AN_COMBO_RES_SURLIGN        4271
#define IDC_AN_COMBO_GRD_SURLIGN        4272
#define IDC_AN_STATIC_VAL_SURLIGN       4273
#define IDC_AN_STATIC_TTL_VAL_SURLIGN   4274
#define IDC_AN_RAD_SUP                  4275
#define IDC_AN_RAD_SUPEGAL              4276
#define IDC_AN_RAD_INF                  4277
#define IDC_AN_RAD_INFEGAL              4278
#define IDC_AN_RAD_BORNEINF             4279
#define IDC_AN_EDIT_VALEUR_SURLIGN      4280
#define IDC_AN_EDIT_BORNEINF_SURLIGN    4281
#define IDC_AN_STATIC_ENTRE_BORNES      4282
#define IDC_AN_EDIT_BORNESUP_SURLIGN    4283
#define IDC_AN_CHK_OUTBORNES            4284
#define IDC_AN_STATIC_COULEUR_SURLIGN   4285
#define IDC_AN_STATIC_TTL_COULEUR       4286
#define IDC_AN_CADRE_COULEUR            4287
#define IDC_AN_MODIF_COULEUR            4288
#define IDC_AN_DEFDEFAUT                4289
#define IDC_AN_EFFACER_DEFDEFAUT        4290
#define ID_AN_OK_SURLIGN                4291
#define ID_AN_CANCEL_SURLIGN            4292
#define IDC_AN_EFFACER_DEFDEFAUT2       4293
#define IDC_AN_SET_PARAM_DEFAUT         4294
#define IDC_AN_STATIC_TTL_COULEUR2      4295
#define IDC_RADIO1                      4296
#define IDC_AN_PRCT_BORNEINF            4297
#define IDC_AN_PRCT_BORNESUP            4298
#define IDC_AN_PRCT_VALEUR              4299
#define IDC_BUTTON1                     4300
#define IDC_AN_BUT_RAZ_SURLIGN          4300
#define IDC_AN_BUT_PREC_SURLIGN         4301
#define IDC_AN_STATIC_CONFIG_DEFAUT     4303
#define IDC_AN_STATIC_TTL_CONFIGDEF     4304
#define IDC_AN_STATIC_CADRE_VAL_SURLIGN 4305
#define IDC_AN_STATIC_CADRE_BORNES_SURLIGN 4306
#define IDC_AN_BUT_MOYENNE_TABLEAU      4307
#define IDC_AN_LABEL_VAR_MOY            4308
#define IDC_AN_LIST_VAR_MOY             4309
#define IDC_AN_BUT_RAZ_VAR_MOY          4310
#define IDC_INFO_FILIGRAMME             4311
#define IDC_INFO_TEXT_FILIGRAMME        4312
#define IDM_AN_PALETTE_13               4313
#define IDM_AN_PALETTE_14               4314
#define IDM_AN_PALETTE_15               4315
#define IDS_AN_INDGLOBAL                4316
#define ID_TABLEAU_EXPORTER             32771
#define IDM_AN_GLOBAL_STRUCTURE         32782
#define IDM_AN_GLOBAL_AFFINITE          32783
#define IDM_AN_GLOBAL_PROXIMITY         32784
#define IDM_AN_TABLEAU_APPLIQUER_CANEVAS 32799
#define IDM_AN_TABLEAU_ENREGISTRER_CANEVAS 32800
#define IDM_AN_TABLEAU_EXPORTER_PRESSEPAPIER 32801
#define IDM_AN_TABLEAU_EXPORTER_FICHIER 32802
#define IDM_AN_TABLEAU_IMPRIMER         32803
#define IDM_AN_TABLEAU_TRANSPOSER       32804
#define IDM_AN_TABLEAU_MODIFIER         32805
#define IDM_AN_TABLEAU_QUITTER          32808
#define IDM_AN_PARAMETRES_DEFINIR_STRUCTURE_TABLEAU 32812
#define IDM_AN_PARAMETRES_INTERPRETER_UNIVERS_COMME_CIBLE 32813
#define IDM_AN_SOURCE_CHOISIR_TERRAINS  32814
#define IDM_AN_SOURCE_CHOISIR_UNIVERS   32817
#define IDM_AN_GLOBAL_ZSCORE            32823
#define IDM_AN_PARAMETRES_PRISE_EN_COMPTE_MARGERREUR 32825
#define ID_AN_PARAM_DUPLICANTS          32829
#define ID_AFFICHAGE_DISPOSITIONR       32830
#define IDM_AN_DISPO_LIGNES             32833
#define IDM_AN_DISPO_2PAR2              32834
#define IDM_AN_DISPO_COLONNES           32836
#define ID_AN_PARAM_EXCLUSIFS           32837
#define ID_AN_PARAM_BASE100             32839
#define IDM_AN_OUTILS_LINEARISATION     32842
#define IDM_AN_OUTILS_SURLIGNAGE        32843
#define ID_TABLEAU_EXPORTERVERSEXCEL    32844
#define IDM_AN_TABLEAU_EXPORTER_EXCEL   32845
#define ID_PARAM32846                   32846
#define ID_MODEMOYENNE_MOYENNESURL      32847
#define ID_MODEMOYENNE_MOYENNESURLESLIGNES 32848
#define ID_AN_PARAM_MOYENNE_TABLEAU     32849
#define ID_AN_PARAM_MOYENNE_LIGNE       32850
#define ID_DDDD_TEST                    32851
#define ID_PARAM32852                   32852
#define ID_PARAM32853                   32853
#define ID_AFFICHAGEEFFECTIF_ENMILLIERS 32854
#define ID_AFFICHAGEMOYENNE_AVEC2D32855 32855
#define ID_AFFICHAGEMOYENNE_SANSD32856  32856
#define ID_AFFICHAGEEFFECTIF_GLOBAL     32857
#define ID_AN_PARAM_AFFICH_EFFECTIF_MILLIERS 32858
#define ID_AN_PARAM_AFFICH_EFFECTIF_GLOBAL 32859
#define ID_AN_PARAM_AFFICH_MOYENNE_2DEC 32860
#define ID_AN_PARAM_AFFICH_MOYENNE_SANSDEC 32861
#define ID_PARAM32862                   32862
#define ID_AN_PARAM_MOYENNE_0_INCLUS    32863
#define ID_AN_PARAM_MOYENNE_0_EXCLUS    32864
#define ID_PARAM32867                   32867
#define ID_SSSSSS_SSSSSS                32868
#define ID_PARAM32869                   32869
#define ID_PARAM32870                   32870
#define ID_MODEMOYENNE_MOYENNESURLESCOLONNES 32871
#define ID_AN_PARAM_MOYENNE_COLONNE     32872
#define ID_TABLEAU_MODIFIERTABLEAU      32873
#define ID_PARAM32874                   32874
#define ID_INDICE_INDICEAFFINIT32875    32875
#define ID_INDICE_POURCENTAGEGLOBAL     32876
#define ID_INDICE_INDICEDEPROXIMIT32877 32877
#define ID_AN_PARAM_INDICE_AFFINITE     32878
#define ID_AN_PARAM_INDICE_PRCTGLOBAL   32879
#define ID_AN_PARAM_INDICE_PROXIMITE    32880
#define ID_EXPORTERVERSEXCEL_AVECDECOUPAGE 32881
#define ID_EXPORTERVERSEXCEL_SANSD32882 32882
#define IDM_AN_TABLEAU_EXPORTER_EXCEL_AVECDECOUP 32883
#define IDM_AN_TABLEAU_EXPORTER_EXCEL_SANSDECOUP 32884
#define ID_PARAM32885                   32885
#define IDM_AN_PARAMETRES_FORCE_QUANTI  32886

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4113
#define _APS_NEXT_COMMAND_VALUE         32887
#define _APS_NEXT_CONTROL_VALUE         4308
#define _APS_NEXT_SYMED_VALUE           4400
#endif
#endif
