//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by admin.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MODIFCMPLX                  101
#define IDR_MAINFRAME                   128
#define IDR_ADMINTYPE                   129
#define IDD_AJOUTCMPLX                  130
#define IDD_SUPPCMPLX                   131
#define IDD_AJOUTBAC                    132
#define IDD_MODIFBAC                    133
#define IDD_SUPPBAC                     134
#define IDD_AJOUTPRODUIT                135
#define IDD_SELBAC                      136
#define IDD_SELCOMPLEXE                 137
#define IDD_MODIFPRODUIT                138
#define IDD_SUPPPRODUIT                 139
#define IDD_AJOUTTEMPO                  140
#define IDD_AJOUTFORMAT                 141
#define IDD_SUPPFORMAT                  142
#define IDD_SUPPTEMPO                   143
#define IDD_MODIFTEMPO                  144
#define IDD_MODIFCHEMIN                 145
#define IDD_SELPRODUIT                  146
#define IDD_EDITMODIFTARIF              149
#define IDC_CURSOR1                     150
#define IDD_MODIFCNC                    151
#define IDD_LISTE_BACS                  152
#define IDD_AJOUT_COMPLEXE_GROUPE       153
#define IDD_AJOUT_BAC_GROUPE            154
#define IDD_SUPPBAC_GROUPE              156
#define IDD_SUPPCMPLX_GROUPE            157
#define IDI_MAINFRAME                   183
#define IDC_LISTCOMPLEXE                1000
#define IDC_OK                          1001
#define IDC_ANNULER                     1002
#define IDC_LIBCOMPLEXE                 1003
#define IDC_CODECOMPLEXE                1004
#define IDC_LABELLIB                    1006
#define IDC_LABELCODE                   1007
#define IDC_coeff                       1007
#define IDC_LABELCODEBAC                1008
#define IDC_COMBOBAC                    1009
#define IDC_COMBOCOMPO                  1010
#define IDC_LIBBAC                      1011
#define IDC_CODEBAC                     1012
#define IDC_LISTBAC                     1013
#define IDC_CADRE2                      1017
#define IDC_DUREE                       1018
#define IDC_LIBPRODUIT                  1019
#define IDC_CODEPRODUIT                 1020
#define IDC_COMPOPRODUIT                1022
#define IDC_SEMAINE                     1023
#define IDC_COMPOCMPLX                  1024
#define IDC_COMPOBAC                    1025
#define IDC_AJOUTCOMPLEXE               1026
#define IDC_AJOUTBAC                    1027
#define IDC_SUPP                        1028
#define IDC_COMBODUREE                  1029
#define IDC_LISTPRODUIT                 1030
#define ID_LIBTEMPO                     1031
#define IDC_NOM                         1032
#define IDC_PERIODE                     1033
#define IDC_PATRON                      1034
#define IDC_COMBOPERIODE                1037
#define IDC_SEMAINES                    1038
#define IDC_PASSAGE11                   1039
#define IDC_PASSAGE12                   1040
#define IDC_PASSAGE22                   1041
#define IDC_PASSAGE21                   1042
#define IDC_PASSAGE31                   1043
#define IDC_PASSAGE41                   1044
#define IDC_PASSAGE32                   1045
#define IDC_PASSAGE42                   1046
#define IDC_PASSAGE51                   1047
#define IDC_PASSAGE61                   1048
#define IDC_PASSAGE52                   1049
#define IDC_PASSAGE62                   1050
#define IDC_PASSAGE71                   1051
#define IDC_LIBFORMAT                   1052
#define IDC_PASSAGE72                   1052
#define IDC_COEFFFORMAT                 1053
#define IDC_PASSAGE102                  1053
#define IDC_PASSAGE92                   1054
#define IDC_PASSAGE91                   1055
#define IDC_PASSAGE81                   1056
#define IDC_PASSAGE101                  1057
#define IDC_PASSAGE82                   1058
#define IDC_CADRE                       1059
#define IDC_TEMPO                       1060
#define IDC_LISTTEMPO                   1061
#define IDC_LISTFORMAT                  1063
#define IDC_LABELCHEMIN                 1064
#define IDC_CHEMIN                      1065
#define IDC_LABELREGIE                  1066
#define IDC_COMBOREGIE                  1067
#define IDC_SUPP2                       1070
#define IDC_TYPECOMBO                   1071
#define IDC_TARIFCOMPLEXE               1074
#define IDC_SPINANNEE                   1076
#define IDC_ANNEETARIF                  1077
#define IDC_CADRE1                      1080
#define IDC_LIST_SEMTARIF               1081
#define IDC_EDIT_TARIF                  1082
#define IDC_EDITANNEE                   1083
#define IDC_COMBO_ELMT                  1085
#define IDC_FRAMELMT                    1086
#define IDC_NOSEMAINE                   1087
#define IDC_DATEDEBUT                   1088
#define IDC_TARIF                       1089
#define IDC_OPTIONREGIE                 1092
#define IDC_EDIT_CNC                    1093
#define IDC_TARIFBAC                    1094
#define IDC_NOMCOMPLEXE                 1095
#define IDC_TARIFPRODUIT                1095
#define IDC_TARIFNONMODIFIABLE          1098
#define IDC_CNC                         1099
#define IDC_COMPLEXE                    1100
#define IDC_NEWCNC                      1101
#define IDC_LIST_COMPLEXE               1102
#define IDC_REGIE                       1102
#define IDC_COMPLEXE2                   1103
#define IDC_BARRE                       1103
#define IDC_A                           1134
#define IDC_B                           1135
#define IDC_LISTBACDISPO                1135
#define IDC_C                           1136
#define IDC_LABEL_LISTBACS              1136
#define IDC_D                           1137
#define IDC_LIST_SELBACS                1137
#define IDC_E                           1138
#define IDC_LABEL_SEL_BACS              1138
#define IDC_F                           1139
#define IDC_LABEL_LISTCOMPS             1139
#define IDC_G                           1140
#define IDC_LABEL_SEL_COMPS             1140
#define IDC_H                           1141
#define IDC_LISTCOMPDISPO               1141
#define IDC_I                           1142
#define IDC_LIST_SELCOMPS               1142
#define IDC_J                           1143
#define IDC_LISTBAC_GROUPE              1143
#define IDC_K                           1144
#define IDC_LISTCOMPLEXE_GROUPE         1144
#define IDC_LISTBAC_GROUPE_COMPO        1144
#define IDC_L                           1145
#define IDC_LISTCMPLX_GROUPE_COMPO      1145
#define IDC_M                           1146
#define IDC_N                           1147
#define IDC_O                           1148
#define IDC_P                           1149
#define IDC_Q                           1150
#define IDC_R                           1151
#define IDC_S                           1152
#define IDC_T                           1153
#define IDC_U                           1154
#define IDC_V                           1155
#define IDC_W                           1156
#define IDC_X                           1157
#define IDC_Y                           1158
#define IDC_Z                           1159
#define ID_BASE_METTREJOUR              32771
#define ID_COMPLEXE_AJOUT               32773
#define ID_COMPLEXE_IMPORTDUTARIF       32774
#define ID_BAC_AJOUTER                  32775
#define ID_BAC_IMPORTDUTARIF            32776
#define ID_PRODUIT_AJOUTER              32777
#define ID_PRODUIT_IMPORTDUTARIF        32778
#define ID_FORMAT_AJOUTER               32779
#define ID_TEMPO_AJOUTER                32780
#define ID_COMPLEXE_MODIFIER            32781
#define ID_COMPLEXE_SUPPRIMER           32782
#define ID_BAC_MODIFIER                 32783
#define ID_BAC_SUPPRIMER                32784
#define ID_PRODUIT_MODIFIER             32785
#define ID_PRODUIT_SUPPRIMER            32786
#define ID_TEMPO_MODIFIER               32787
#define ID_TEMPO_SUPPRIMER              32788
#define ID_FORMAT_SUPPRIMER             32789
#define ID_SAISONNALITS_IMPORTER        32790
#define ID_DONNESCNC_IMPORTER           32791
#define ID_PRODUIT_AJOUTEDEPUIS         32792
#define ID_BAC_EDITMODIFIE_TARIF        32793
#define ID_COMPLEXE_EDITMODIFIE_TARIF   32794
#define ID_PRODUIT_EDITMODIFIE_TARIF    32795
#define ID_DONNEESCNC_MODIF             32796
#define ID_PRODUITFILMS_AJOUTEDEPUIS    32798
#define ID_BAC_AJOUT_GROUPE             32803
#define ID_BAC_SUPP_GROUPE              32804
#define ID_BAC_MODIF_GROUPE             32805
#define ID_COMPLX_AJOUT_GROUPE          32806
#define ID_COMPLX_SUPP_GROUPE           32807
#define ID_COMPLX_MODIF_GROUPE          32808

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1145
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
