//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by JFCFileDoc.rc
//
#define IDC_FD_TARIFBASE                3
#define IDR_FD_CONTEXTMENU_CIBLES       6
#define IDD_FD_DLG_TARIFMANUEL          1265
#define IDD_FD_DLG_OFFRE2_TITRES_SEL_SEGMENTS 1266
#define IDD_FD_DLG_OFFRE2_TITRES_SEL_SOURCE1 1267
#define IDD_FD_DLG_OFFRE2_TITRES_SEL_TYPESPOIDS 1268
#define IDD_FD_DLG_OFFRE2_TITRES_SEL_SOURCE 1269
#define IDC_FD_DATED                    1274
#define IDC_FD_DATEF                    1278
#define IDC_FD_SPINJ                    1326
#define IDC_FD_SPINS                    1328
#define IDC_FD_EDIT_TARIF               1348
#define IDC_FD_CBX_FORMAT               1349
#define IDC_FD_SEPAR                    1352
#define IDC_FD_TXTSUPPORT               1353
#define IDC_FD_TEXTJ                    1376
#define IDC_FD_TEXTS                    1377
#define IDC_FD_TXT5                     1390
#define IDC_FD_LBL_FORMAT               2219
#define IDC_FD_LBL_TARIF                2220
#define IDC_FD_BK_SAISIETARIF           2252
#define IDC_FD_TREE_RUBRIC_ITEMS        2278
#define IDC_FD_TREE_RUBRIC_PALETTES     2279
#define IDC_FD_TREE_RUBRIC_ITEMS3       2280
#define IDC_FD_TREE_RUBRIC_REFAFFS      2281
#define IDC_CS_LABEL_DATETAR            7081
#define IDC_CS_DATETAR_SEL              7085
#define IDC_CS_BK_DATETAR               7087
#define IDD_CS_DLG_DATETAR              7091
#define IDD_FD_DLG_DATETAR              7092
#define IDI_FD_RAZ                      7095
#define IDD_FD_DLG_MESSAGE              7096
#define IDB_FD_LEDNEUTRE                9000
#define IDB_FD_LEDORANGE                9001
#define IDB_FD_LEDROUGE                 9002
#define IDB_FD_LEDVERT                  9003
#define IDC_FD_BK                       9004
#define IDC_FD_BTN_LISTALL              9005
#define IDC_FD_BTN_RAZSEARCH            9006
#define IDC_FD_BTN_SEUILS               9007
#define IDC_FD_BTNOPTMOT                9008
#define IDC_FD_BTNR1_ITEMS              9009
#define IDC_FD_BTNOPTMOT2               9009
#define IDC_FD_BTNR1_LOTS               9010
#define IDC_FD_BTNR1_SOURCE             9011
#define IDD_FD_DLG_SUPPORTS_INEXISTANTS 9012
#define IDC_FD_SEP_TITLE2               9013
#define IDC_FD_BTNR2_PALETTES           9014
#define IDC_FD_BTNR2_SUPPORT            9015
#define IDC_FD_BTNR2_TITRES             9016
#define IDC_FD_BTNR3_AFFINITE           9017
#define IDC_FD_BTNR3_CIBLE              9018
#define IDC_FD_BTNR3_COUPLAGES          9019
#define IDC_FD_BTNREPRISE               9020
#define IDC_FD_BTNT                     9021
#define IDC_FD_BTNLNM                   9022
#define IDC_FD_BTNT2                    9023
#define IDC_FD_BTNLDP                   9024
#define IDC_FD_COMBO_SOURCE             9025
#define IDC_FD_BTNREPRISE4              9026
#define IDC_FD_BTNLDP30J                9027
#define IDD_FD_DLG_OFFRE2_TITRES        9028
#define IDB_FD_MOT1                     9029
#define IDC_FD_EDITSEARCH               9030
#define IDC_FD_IMPORT                   9031
#define IDC_FD_LIST_BAS                 9032
#define IDC_FD_LIST_HAUT                9033
#define IDC_FD_LIST_PERIOD              9034
#define IDC_FD_LIST_POIDS               9035
#define IDC_FD_LIST_SEGMENT             9036
#define IDC_BUTTON1                     9037
#define IDC_SEUILS                      9037
#define IDC_INFOS_SEUILS                9037
#define IDD_FD_DLG_OFFRE2_PERIODE       9038
#define IDC_FD_LIST_TERRAIN             9039
#define IDC_FD_INFO_SEUILS              9040
#define IDD_FD_DLG_OFFRE2_FORMATS       9041
#define IDC_FD_MIRE                     9042
#define IDC_FD_OK                       9043
#define IDC_FD_PROGRESS2                9044
#define IDC_FD_SEUILA                   9045
#define IDC_FD_SEUILL                   9046
#define IDC_EDIT1                       9047
#define IDC_ELEMS_INDICATOR             9047
#define IDC_SUPPORTS                    9048
#define IDC_FD_STATIC_CIBLES            9049
#define IDC_FD_STATIC_FILLE             9050
#define IDC_FD_STATIC_FILTRE            9051
#define IDC_LIST3                       9052
#define IDC_FD_STATIC_TITRE             9053
#define IDC_FD_STATIC_TTL               9054
#define IDC_FD_STATIC_TTLCIBLES         9055
#define IDC_FD_STATIC_TTLFILTRE         9056
#define IDC_FD_STATIC_TTLPERIOD         9057
#define IDC_FD_STATIC_TTLPOIDS          9058
#define IDC_FD_STATIC_TTLSEGMENT        9059
#define IDC_LST_TITRES                  9060
#define IDC_CK_SUPPORTS_SOURCE          9061
#define IDC_FD_STATIC_TTLSOURCE         9062
#define IDC_CK_COUPLAGES2               9063
#define IDC_CK_FAMILLES                 9064
#define IDC_FD_STATIC_TTLTERRAIN        9065
#define IDC_TITLE_SEARCH_STR            9066
#define IDC_USERTEXT                    9067
#define IDC_FD_STATIC_TTLTITRE          9068
#define IDC_FD_TREE_BAS                 9069
#define IDC_FD_TTL                      9070
#define IDC_FD_TXT                      9071
#define IDC_FD_TXT2                     9072
#define IDC_FD_X                        9073
#define IDD_FD_DLG_CHOIXMOTEUR          9074
#define IDD_FD_DLG_CIBLE                9075
#define IDD_FD_DLG_CTX                  9076
#define IDD_FD_DLG_CTXCHILD             9077
#define IDD_FD_DLG_FILTREAUDIENCE       9078
#define IDD_FD_DLG_OFFRE                9079
#define IDS_MESS_SEG_NONSEL             9080
#define IDS_FD_MESS_FCA_2007            9081
#define IDD_FD_DLG_SRC_UNIQUE           9082
#define IDD_FD_DLG_SUPPORT              9083
#define IDS_FD_TITRE_OFFRE              9084
#define IDS_FD_FILTER                   9085
#define IDS_FD_NONAME                   9086
#define IDS_FD_STR_CPL                  9087
#define IDS_FD_STR_ERR_CIBLE            9088
#define IDS_FD_STR_ERR_IAFF             9089
#define IDS_FD_STR_ERR_SUPPORT          9090
#define IDS_FD_STR_ERR_TERRA            9091
#define IDS_FD_STR_ERR_TERRC            9092
#define IDS_FD_STR_ERRSEUIL             9093
#define IDS_FD_STR_ITEM                 9094
#define IDS_FD_STR_ITEMAFF              9095
#define IDS_FD_STR_LOT                  9096
#define IDS_FD_STR_PALETTES             9097
#define IDS_FD_STR_TITRE                9098
#define IDI_FD_CHECK                    9099
#define IDS_FD_ERRITEM                  9100
#define IDC_FD_SEP_TITLE1               9101
#define IDI_FD_NOCHECK                  9102
#define IDS_FD_ABAQUE                   9103
#define IDD_FD_DLG_OFFRE2               9104
#define IDS_FD_PROBA                    9105
#define IDD_FD_DLG_OFFRE2_CIBLES        9106
#define IDC_RAZFILTER                   9107
#define IDC_RAZSELECT                   9109
#define IDC_FD_BTN_INFO_SEUILS          9113
#define IDB_BITMAP1                     9114
#define IDB_FD_MOT2                     9115
#define IDS_STRING9102                  9116
#define IDS_FD_MAX_TARIF                9117
#define IDS_FD_MESS_AEPM_JANV_DEC_2006  9118
#define IDC_TEST456                     9119
#define IDC_TABCTRL                     9120
#define IDC_TABCTRL_OFFRE               9121
#define IDC_LST_FILTRES_ELEMENTS        9122
#define IDC_LST_FILTRES                 9123
#define IDC_CBB_SOURCES                 9124
#define IDC_CK_TITRES                   9125
#define IDC_CK_COUPLAGES                9126
#define IDC_TABCTRL_SELECTION           9127
#define IDC_LB_SEL_SEGMENTS             9128
#define IDC_CK_SUPPORTS_FROM_SOURCE     9128
#define IDC_CB_SEL_SOURCE               9129
#define IDC_LB_SEL_TYPESPOIDS           9129
#define IDC_LB_SEL_TERRAINS             9130
#define IDC_MONTHCALENDAR1              9130
#define IDC_MONTHCALENDAR2              9131
#define IDC_FD_STATIC_TTLFILTRES        9131
#define IDC_FD_STATIC_TTLTITRES         9132
#define IDC_FD_STATIC_TTLFORMATS        9133
#define IDC_RAZFORMATS                  9134
#define IDC_LST_FORMATS                 9135
#define IDC_LST_ITEMS_PALETTES          9136
#define IDC_CK_ITEMS_FROM_SOURCE        9137
#define IDC_CIBLES_SEARCH_STR           9138
#define IDC_FD_TREE_CIBLES              9139
#define IDC_LST_CIBLES                  9140
#define IDC_FD_TREE_PALETTES            9141
#define IDC_FD_PERIOD_TITRE1            9142
#define IDC_FD_PERIOD_TITRE2            9143
#define IDC_FD_PERIOD_TITRE3            9144
#define IDC_QU_MESSAGE                  9144
#define IDC_FD_PERIOD_TITRE4            9145
#define IDC_LST_MESSAGE                 9146
#define IDM_FD_CIBLES_REFAFFINITE       32771
#define ID_CONTEXTEMENUCIBLES_AFFICHERSEUILS 32772
#define IDM_FD_CONTEXTEMENUCIBLES_AFFICHERSEUILS 32773
#define IDM_OF_CIBLES_REFAFFINITE       32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        7097
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         9146
#define _APS_NEXT_SYMED_VALUE           9200
#endif
#endif
