//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ChoixSupportExt.rc
//
#define IDC_CS_AUCUN_RANG               3
#define IDC_CS_AUCUN_RANG2              4
#define IDC_CS_TOUS_RANG                4
#define IDB_CS_BITMAP_RANG              1999
#define IDB_CS_DOWN                     2077
#define IDB_CS_UP                       2078
#define IDI_CS_CHECKOFF                 4056
#define IDI_CS_CHECKON                  4058
#define IDD_CS_DLG_PUPITRE_ECH          7000
#define IDD_CS_DLG_CHOIXSUPPORT         7001
#define IDI_CS_ICON                     7002
#define IDR_CS_MENU                     7003
#define IDD_CS_DLG_ECHELLES             7004
#define IDD_CS_DLG_MAPPING              7006
#define IDD_CS_DLG_CUMULATIVITE         7008
#define IDC_CS_CADRE_CUMULATIVITE       7009
#define IDD_CS_DLG_DUPLICATION          7010
#define IDC_CS_CADRE_GRAPHCUM           7011
#define IDC_CS_CADRE_DUPLICATION        7012
#define IDC_CS_ECHELLES                 7013
#define IDC_CS_LABEL_GRANDEURS          7014
#define IDC_CS_MAPPING                  7015
#define IDC_CS_LIST_GRANDEURS           7016
#define IDD_CS_DLG_PUPITRE_MAP          7017
#define IDC_CS_CUMULATIVITE             7018
#define IDC_CS_LABEL_DUPLI              7019
#define IDD_CS_DLG_PUPITRE_CUM          7020
#define IDC_CS_STATIC_PUPITRE_MAP       7021
#define IDC_CS_DUPLICATION              7022
#define IDC_CS_STATIC_PUPITRE_ECH       7023
#define IDC_CS_LABEL_FAMILLES           7024
#define IDC_CS_CADRE_ECH                7025
#define IDC_CS_LABEL_FAMILLES2          7026
#define IDD_CS_DLG_PUPITRE_DUP          7027
#define IDC_CS_TITRE_ECHELLE            7028
#define IDC_CS_CADRE_SEL1               7029
#define IDC_CS_GRID_ECHELLE             7030
#define IDC_CS_LABEL_CENTRES            7031
#define IDC_CS_BTN_HEADER1              7032
#define IDC_CS_CADRE_RESULT             7033
#define IDC_CS_BTN_HEADER2              7034
#define IDC_CS_LABEL_SUPPORTS           7035
#define IDC_CS_BTN_HEADER3              7036
#define IDC_CS_LABEL_TERRAINS           7037
#define IDC_CS_LABEL_CIBLES             7038
#define IDC_CS_LIST_TERRAINS            7039
#define IDC_CS_LIST_CIBLES              7040
#define IDC_CS_LABEL_FORMATS            7041
#define IDC_CS_LABEL_CREUSET            7042
#define IDC_CS_CADRE_ECHELLE            7043
#define IDC_CS_LABEL_REFAFF             7044
#define IDC_CS_CADRE_SEL2               7045
#define IDC_CS_LIST_FORMATS             7046
#define IDC_CS_CADRE_BTNFIXE            7047
#define IDC_CS_CADRE_ONGLET             7048
#define IDD_CS_DLG_PLATEAU              7049
#define IDC_CS_LIST_REFAFF              7050
#define IDC_CS_FOND                     7051
#define IDC_CS_LABEL_FILTRE_AUDIENCE    7052
#define IDC_CS_FORMAT                   7053
#define IDC_CS_LABEL_CONTEXTE_LECT      7054
#define IDC_CS_OFFRE                    7055
#define IDC_CS_LABEL_NIVEAU             7056
#define IDC_CS_DATETAR                  7057
#define IDC_CS_LABEL_SEGPOP             7058
#define IDC_CS_TITRE                    7059
#define IDC_CS_LIST_SEGPOP              7060
#define IDD_CS_ABOUTBOX                 7061
#define IDC_CS_LABEL_DATETAR            7081
#define IDI_CS_LEDOFF                   7082
#define IDI_CS_LEDON                    7083
#define IDC_DATETIMEPICKER1             7084
#define IDC_CS_DATETAR_SEL              7085
#define IDI_CS_LEDSEL                   7086
#define IDC_CS_BK_DATETAR               7087
#define IDB_CS_LEDNEUTRE                7088
#define IDC_CS_TITRE_CUMULATIVITE       7089
#define IDB_CS_LEDORANGE                7090
#define IDS_CS_MOTABAQUE                7091
#define IDS_CS_FILTER                   7092
#define IDB_CS_LEDROUGE                 7093
#define IDB_CS_LEDVERT                  7094
#define IDS_CS_MOTABAQUEETAL            7095
#define IDC_CS_GRID_CUMULATIVITE        7096
#define IDS_CS_MOTPROBA                 7097
#define IDC_CS_TITRE_DUPLICATION        7098
#define IDS_CS_CTRL_INDEXDROPDOWNLIST   7099
#define IDD_CS_DLG_ORDRE_HEADER         7100
#define IDS_CS_MENUFAMILLE              7101
#define IDC_CS_GRID_DUPLICATION         7102
#define IDS_CS_TITREADDED               7103
#define IDC_CS_CADRE_CUM                7104
#define IDS_CS_FILTER_ATP               7105
#define IDC_CS_CADRE_DUP                7106
#define IDI_ICON1                       7107
#define IDI_CS_FLECHE                   7108
#define IDC_CS_STATIC_PUPITRE_CUM       7109
#define IDD_CS_DLG_ORDRE_GRAND_ECH      7110
#define IDC_CS_LABEL_COURBES            7111
#define IDC_CS_TIRET_TITRE              7112
#define IDC_CS_BK_ORDREHEADER           7113	
#define IDC_CS_PROGRESS_RESULTCUM       7114
#define IDS_CS_A_UN_AN                  7115
#define IDC_CS_GRID_COLOR_CUM           7116
#define IDC_CS_PROGRESS_RESULTECH       7117
#define IDS_CS_ABSCISSE_ND              7118
#define IDS_CS_ORDONNEE_ND              7119
#define IDC_CS_FL1                      7120
#define IDC_CS_LABEL_GRANDCUM           7121
#define IDC_CS_LIST_GRANDCUM            7122	
#define IDC_CS_PROGRESS_RESULTDUP       7123
#define IDC_CS_LABEL_GRANDDUP           7124
#define IDC_CS_STATIC_PUPITRE_DUP       7125
#define IDC_CS_LIST_GRANDDUP            7126
#define IDC_CS_TITRE_MAPPING            7127
#define IDC_CS_GRID_MAPPING             7128
#define IDC_CS_PROGRESS_RESULTMAP       7129
#define IDC_CS_LABEL_SEPCOLOR           7130
#define IDC_CS_LABEL_GROUPCOLOR         7131
#define IDC_CS_SPLIT_HORZ               7132
#define IDC_CS_SPLIT2_HORZ              7133
#define IDC_CS_GRAPHCUM                 7134
#define IDC_CS_SCROLLGRAPH              7135
#define IDC_CS_BK_ORDRE_GRDECH          7136
#define IDC_CS_LABEL_TITRE              7137
#define IDC_LST_                        7138
#define IDC_CS_LST_GRANDEURS            7139
#define IDC_CS_CADRE_GRIDMAP            7140
#define IDC_CS_CADRE_MAPPING            7141
#define IDC_CS_LABEL_ABS_MAPPING        7142
#define IDC_CS_LABEL_ORD_MAPPING        7143
#define IDC_LIST_GRANDABS               7144
#define IDC_CS_GRD_UP                   7145
#define IDC_LIST_GRANDORD               7146
#define IDC_CS_GRD_DOWN                 7147
#define IDD_CS_DLG_RANG_RESULT          7148
#define IDC_CHK_RANG_VISIBLE            7149
#define IDC_CHECK1                      7150
#define ID_OPTIONS                      32385
#define ID_PARAM                        32786
#define ID_MARQUAGE                     32787
#define ID_AFFICHAGE                    32788
#define ID_FEN                          32789
#define IDM_CS_OFFRES_FORMATS           32799
#define IDM_CS_CIBLES                   32802
#define IDM_CS_FORMATS                  32804
#define IDM_CS_PERIODETARIF             32805
#define IDM_CS_PLATEAU_NOUVEAU          32807
#define IDM_CS_PLATEAU_ENREGISTRER      32808
#define IDM_CS_PLATEAU_OUVRIR           32809
#define IDM_CS_PLATEAU_ENREGISTRERSOUS  32810
#define IDM_CS_PLATEAU_FERMER           32811
#define IDM_CS_PLATEAU_QUITTER          32812
#define IDM_CS_SOURCES                  32813
#define IDM_CS_SUPPORTS                 32814
#define ID_                             32815
#define IDM_CS_ABOUTBOX                 32817
#define IDM_CS_PLATEAU_IMPORTETUDE      32818
#define ID_AFFICHAGE_CHOISIRLAPALETTEDECOULEURS 32818
#define IDM_CS_PALETTE_1                32830
#define IDM_CS_PALETTE_2                32831
#define IDM_CS_PALETTE_3                32832
#define IDM_CS_PALETTE_4                32833
#define IDM_CS_PALETTE_5                32834
#define IDM_CS_PALETTE_6                32835
#define IDM_CS_PALETTE_7                32836
#define IDM_CS_PALETTE_8                32837
#define IDM_CS_PALETTE_9                32838
#define IDM_CS_PALETTE_10               32839
#define IDM_CS_PALETTE_11               32840
#define IDM_CS_PALETTE_12               32841
#define IDM_CS_PALETTE_13               32842
#define IDM_CS_PALETTE_14               32843
#define IDM_CS_PALETTE_15               32844
#define IDM_CS_1_INSERTION              32853
#define IDM_CS_2_INSERTIONS             32854
#define IDM_CS_3_INSERTIONS             32855
#define IDM_CS_4_INSERTIONS             32856
#define IDM_CS_5_INSERTIONS             32857
#define IDM_CS_6_INSERTIONS             32858
#define IDM_CS_7_INSERTIONS             32859
#define IDM_CS_8_INSERTIONS             32860
#define IDM_CS_9_INSERTIONS             32861
#define IDM_CS_10_INSERTIONS            32862
#define IDM_CS_MAX_INSERTIONS           32863
#define IDM_CS_TEST                     32865
#define ID_OPTIONS_M                    32869
#define ID_OPTIONS_BASEDECALCULDESGRP   32870
#define ID_OPTIONS_BASETARIFAIRE        32872
#define IDM_CS_OPT_REPRISEENMAIN        32874
#define IDM_CS_OPT_LNMMAGAZINE          32876
#define IDM_CS_OPT_LDPQUOTIDIEN         32877
#define IDM_CS_OPT_COURBE_MEMODEMEMO    32878
#define IDM_CS_CONTEXTLECTURE           32879
#define IDM_CS_MODEL                    32883
#define IDM_CS_MODELETAL                32884
#define IDM_CS_PROBABILIT               32885
#define IDM_CS_OPT_BASECALCGRPC_NAT     32888
#define IDM_CS_OPT_BASECALCGRPC_REG     32889
#define IDM_CS_BASETARIFNEGO            32895
#define IDM_CS_BASETARIFPLAQ            32896
#define IDM_CS_FILTRE_AUDIENCE          32898
#define IDM_CS_ORDRE_ENTETES            32900
#define ID_CS__TRICOL1                  32902
#define IDM_CS_OPTIONS_LDPBIMESTR       32906
#define IDM_CS_ORDRE_GRANDECH           32920
#define IDM_CS_AFFOPTMOTEUR             32922
#define ID_Menu                         32923
#define ID_CS_AFFICHAGE_NBD             32924
#define ID_CS_NBD_AUCUNEDECIMALE        32925
#define ID_CS_NBD_1DECIMALE             32926
#define ID_CS_NBD_2DECIMALE             32927
#define IDM_CS_RANG_COL_VISIBLE         32932
#define IDM_CS_MOYENNE_VISIBLE          32934
#define ID_PARAM_AFFICHAGEDESRANGSPARR  32935
#define ID_PLATEAU_EXPORTERDANSLEPRESSEPAPIER 32949
#define ID_PLATEAU_EXPORTERDANSUNFICHIER 32950
#define ID_EXPORTERDANSUNFICHIER_ECHELLE 32955
#define IDM_CS_EXPORTER_PRESSEPAPIER_ECHELLE 32959
#define IDM_CS_EXPORTER_PRESSEPAPIER_MAPPING 32960
#define IDM_CS_EXPORTER_PRESSEPAPIER_CUMULATIVITE 32961
#define IDM_CS_EXPORTER_PRESSEPAPIER_DUPLICATION 32962
#define IDM_CS_EXPORTER_FICHIER_ECHELLE 32964
#define IDM_CS_EXPORTER_FICHIER_MAPPING 32965
#define IDM_CS_EXPORTER_FICHIER_CUMULATIVITE 32966
#define IDM_CS_EXPORTER_FICHIER_DUPLICATION 32967
#define IDM_CS_EXPORTER_PRESSEPAPIER_GRAPHMAPPING 32969
#define IDM_CS_EXPORTER_FICHIER_GRAPHMAPPING 32971
#define ID_PLATEAU_IMPRESSION           32972
#define IDM_CS_PRINT_ECHELLE            32973
#define IDM_CS_PRINT_MAPPING            32974
#define IDM_CS_PRINT_CUMULATIVITE       32975
#define IDM_CS_PRINT_DUPLICATION        32976
#define IDM_CS_12_INSERTIONS            32977
#define IDM_CS_24_INSERTIONS            32978
#define IDM_CS_53_INSERTIONS            32979
#define IDM_CS_365_INSERTIONS           32980
#define IDM_CS_105_INSERTIONS           32982
#define IDM_CS_EXPORTER_PRESSEPAPIER_GRAPHCUMUL 32984
#define IDM_CS_EXPORTER_PRESSEPAPIER_ECHELLE_PARCIBLE 32987
#define IDM_CS_EXPORTER_FICHIER_ECHELLE_PARCIBLE 32988
#define IDM_CS_PRINT_ECHELLE_PARCIBLE   32990
#define IDM_CS_EXPORTER_FICHIER_GRAPHCUMUL 32992
#define IDM_CS_OPT_CUMUL_FAMILLE        32994
#define ID_OPTIONSDECALCUL_AAAAA        32995
#define IDM_CS_OPT_FAM_CUMUL            32998
#define IDM_CS_OPT_FAM_MOYENNE          32999
#define ID_PLATEAU_EXPORTERVERSEXCEL    33000
#define ID_PLATEAU_EXPORTERVERSEXCEL33001 33001
#define IDM_CS_EXPORTER_EXCEL_ECHELLE   33002
#define IDM_CS_EXPORTER_EXCEL_CIBLES    33003
#define IDM_CS_EXPORTER_EXCEL_PARCIBLE  33004
#define IDM_CS_EXPORTER_EXCEL_MAPPING   33005
#define IDM_CS_EXPORTER_EXCEL_GRAPHMAPPING 33006
#define IDM_CS_EXPORTER_EXCEL_CUMULATIVITE 33007
#define IDM_CS_EXPORTER_EXCEL_DUPLICATION 33008
#define IDM_CS_EXPORTER_EXCEL_GRAPHCUMUL 33009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        7103
#define _APS_NEXT_COMMAND_VALUE         33010
#define _APS_NEXT_CONTROL_VALUE         7151
#define _APS_NEXT_SYMED_VALUE           7105
#endif
#endif
