//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18047
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par xsd, Version=4.0.30319.17929.
// 
namespace IMP_CODI_PRESS_TARIFS_LOG {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NewDataSet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TARIF_DELETE", typeof(NewDataSetTARIF_DELETE), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("TARIF_INSERT", typeof(NewDataSetTARIF_INSERT), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class NewDataSetTARIF_DELETE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomSupportField;
        
        private string nomPeriodeField;
        
        private string dateAppliPeriodeField;
        
        private string dateFinPeriodeField;
        
        private string nom_ligne_offreField;
        
        private string statutField;
        
        private string codeTypePubliciteField;
        
        private string typePubliciteField;
        
        private string codeTypeEditionField;
        
        private string typeEditionField;
        
        private string codeCouleurField;
        
        private string couleurField;
        
        private string codeFormatField;
        
        private string formatField;
        
        private string codeEmplacementField;
        
        private string emplacementField;
        
        private string codeRubriqueField;
        
        private string rubriqueField;
        
        private string codeImplantationField;
        
        private string implantationField;
        
        private string codeTypeEncartField;
        
        private string typeEncartField;
        
        private string codeTypeTraitementField;
        
        private string typeTraitementField;
        
        private string codePaginationField;
        
        private string paginationField;
        
        private string codeDiffusionField;
        
        private string diffusionField;
        
        private string codeSupportField;
        
        private string supportField;
        
        private string tarifField;
        
        private string dateModificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NomSupport {
            get {
                return this.nomSupportField;
            }
            set {
                this.nomSupportField = value;
                this.RaisePropertyChanged("NomSupport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NomPeriode {
            get {
                return this.nomPeriodeField;
            }
            set {
                this.nomPeriodeField = value;
                this.RaisePropertyChanged("NomPeriode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateAppliPeriode {
            get {
                return this.dateAppliPeriodeField;
            }
            set {
                this.dateAppliPeriodeField = value;
                this.RaisePropertyChanged("DateAppliPeriode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateFinPeriode {
            get {
                return this.dateFinPeriodeField;
            }
            set {
                this.dateFinPeriodeField = value;
                this.RaisePropertyChanged("DateFinPeriode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nom_ligne_offre {
            get {
                return this.nom_ligne_offreField;
            }
            set {
                this.nom_ligne_offreField = value;
                this.RaisePropertyChanged("Nom_ligne_offre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Statut {
            get {
                return this.statutField;
            }
            set {
                this.statutField = value;
                this.RaisePropertyChanged("Statut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeTypePublicite {
            get {
                return this.codeTypePubliciteField;
            }
            set {
                this.codeTypePubliciteField = value;
                this.RaisePropertyChanged("CodeTypePublicite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TypePublicite {
            get {
                return this.typePubliciteField;
            }
            set {
                this.typePubliciteField = value;
                this.RaisePropertyChanged("TypePublicite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeTypeEdition {
            get {
                return this.codeTypeEditionField;
            }
            set {
                this.codeTypeEditionField = value;
                this.RaisePropertyChanged("CodeTypeEdition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TypeEdition {
            get {
                return this.typeEditionField;
            }
            set {
                this.typeEditionField = value;
                this.RaisePropertyChanged("TypeEdition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeCouleur {
            get {
                return this.codeCouleurField;
            }
            set {
                this.codeCouleurField = value;
                this.RaisePropertyChanged("CodeCouleur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Couleur {
            get {
                return this.couleurField;
            }
            set {
                this.couleurField = value;
                this.RaisePropertyChanged("Couleur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeFormat {
            get {
                return this.codeFormatField;
            }
            set {
                this.codeFormatField = value;
                this.RaisePropertyChanged("CodeFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("Format");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeEmplacement {
            get {
                return this.codeEmplacementField;
            }
            set {
                this.codeEmplacementField = value;
                this.RaisePropertyChanged("CodeEmplacement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Emplacement {
            get {
                return this.emplacementField;
            }
            set {
                this.emplacementField = value;
                this.RaisePropertyChanged("Emplacement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeRubrique {
            get {
                return this.codeRubriqueField;
            }
            set {
                this.codeRubriqueField = value;
                this.RaisePropertyChanged("CodeRubrique");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Rubrique {
            get {
                return this.rubriqueField;
            }
            set {
                this.rubriqueField = value;
                this.RaisePropertyChanged("Rubrique");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeImplantation {
            get {
                return this.codeImplantationField;
            }
            set {
                this.codeImplantationField = value;
                this.RaisePropertyChanged("CodeImplantation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Implantation {
            get {
                return this.implantationField;
            }
            set {
                this.implantationField = value;
                this.RaisePropertyChanged("Implantation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeTypeEncart {
            get {
                return this.codeTypeEncartField;
            }
            set {
                this.codeTypeEncartField = value;
                this.RaisePropertyChanged("CodeTypeEncart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TypeEncart {
            get {
                return this.typeEncartField;
            }
            set {
                this.typeEncartField = value;
                this.RaisePropertyChanged("TypeEncart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeTypeTraitement {
            get {
                return this.codeTypeTraitementField;
            }
            set {
                this.codeTypeTraitementField = value;
                this.RaisePropertyChanged("CodeTypeTraitement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TypeTraitement {
            get {
                return this.typeTraitementField;
            }
            set {
                this.typeTraitementField = value;
                this.RaisePropertyChanged("TypeTraitement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodePagination {
            get {
                return this.codePaginationField;
            }
            set {
                this.codePaginationField = value;
                this.RaisePropertyChanged("CodePagination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pagination {
            get {
                return this.paginationField;
            }
            set {
                this.paginationField = value;
                this.RaisePropertyChanged("Pagination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeDiffusion {
            get {
                return this.codeDiffusionField;
            }
            set {
                this.codeDiffusionField = value;
                this.RaisePropertyChanged("CodeDiffusion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Diffusion {
            get {
                return this.diffusionField;
            }
            set {
                this.diffusionField = value;
                this.RaisePropertyChanged("Diffusion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeSupport {
            get {
                return this.codeSupportField;
            }
            set {
                this.codeSupportField = value;
                this.RaisePropertyChanged("CodeSupport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Support {
            get {
                return this.supportField;
            }
            set {
                this.supportField = value;
                this.RaisePropertyChanged("Support");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Tarif {
            get {
                return this.tarifField;
            }
            set {
                this.tarifField = value;
                this.RaisePropertyChanged("Tarif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateModification {
            get {
                return this.dateModificationField;
            }
            set {
                this.dateModificationField = value;
                this.RaisePropertyChanged("DateModification");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class NewDataSetTARIF_INSERT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomSupportField;
        
        private string nomPeriodeField;
        
        private string dateAppliPeriodeField;
        
        private string dateFinPeriodeField;
        
        private string nom_ligne_offreField;
        
        private string statutField;
        
        private string codeTypePubliciteField;
        
        private string typePubliciteField;
        
        private string codeTypeEditionField;
        
        private string typeEditionField;
        
        private string codeCouleurField;
        
        private string couleurField;
        
        private string codeFormatField;
        
        private string formatField;
        
        private string codeEmplacementField;
        
        private string emplacementField;
        
        private string codeRubriqueField;
        
        private string rubriqueField;
        
        private string codeImplantationField;
        
        private string implantationField;
        
        private string codeTypeEncartField;
        
        private string typeEncartField;
        
        private string codeTypeTraitementField;
        
        private string typeTraitementField;
        
        private string codePaginationField;
        
        private string paginationField;
        
        private string codeDiffusionField;
        
        private string diffusionField;
        
        private string codeSupportField;
        
        private string supportField;
        
        private string tarifField;
        
        private string dateModificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NomSupport {
            get {
                return this.nomSupportField;
            }
            set {
                this.nomSupportField = value;
                this.RaisePropertyChanged("NomSupport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NomPeriode {
            get {
                return this.nomPeriodeField;
            }
            set {
                this.nomPeriodeField = value;
                this.RaisePropertyChanged("NomPeriode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateAppliPeriode {
            get {
                return this.dateAppliPeriodeField;
            }
            set {
                this.dateAppliPeriodeField = value;
                this.RaisePropertyChanged("DateAppliPeriode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateFinPeriode {
            get {
                return this.dateFinPeriodeField;
            }
            set {
                this.dateFinPeriodeField = value;
                this.RaisePropertyChanged("DateFinPeriode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nom_ligne_offre {
            get {
                return this.nom_ligne_offreField;
            }
            set {
                this.nom_ligne_offreField = value;
                this.RaisePropertyChanged("Nom_ligne_offre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Statut {
            get {
                return this.statutField;
            }
            set {
                this.statutField = value;
                this.RaisePropertyChanged("Statut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeTypePublicite {
            get {
                return this.codeTypePubliciteField;
            }
            set {
                this.codeTypePubliciteField = value;
                this.RaisePropertyChanged("CodeTypePublicite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TypePublicite {
            get {
                return this.typePubliciteField;
            }
            set {
                this.typePubliciteField = value;
                this.RaisePropertyChanged("TypePublicite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeTypeEdition {
            get {
                return this.codeTypeEditionField;
            }
            set {
                this.codeTypeEditionField = value;
                this.RaisePropertyChanged("CodeTypeEdition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TypeEdition {
            get {
                return this.typeEditionField;
            }
            set {
                this.typeEditionField = value;
                this.RaisePropertyChanged("TypeEdition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeCouleur {
            get {
                return this.codeCouleurField;
            }
            set {
                this.codeCouleurField = value;
                this.RaisePropertyChanged("CodeCouleur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Couleur {
            get {
                return this.couleurField;
            }
            set {
                this.couleurField = value;
                this.RaisePropertyChanged("Couleur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeFormat {
            get {
                return this.codeFormatField;
            }
            set {
                this.codeFormatField = value;
                this.RaisePropertyChanged("CodeFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("Format");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeEmplacement {
            get {
                return this.codeEmplacementField;
            }
            set {
                this.codeEmplacementField = value;
                this.RaisePropertyChanged("CodeEmplacement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Emplacement {
            get {
                return this.emplacementField;
            }
            set {
                this.emplacementField = value;
                this.RaisePropertyChanged("Emplacement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeRubrique {
            get {
                return this.codeRubriqueField;
            }
            set {
                this.codeRubriqueField = value;
                this.RaisePropertyChanged("CodeRubrique");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Rubrique {
            get {
                return this.rubriqueField;
            }
            set {
                this.rubriqueField = value;
                this.RaisePropertyChanged("Rubrique");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeImplantation {
            get {
                return this.codeImplantationField;
            }
            set {
                this.codeImplantationField = value;
                this.RaisePropertyChanged("CodeImplantation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Implantation {
            get {
                return this.implantationField;
            }
            set {
                this.implantationField = value;
                this.RaisePropertyChanged("Implantation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeTypeEncart {
            get {
                return this.codeTypeEncartField;
            }
            set {
                this.codeTypeEncartField = value;
                this.RaisePropertyChanged("CodeTypeEncart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TypeEncart {
            get {
                return this.typeEncartField;
            }
            set {
                this.typeEncartField = value;
                this.RaisePropertyChanged("TypeEncart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeTypeTraitement {
            get {
                return this.codeTypeTraitementField;
            }
            set {
                this.codeTypeTraitementField = value;
                this.RaisePropertyChanged("CodeTypeTraitement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TypeTraitement {
            get {
                return this.typeTraitementField;
            }
            set {
                this.typeTraitementField = value;
                this.RaisePropertyChanged("TypeTraitement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodePagination {
            get {
                return this.codePaginationField;
            }
            set {
                this.codePaginationField = value;
                this.RaisePropertyChanged("CodePagination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pagination {
            get {
                return this.paginationField;
            }
            set {
                this.paginationField = value;
                this.RaisePropertyChanged("Pagination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeDiffusion {
            get {
                return this.codeDiffusionField;
            }
            set {
                this.codeDiffusionField = value;
                this.RaisePropertyChanged("CodeDiffusion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Diffusion {
            get {
                return this.diffusionField;
            }
            set {
                this.diffusionField = value;
                this.RaisePropertyChanged("Diffusion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeSupport {
            get {
                return this.codeSupportField;
            }
            set {
                this.codeSupportField = value;
                this.RaisePropertyChanged("CodeSupport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Support {
            get {
                return this.supportField;
            }
            set {
                this.supportField = value;
                this.RaisePropertyChanged("Support");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Tarif {
            get {
                return this.tarifField;
            }
            set {
                this.tarifField = value;
                this.RaisePropertyChanged("Tarif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateModification {
            get {
                return this.dateModificationField;
            }
            set {
                this.dateModificationField = value;
                this.RaisePropertyChanged("DateModification");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
